### ISSUE TITLE
Invisible layer in Tilemap is visible in Arcade

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#1002]
1. Create Tilemap
2. Add Image layer
3. Set layer as invisible
4. Run code:
```
import arcade
arcade.open_window(400, 400, 'Invisible layer')
tile_map = arcade.load_tilemap('map.json')
scene = arcade.Scene.from_tilemap(tile_map)
arcade.start_render()
scene.draw()
arcade.finish_render()
arcade.run()
```
5. Image is visible:
![изображение](https://user-images.githubusercontent.com/21060932/137081717-b8c8f9a0-3a39-465b-b653-4595063de2cc.png)

`map.json`:
```
{ "compressionlevel":-1,
 "height":10,
 "infinite":false,
 "layers":[
        {
         "id":2,
         "image":"image.png",
         "name":"IMAGE",
         "offsetx":149.333333333333,
         "offsety":282.666666666667,
         "opacity":1,
         "type":"imagelayer",
         "visible":false,
         "x":0,
         "y":0
        }],
 "nextlayerid":3,
 "nextobjectid":1,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.7.2",
 "tileheight":45,
 "tilesets":[],
 "tilewidth":45,
 "type":"map",
 "version":"1.6",
 "width":10
}
```
`image.png`:
![image](https://user-images.githubusercontent.com/21060932/137081977-ba6e739e-db35-45d1-b76f-6303bc7ecab1.png)

**Comment by Cleptomania** [comment]
This will be a somewhat straight forward fix. Pytiled-parser already supports visibility for layers. 

The question is how do we want the behavior to be, if a layer is invisible, do we want to literally not process it into a SpriteList/Object List, or should everything within just be transparent and not drawn?

I think my preferred approach would be for the Tilemap to still process it into a SpriteList, but add a way to Scene to make a layer invisible, and it will not draw a layer if it is, but would still get processed.

**Comment by Cleptomania** [comment]
There is support for this in the development branch now. 

A `visible` attribute has been added to SpriteList, which can be used to enable/disable drawing for a given SpriteList, so this has uses and benefits beyond TileMaps as well.

The TileMap class now just leverages this attribute to draw or not draw a SpriteList.

Should note this only disables drawing, so the SpriteList will still be processed as normal and added to scenes, and if you have collisions with it or something that will still happen, this exclusively relates to actually drawing it.

This property can be leveraged to dynamically change if a SpriteList should be visible without having to do logic to decide to draw it in `on_draw`, you can easily set the value during `on_update` or something, and when it's drawn during `on_draw`, it will just be ignored.

**Comment by einarf** [comment]
2.6.4 released
