### ISSUE TITLE
Mismatch between doc build script and guide on how to run it

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1003]
### What documentation needs to change? 

The documentation for how to build the windows documentation says `make doc` should be used, but the actual windows build script reports and accepts `make docs` (plural).

### Where is it located?
The [windows how to compile page](https://api.arcade.academy/en/latest/development/how_to_compile.html#windows) page.

### What is wrong with it? How can it be improved?
Choose one and make them consistent, preferably across platforms.

**Comment by Cleptomania** [comment]
I'm gonna close this in favor of expanding #995 and tracking it there.
