### ISSUE TITLE
Incorrect or unclear build output path reported by windows build script

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1004]
### Actual behavior:
The path for compiled documentation is reported incorrectly at the end of the current version of the windows `make docs` build script:
```
build succeeded, 221 warnings.

The HTML pages are in build\html.
sitemap.xml was generated for URL https://api.arcade.academy/ in C:\Users\user\Projects\arcade\doc\build\htm
l/sitemap.xml
```

A beginner attempting to change into that directory on windows will get an error because the directory specified does not exist:
```
>cd build\html
The system cannot find the path specified.
```

### Expected behavior:
The full path from the script's run directory should be reported instead, without a trailing period:
```
The HTML pages are in doc\build\html
```

### Steps to reproduce/example code:
Run `make docs` on a windows system to build the documentation.

**Comment by pvcraven** [comment]
Running "make html" from the "doc" directory builds the docs, and that path is correct from that directory.

Running "make docs" from the root just changes to that directory and then runs "make html". I'm not sure a super-easy way to put out the proper directory depending on where the developer started the build.

**Comment by pushfoo** [comment]
Ty for the fix. Improving the beginner doc and build script is turning into a larger ongoing project, so I you could safely close this ticket since it's extremely specific in scope.
