### ISSUE TITLE
Add CI check for constructor docstrings outside the project's standard locations

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1007]
### What should be added/changed?
A CI check to scan for constructor docstrings outside the project standard location, which is in the class-level attributes rather than on the constructor.

### What would it help with?
It would help preventing issues like #1005 from arising in the future.

It would also help both beginner contributors and maintainers by saving everyone time. Beginner contributors are likely to put constructor documentation on constructors. Having CI flag this and link the relevant documentation ([see discussion of #995](https://github.com/pythonarcade/arcade/issues/995#issuecomment-942252689)) would prevent having to explain this repeatedly on discord or in comments on github issues.

**Comment by pushfoo** [comment]
There are at least two ways of doing this:
- a kludge using the `inspect` module
- working with sphinx's internals to customize the build process

Both have their downsides.

**Comment by pushfoo** [comment]
We might be able to omit the experimental directory from these checks.

**Comment by einarf** [comment]
This could be a unittest. Then we could potentially also run that with all unit tests that don't need a context.

**Comment by einarf** [comment]
This was more or less a 5 minute thing. We already have a `autodoc-process-docstring` callback in `doc/conf.py` just giving us this info for free. If the initializer have a docstring we raise hard error.
