### ISSUE TITLE
Process finished with exit code 132 (interrupted by signal 4: SIGILL)

### ISSUE THREAD

**Issue by m-hertig** [pythonarcade/arcade#1015]
I'm trying to run a python project using the arcade library on a macbook pro mid 2010 (osx 10.12.6 sierra). 
As soon as I import the arcade library to a hello world python script I'm getting the following error message:

`Process finished with exit code 132 (interrupted by signal 4: SIGILL)`

I tried with python 3.8 and 3.9, Both with the same result.

Any ideas how to resolve this are much apprechiated.

**Comment by pushfoo** [comment]
Can you please paste the entire output it prints in addition to the error code?

**Comment by pushfoo** [comment]
If you aren't able to get any output beyond what you've already posted, please specify how you installed arcade, your current arcade version, and the output when you run this script:
```py
import faulthandler
# enable limited traceback in response to SIGILL
faulthandler.enable()

import arcade

class MyGame(arcade.Window):

    def __init__(self):
        super().__init__(800, 600, "Test")

    def on_draw(self):
        arcade.start_render()

        arcade.draw_text(
            "Hello world",
            self.width / 2, self.height / 2 - 50,
             arcade.color.WHITE, 100,
             anchor_x="center",
         )

if __name__ == "__main__":
    game = MyGame()
    game.run()
```
To my knowledge, arcade itself doesn't have any binary parts, only dependencies. I suspect that one of the dependencies is either corrupt or using instructions that your older processor does not support. Knowing where the SIGILL is triggered would help us figure out what you can do to address the problem, such as either re-installing that dependency or recompiling it for your system.

**Comment by m-hertig** [comment]
@pushfoo thanks alot for your kind and detailed reply, that is awesome! 
I could update my operating system in the meantime to osx 10.13.6 high sierra which resolved the problem. 
The update was done before I could get the additional output, so I dont know what exactly caused the error. My project is now working fine.
Keep up the good work & best wishes

**Comment by einarf** [comment]
That's likely to have been a driver issue. MacOS have always been very late with OpenGL support and it's even deprecated now, but it won't be removed because so many things rely on it.
