### ISSUE TITLE
Seg fault on "glDeleteBuffers" when working with non-graphic thread

### ISSUE THREAD

**Issue by yegarti** [pythonarcade/arcade#1018]
## Bug Report
I'm working with threading in my game to separate the logic part from the graphic part but I was encountering this issue during the work.
I know that when working with threads using pyglet it's better to let the pyglet be the main thread and run the other job in a thread, which is what I'm doing.
On the side thread I don't do anything that related to arcade/pyglet.

Looking at the dump in the system log I can see it happened on: "glDeleteBuffers (libGL.so.1 + 0x48aa9)"

Thanks.

```
Manjaro 21.1.4
Python 3.9.4
arcade 2.6.3
```

### Actual behavior:
seg fault after 3-20 seconds

### Expected behavior:
no crash

### Steps to reproduce/example code:
```python3
import random
import time
import threading

import arcade
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 728
SCREEN_TITLE = 'Test'

die = False


class Task:
    def __init__(self):
        self.stuff = []

    def start(self):
        while not die:
            self.stuff = random.sample(range(10), 5)
            time.sleep(0.01)
            self.stuff = random.sample(range(10), 5)


class MyGame(arcade.Window):

    def __init__(self):
        super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
        arcade.set_background_color(arcade.color.AMAZON)
        self.sprites = arcade.SpriteList()

    def on_update(self, delta_time: float):
        self.sprites = arcade.SpriteList()
        for i in range(random.randint(0, 6)):
            sprite = arcade.SpriteSolidColor(200, 100, arcade.color.GRAY)
            sprite.position = (100 + i * 200, 100)
            self.sprites.append(sprite)

    def on_draw(self):
        arcade.start_render()
        self.sprites.draw()

def main():
    global die
    window = MyGame()
    task = Task()
    thread = threading.Thread(target=task.start)
    thread.start()
    arcade.run()
    die = True
    thread.join()



if __name__ == "__main__":
    main()
```

**Comment by einarf** [comment]
This is covered in the docs : https://api.arcade.academy/en/development/advanced/opengl_notes.html

It's currently under the development version

**Comment by yegarti** [comment]
> This is coverned in the docs : https://api.arcade.academy/en/development/advanced/opengl_notes.html
> 
> It's currently under the development version

Using `gc_mode="context_gc"` does solve the issue, thanks.
Issue closed.

**Comment by einarf** [comment]
Just don't forget to call `ctx.gc()` in main thread or things might go 💥 eventually 😄 

(I have done that once and it was not a great experience!)
