### ISSUE TITLE
When, where, and how you override on_resize could use a couple of improvements

### ISSUE THREAD

**Issue by jjinux** [pythonarcade/arcade#1024]
### What should be added/changed?

`View.on_resize()` doesn't exist. However, if you define it in a subclass, it does get called, and it's important. This should be documented and even added to `View`.

`Window.on_resize()` does exist. However, it should be documented that if you override it, you need to make sure to call the parent class's method. For a lot of `on_` methods, you don't need to call the parent class's method--this isn't one of them.

These two things together lead to some confusion.

It may make sense to do a quick pass through the examples looking for `on_resize` to make sure all the examples are doing the right thing.

### What would it help with?

See above.

## Documentation request:

See above.

### What documentation needs to change? 

See above.

### Where is it located?

See above.

### What is wrong with it? How can it be improved?

See above.

**Comment by einarf** [comment]
Looking into this. It definitely needs some cleanup/clarifications.

**Comment by einarf** [comment]
I don't see any resizable examples using views. Probably need to make one.

**Comment by einarf** [comment]
Added some improvements in : 95e327c00f9f91fd038d86fe480e9efc7a93e4e8

If this is not sufficent, please share some suggestions.

**Comment by jjinux** [comment]
Awesome! Thanks!

**Comment by einarf** [comment]
2.6.4 released
