### ISSUE TITLE
Add resources for trans or nb coders

### ISSUE THREAD

**Issue by mordy-python** [pythonarcade/arcade#1029]
## Enhancement request:

Add resources for transgender or non-binary programmers on [the diversity page](https://api.arcade.academy/en/latest/community/diversity.html)

Currently, there are only resources for female coders, but the page mentions transgender and non-binary people as well. It would mean a lot to the gender-divergent community if you could add some links to some coding groups like Girls Who Code but for trans or nb programmers as well.

**Comment by pvcraven** [comment]
Hi, good suggestion.

Graphics included with Arcade, and as part of the examples, mostly come from [Kenney.nl](https://kenney.nl/). His license is compatible with Arcade. To accomplish this task:

1. We'd need to convince him to release those assets. (He's got a discord, and is a nice guy. So entirely possible people might be able to politely ask him to do that, particularly if it was more than just me.)
2. Someone else would need to take the time and create those assets.
3. Someone would need to donate money so we could hire someone to create those assets.

**Comment by einarf** [comment]
I think this was a much simpler request about adding more links to groups/events. I guess even that is not simple considering we have users from all continents and many groups/events are fairly local.

I think suggestions could be useful here.

**Comment by mordy-python** [comment]
I meant links to groups or events, but it need not necessarily be an in-person group. I meant anything that would show gender minorities that they aren't alone

**Comment by pvcraven** [comment]
Are you aware of any you'd like to see listed? I could add in the US PyCon at least has specific meetings and outreach for trans/nb coders.

**Comment by pathunstrom** [comment]
Can I offer https://www.transgamedev.com/ as a solid resource?

It's a loose coalition of transgender game devs of all levels and python game development is very much treated well there.

**Comment by mordy-python** [comment]
> Are you aware of any you'd like to see listed? I could add in the US PyCon at least has specific meetings and outreach for trans/nb coders.

No, I didn't have anything in mind. It's partly why I created this issue :).

Thank you for your support with this. I really appreciate it!!

**Comment by pvcraven** [comment]
Closing with issue #1029 being implemented. Feel free to suggest additional resources.
