### ISSUE TITLE
Scene.add_sprite_list_xxx() methods do not work properly.

### ISSUE THREAD

**Issue by relent95** [pythonarcade/arcade#1032]
## Bug Report
Scene.add_sprite_list_before/after(), Scene.move_sprite_list_before/after() do not work properly.
Also the official platformer tutorial has some maps with incorrectly ordered layers.
(e.g., map2_level_1.json has layers Platforms, ..., Foreground, Background in the bottom to top order.)
I have tested with arcade 2.6.5 in Windows 10.

### Actual behavior:
Scene.add_sprite_list_before(name, before) inserts the 'name' sprite list before the sprite list before the 'before' sprite list.
Scene.add_sprite_list_after(name, after) inserts the 'name' sprite list before the 'after' sprite list.
Scene.move_sprite_list_before() always raises a ValueError.
Scene.move_sprite_list_after() always raises a ValueError.

### Expected behavior:
All the mentioned methods should conform the API reference.

### Steps to reproduce/example code:
At least for Scene.add_sprite_list_before(), run the official platformer tutorial step 10.

**Comment by Cleptomania** [comment]
Thanks for the report on these, the functions have been fixed in the development branch, and I've updated the layer ordering in the part 10 of the platformer tutorial there as well.
