### ISSUE TITLE
UIBoxLayout does not use align parameter

### ISSUE THREAD

**Issue by eruvanos** [pythonarcade/arcade#1035]
UIBoxLayout places children always centralised on screen, the parameter `align` is ignored.

**Comment by indeed999** [comment]
The same issue, I wasted many hours considering that is my fault

**Comment by eruvanos** [comment]
Will be covered in next release.
https://github.com/pythonarcade/arcade/commit/07211c4e72cad972f9c4e9704e86231099ecb0ff

**Comment by eruvanos** [comment]
Released
