### ISSUE TITLE
Idea: swap _init_deferred and length check in lazy SpriteList

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#1039]
### What should be added/changed?

Not sure if I understand this correctly, but the idea is to not call init_deferred (and set up OpenGL etc) if the length of the spritelist is zero or it is not visible. There is a check for length 0 or not visible which causes draw() to just return, but it is placed after init_deferred. I am suggesting moving init_deferred to after the length/visible check. My understanding is that this would only affect SpriteLists with lazy=True.

### What would it help with?

I use many spritelists in my game, for enemies, items, moving platforms, ladders, etc, but not all of them are used in every level. For example, in most levels, there are no ladders, so the ladder spritelist is empty. If this change was made, I could set spritelists that are not used in every level - e.g. ladders - to lazy=True, then they would not do init_deferred. My guess is that this would improve performance by not doing init_deferred (it looks like it is doing stuff with memory and openGL). I do not myself know enough about the inner workings of all of this to be able to evaluate if this is worthwhile or not.

**Comment by einarf** [comment]
Definitely something we should do. I don't think this will cause any problems.

**Comment by einarf** [comment]
Fixed. We'll the the initialization after. That way we don't end up creating unnecesary opengl resources if the spritelist stays empty and is just thrown away later. `lazy=True` or creation before context is needed.

**Comment by einarf** [comment]
2.6.6 is out
