### ISSUE TITLE
Add antialiasing to frame buffers

### ISSUE THREAD

**Issue by user2332533** [pythonarcade/arcade#1040]
## Enhancement request:
Add anti-aliasing to frame buffers

Drawing to frame buffers does not provide the same anti-aliasing as drawing to the window

![screenshot1](https://user-images.githubusercontent.com/95532390/144713694-ed066fa6-85e9-4796-943c-06da186ae462.png)
(The ascending line is drawn to the frame buffer while the descending line is drawn to the window)

### What should be added/changed?
A way to apply the same gl effects to the frame buffers as to the window

### What would it help with?
Making frame buffers a suitable target for shape drawing. 

For example: Drawing 100,000 static shapes to the screen every cycle is expensive compared to drawing them to a frame buffer once and rendering the framebuffer to the screen each cycle

### Code to reproduce
Using shadertoy:
```python
import arcade

class MyGame(arcade.Window):
    def __init__(self, width, height, title):
        super().__init__(width, height, title, samples=16)
        arcade.set_background_color((255, 255, 255))  
        self.clear() 
        # Set up shadertoy to use as framebuffer renderer
        pt = '''
        void mainImage(out vec4 fragColor, in vec2 fragCoord) {
            fragColor = texture(iChannel0, fragCoord.xy / iResolution.xy);
        }
        '''
        self.shadertoy = arcade.experimental.Shadertoy([width, height], pt)
        self.shadertoy.channel_0 = self.ctx.texture([width, height], components=4)
        self.fbo = self.shadertoy.ctx.framebuffer(color_attachments=[self.shadertoy.channel_0])
        # Draw a line to framebuffer
        self.fbo.use()
        arcade.draw_line(0, 0, self.width, self.height, (0, 0, 0))
        # Draw the framebuffer and a line to the window
        self.use()     
        self.shadertoy.render()
        arcade.draw_line(self.width, 0, 0, self.height, (0, 0, 0))

window = MyGame(200, 150, 'Test')
arcade.run()
```
Using program:
```python
import arcade

class MyGame(arcade.Window):

    def __init__(self, width, height, title):
        super().__init__(width, height, title, samples=16)
        arcade.set_background_color(arcade.color.WHITE)
        self.clear()
        # Set up a frame buffer
        self.texture = self.ctx.texture([width, height], components=4)
        self.fb = self.ctx.framebuffer(color_attachments=[self.texture])
        self.quad_fs = arcade.gl.geometry.quad_2d_fs()
        self.program = self.ctx.program(
            vertex_shader="""
            #version 330
            in vec2 in_vert;
            in vec2 in_uv;
            out vec2 uv;
            void main() {
                gl_Position = vec4(in_vert, 0.0, 1.0);
                uv = in_uv;
            }
            """,
            fragment_shader="""
            #version 330
            uniform sampler2D texture0;
            in vec2 uv;
            out vec4 fragColor;
            void main() { 
                fragColor = texture(texture0, uv); 
            }
            """,
        )
        # Draw a line to the frame buffer
        self.fb.use()
        arcade.draw_line(0, 0, self.width, self.height, (0, 0, 0))
        # Draw the framebuffer and a line to the window
        self.use()
        self.texture.use()
        self.quad_fs.render(self.program)
        arcade.draw_line(self.width, 0, 0, self.height, (0, 0, 0))        

MyGame(200, 150, 'test')
arcade.run()
```
Tested on current development branch 2021-12-04 (last commit c89197471b8)

**Comment by einarf** [comment]
This is definitely nice to have. Framebuffers with samples do add some challenges though. To actually display a multisampled buffer you either have to :

A) Copy the framebuffer to another one (without samples) hoping the driver have support for this 
B) Make a shader that reads a `sampler2DMS` sampler when drawing to the screen

**Comment by user2332533** [comment]
Thanks, is this not simple because the window frame buffer is actually handled by pyglet rather than arcade?

As a work around, is there a way to copy screen contents to a fb? 

I'm thinking of something like:
- Clear window with transparent background
- Draw shapes to window
- Copy window  contents to fb
- In on_draw draw fb to window

**Comment by einarf** [comment]
I my experience the safest way is to avoid the default framebuffer entirely because the exact pixel format may vary a little bit and blitting framebuffers is very sensitive to format differences. It might be ok, but we can see what works.

I suggest doing the following initially:
1) Add support multisamples textures (`ctx.texture((w, h), samples=4)`
2) Create a shader that renders a multisampled texture to the screen. This shader whould just iterate all the samples per fragment and write out the resolved value.

This should be relatively quick to add.

That begin said .. we can also add `ctx.copy_framebuffer` for people who want to experiment

**Comment by einarf** [comment]
I did some tweaks in Texture, Context and Framebuffer and got this working : https://github.com/pythonarcade/arcade/blob/development/arcade/experimental/examples/multisample_fbo.py

That's a start at least. Give it a try with latest development branch. This could be integrated into the Shadertoy, but we do need separate shaders with `sampler2DMS` samplers.

**Comment by einarf** [comment]
Forgot to link up the commit : ac2c00a4e2666063be1ca7b3e5cab885491c8261

**Comment by einarf** [comment]
I have tested this on Nvidia, AMD Vega, Intel HD4000 and AMD module GPU. Seems to work ok.

Using copy framebuffer is not a problem as long as the source and target is the same size and format. Only the source can be multisampled.

**Comment by einarf** [comment]
Just need a shader example for rendering an MSAA texture now.

The channels in shadertoy can't really be multisampled. That breaks shadertoy badly.

**Comment by einarf** [comment]
Actually. Let's stay with `copy_framebuffer`. It does work as long as we follow the restrictions. Dealing with `sampler2DMS` is just too painful as we don't know the coverage etc.

Marking this as done for now since it will go in the next release.

**Comment by einarf** [comment]
2.6.6 is out

**Comment by user2332533** [comment]
A million thanks @einarf this is fantastic. 
I'm going to have to learn a lot more about gl to understand how this works, your commit is deceptively simple looking.

I had to add `samples=8` to the Window init call to get your example running but then it worked perfectly.

Here are a couple of naive benchmark examples to demonstrate why I was going down this path to begin with. The `ShapeElementList` version hits 1 FPS and causes a memory error if I up the count while the `copy_framebuffer` version is smooth at 60 FPS.

### Many static lines with copy_framebuffer
```python
import math
import arcade
from random import randint
import time
import collections

class FPSCounter:
    def __init__(self):
        self.time = time.perf_counter()
        self.frame_times = collections.deque(maxlen=60)

    def tick(self):
        t1 = time.perf_counter()
        dt = t1 - self.time
        self.time = t1
        self.frame_times.append(dt)

    def get_fps(self):
        total_time = sum(self.frame_times)
        if total_time == 0:
            return 0
        else:
            return len(self.frame_times) / total_time

class MultisampleFramebuffer(arcade.Window):

    def __init__(self, width, height):
        super().__init__(width, height, "Stress test lines FB", samples=8)
        self.time = 0
        self.fps = FPSCounter()

        # Create a MSAA texture and framebuffer
        self.texture = self.ctx.texture(self.get_framebuffer_size(), samples=8)
        self.fbo = self.ctx.framebuffer(color_attachments=[self.texture])
        
        # Draw a lot of lines to the buffer
        self.fbo.use()
        self.fbo.clear()
        for i in range(50000):
            arcade.draw_line(
                randint(0, self.width), 
                randint(0, self.height), 
                randint(0, self.width), 
                randint(0, self.height), 
                (randint(0, 255), randint(0, 255), randint(0, 255))
            )
        self.use()

    def on_draw(self):
        self.clear()
        # Copy the frame buffer to the screen
        self.ctx.copy_framebuffer(self.fbo, self.ctx.screen)
        # Add an animation
        arcade.draw_circle_outline(
            self.width / 2,
            self.height / 2,
            200 + math.sin(self.time) * 50,
            (0, 0, 0),
        )
        # Draw FPS counter
        fps = self.fps.get_fps()
        output = f"FPS: {fps:3.0f}"
        arcade.draw_text(output, 20, self.height - 80, arcade.color.BLACK, 16)
        self.fps.tick()

    def on_update(self, delta_time: float):
        self.time += delta_time


MultisampleFramebuffer(800, 600).run()
```
 ### Many static lines with ShapeElementList
```python
import math
import arcade
from random import randint
import time
import collections

class FPSCounter:
    def __init__(self):
        self.time = time.perf_counter()
        self.frame_times = collections.deque(maxlen=60)

    def tick(self):
        t1 = time.perf_counter()
        dt = t1 - self.time
        self.time = t1
        self.frame_times.append(dt)

    def get_fps(self):
        total_time = sum(self.frame_times)
        if total_time == 0:
            return 0
        else:
            return len(self.frame_times) / total_time

class MultisampleFramebuffer(arcade.Window):

    def __init__(self, width, height):
        super().__init__(width, height, "Stress test lines SEL", samples=8)
        self.time = 0
        self.fps = FPSCounter()

        self.lines = arcade.ShapeElementList()
        for i in range(50000):
            self.lines.append(
                arcade.create_line(
                    randint(0, self.width), 
                    randint(0, self.height), 
                    randint(0, self.width), 
                    randint(0, self.height), 
                    (randint(0, 255), randint(0, 255), randint(0, 255))
                )
            )

    def on_draw(self):
        self.clear()
        # Draw the lines in the SEL
        self.lines.draw()
        # Add an animation
        arcade.draw_circle_outline(
            self.width / 2,
            self.height / 2,
            200 + math.sin(self.time) * 50,
            (0, 0, 0),
        )
        # Draw FPS counter
        fps = self.fps.get_fps()
        output = f"FPS: {fps:3.0f}"
        arcade.draw_text(output, 20, self.height - 80, arcade.color.BLACK, 16)
        self.fps.tick()

    def on_update(self, delta_time: float):
        self.time += delta_time


MultisampleFramebuffer(800, 600).run()
```
