### ISSUE TITLE
Camera: default arguments cause crash

### ISSUE THREAD

**Issue by CommentatorForAll** [pythonarcade/arcade#1041]
## Bug Report
When initializing a camera using its default arguments (by not supplying any), it crashes the Program with an ZeroDivisionError

### Expected behavior:
Either having a camera with an dynamic viewport (always at the size of the window) or at least not crash

### Steps to reproduce/example code:
call arcade.Camera()

**Comment by Cleptomania** [comment]
Thanks for the suggestion, the Camera already stores a reference to the window so this is an easy implementation.

This has been implemented in the development and should be in the 2.6.7 release.

The behavior is such that if the viewport width or height is not explicitly set, it will pull the value from the window
