### ISSUE TITLE
Question on Wayland

### ISSUE THREAD

**Issue by mu-us61** [pythonarcade/arcade#1042]
hello  my question is about Wayland support , I was gonna start arcade tutorial but the first sentence is not gonna work on wayland and this is sad because wayland is the future ,  it will never ever gonna be work on wayland or after some time will  wayland gonna be supported ?

this is from offical web page the first sentence is really intimidating maybe it should be written as Wayland currently not supported if it is like that. https://api.arcade.academy/en/latest/get_started.html#get-started-here

![image](https://user-images.githubusercontent.com/73366454/145584084-82325f4a-1c65-47a7-b244-42ecbef48a86.png)

and lastly as a suggestion naming is somewhat feels off , arcadepy or pyarcade would be nicer rather than barebone "arcade"

**Comment by Cleptomania** [comment]
I’m theory it would probably work using XWayland, however I haven’t tried it. If you don’t have XWayland here’s an Arch Wiki page about it: https://wiki.archlinux.org/title/wayland#XWayland

I’d love to hear some feedback about if that works or not. It would take a lot of setup for me to test with Wayland as I am not ready to actually switch to it.

Arcade getting native wayland support will rely on Pyglet getting it. There hasn’t been much request for it that I’m aware of so I don’t think anyone has considered it very high priority. 

I know it’s definitely on the roadmap, but I’m unsure what an expected timeline would be to give other than “sometime in the future”. In theory once Pyglet supports it, nothing really needs done Arcade side to implement unless that happens to change Pyglet’s window API.

**Comment by einarf** [comment]
It should work on XWayland currently. I know Wayland support is on the TODO list.

When it comes to the package name that's just a matter of taste. Changing it now after 5 years is more trouble than it's worth. There are python packages with and without the py pre/postfix. I do agree that for example pyarcade *could* work and *might* be a slighly better name from a marketing perspective. But again, changing it is such a painful transition. Probably just smarter to promote the name "Python Arcade" in docs and tutorials (That's already the organization name).
