### ISSUE TITLE
GUI Style lacking in documentation

### ISSUE THREAD

**Issue by NovaAndrom3da** [pythonarcade/arcade#1047]
Add more comprehensive documentation to the [GUI Style page](https://api.arcade.academy/en/2.6.6/gui/style.html). Right now it is confusing and does not have adequate information in order to change styles of GUI widgets, such as UIFlatButton. Better documentation could include examples of how to (i.e.) change the background color of a widget when hovered.

Also, I would like to ask. Are there any improvements in using the pseudo-`dict` class for Widget styling, instead of a real `dict`?

**Comment by eruvanos** [comment]
We have some changes ready for a bigger release, which will improve the style handling for the UIFlatButton (like it is now for UISlider).

It looks like the documentation for the UIFlatButton already made it on the main page, while the change is not available in a release.

https://github.com/pythonarcade/arcade/commit/6867558634088f59fb95a1efd46e2cca9561eddb

**Comment by Ibrahim2750mi** [comment]
Completed in #1607
