### ISSUE TITLE
UNICODE ERROR

### ISSUE THREAD

**Issue by HoiDam** [pythonarcade/arcade#1054]
### Actual behavior:
```
    UnicodeDecodeError                        Traceback (most recent call last)
    _ctypes/callbacks.c in 'calling callback function'()
    
    ~\AppData\Roaming\Python\Python38\site-packages\pyglet\font\win32query.py in _enum_font_names(logfont, textmetricex, fonttype, param)
        341 
        342     lf = logfont.contents
    --> 343     name = lf.lfFaceName.decode('utf-8')
        344 
        345     # detect font type (vector|raster) and format (ttf)
    
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 0: invalid start byte
```
### Expected behavior:
No ERROR
### Steps to reproduce/example code:
`
    arcade.draw_text("HOST",
                        x + CIRCLE_SIZE + TEXT_TOOLTIP_ADD, 
                        y + CIRCLE_SIZE + TEXT_TOOLTIP_ADD,
                        arcade.color.RED,
                        DEFAULT_FONT_SIZE * 1.5,
                        width=SCREEN_WIDTH)
`

**Comment by pvcraven** [comment]
I believe this has to do with a name on one of your system fonts. It isn't getting properly decoded by the UTF-8.

**Comment by pvcraven** [comment]
Opened issue with pyglet: https://github.com/pyglet/pyglet/issues/524
