### ISSUE TITLE
Window not consistently given focus upon startup

### ISSUE THREAD

**Issue by slipstreampilot** [pythonarcade/arcade#1055]
## Bug Report

Hello - I'm a relative newbie to arcade but grateful for all the work you've done here. 

On Mac, using the arcade.Window class, the window does not always begin in or stay in focus. i.e. the title of the window is greyed out and the three little dots in the top left are greyed out instead of in color (red yellow green). Weirdly, this issue shows up randomly without clear cause when running the exact same code multiple times. (open program, close program, repeat). Sometimes the code works perfectly with no focus issue for the full run of the program. Sometimes the window cannot be brought into focus even if you click on the window. Very strange. I have verified that this occurs even in the basic window tutorial code copied below. In my case, however, I was trying to create a sort of button and this resulted in the button requiring double-click instead of single click.

I'm running python 3.9 and arcade 2.6.7 on a mac with intel. Big Sur

### Steps to reproduce/example code:

"""
Platformer Game
"""
import arcade

# Constants
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "Platformer"

class MyGame(arcade.Window):
    """
    Main application class.
    """

    def __init__(self):

        # Call the parent class and set up the window
        super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)

        arcade.set_background_color(arcade.csscolor.CORNFLOWER_BLUE)

    def setup(self):
        """Set up the game here. Call this function to restart the game."""
        pass

    def on_draw(self):
        """Render the screen."""

        arcade.start_render()
        # Code to draw the screen goes here

def main():
    """Main function"""
    window = MyGame()
    window.setup()
    arcade.run()

if __name__ == "__main__":
    main()

**Comment by slipstreampilot** [comment]
I just upgraded to arcade 2.6.8 and verified that it also has the issue

**Comment by einarf** [comment]
I've seen this on my mac as well. This is an issue in pyglet. I wonder if there's some quick fix for this.

**Comment by einarf** [comment]
@slipstreampilot What happens if you add this at the end of the window initializer?

```py
self.activate()
```

This should ideally trigger a window focus event.

**Comment by slipstreampilot** [comment]
Thanks. I'm not 100% sure where you are referring to when you say "at the end of the window initializer, but I tried calling self.activate() during __init__ and also at the end of the program with 
window = MyWindow()
window.activate()
neither worked unfortunately

**Comment by einarf** [comment]
https://github.com/pyglet/pyglet/issues/225

**Comment by einarf** [comment]
The bug is in the pyglet project, so closing this one for now since there is nothing we can do  about it here.
