### ISSUE TITLE
UIInputText() not working

### ISSUE THREAD

**Issue by BrettskiPy** [pythonarcade/arcade#1059]
## Bug Report
The UIInputText() is not visible even after it is created.

### Expected behavior:
Entry box appears upon using the arcade.gui.UIInputText()

### Steps to reproduce/example code:
Observe simplified code attached. 
[entry_box_not_working.txt](https://github.com/pythonarcade/arcade/files/7805430/entry_box_not_working.txt)

**Comment by eruvanos** [comment]
The issue is caused by the underlying pyglet lib: https://github.com/pyglet/pyglet/issues/529

Please try this workaround:
```
entry_area = arcade.gui.UIInputText(text=" ")
entry_area.text = ""
```

This should do the trick.

PS. I also recommend to add some border to make the input field more visible (even in the example code):

```
self.manager.add(
            arcade.gui.UIAnchorWidget(
                anchor_x="center_x",
                anchor_y="center_y",
                child=self.v_box).with_border()
        )
```

**Comment by BrettskiPy** [comment]
Awesome, thanks for the information. I’ll try this out soon.

**Comment by einarf** [comment]
There are still things we need to do here, so re-opening

**Comment by einarf** [comment]
Should be solved now. 2.0.6 will have more fixes as well

**Comment by alejomongua** [comment]
It still happens in 2.6.17
