### ISSUE TITLE
Documentation sometimes uses Arcade’s old URL

### ISSUE THREAD

**Issue by Jayman2000** [pythonarcade/arcade#1062]
### What documentation needs to change?

Anything with links that contain <https://github.com/pvcraven/arcade/>

### Where is it located?

```
$ git grep -l 'pvcraven/arcade'
CONTRIBUTING.md
README.rst
doc/development/enhancement_list.rst
doc/development/how_to_contribute.rst
doc/development/how_to_submit_changes.rst
doc/development/release_notes.rst
doc/index.rst
doc/install/source.rst
```

### What is wrong with it? How can it be improved?

Originally, Arcade’s repo was located at <https://github.com/pvcraven/arcade/>. Now, <https://github.com/pvcraven/arcade/> redirects to <https://github.com/pythonarcade/arcade/>. The links in the documentation should be updated for Arcade’s current location.

**Comment by tomc** [comment]
sed 's/pvcraven\/arcade/pythonarcade\/arcade' 
?

**Comment by Jayman2000** [comment]
> sed 's/pvcraven/arcade/pythonarcade/arcade'
> ?

Close, but you have to escape the slashes. Here’s what I used:
```bash
to_find='pvcraven\/arcade'
git grep -lz "$to_find" | xargs -0 -- sed -i "s/$to_find/pythonarcade\/arcade/"
```

**Comment by tomc** [comment]
Actually I had escaped the slashes but it must have gotten gobbled by the
forum sanitizer.  :)

At any rate, minor syntax quibbles aside my point was this seemed like a
simple fix.

**Comment by pvcraven** [comment]
Nice catch. I'll get it done unless someone is already working a PR.

**Comment by Jayman2000** [comment]
> Nice catch. I'll get it done unless someone is already working a PR.

See #1063.
