### ISSUE TITLE
Shapely never used for has_line_of_sight, even if installed

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#1066]
### Actual behavior:

The function has_line_of_sight in paths_shapely.py is not used, even if shapely is installed.

### Expected behavior:

If shapely is installed, the functions in paths_shapely.py should be used, otherwise those in paths_python.py

### Steps to reproduce/example code:

Have shapely installed, use has_line_of_sight. You can put a break point or print statement in the functions to see which one gets called.

I found this by putting print statements to check if shapely is installed, and in has_line_of_sight. I think the problem is this part in paths.py:
```
if 'shapely' in sys.modules:
    from .paths_python import has_line_of_sight  # noqa: F401
else:
    from .paths_python import has_line_of_sight  # noqa: F401
```
The code is the same in both branches. Clearly, the intended behavior is as in geometry.py, where it actually selects the shapely functions.

**Comment by bunny-therapist** [comment]
arcade==2.6.8

I see the same code in current development branch: https://github.com/pythonarcade/arcade/blob/development/arcade/paths.py

**Comment by einarf** [comment]
Fixed. That was just a simply typo in the imports.

**Comment by einarf** [comment]
2.6.10 released
