### ISSUE TITLE
Wrong size of custom square hitbox loaded from Tiled json tilemap

### ISSUE THREAD

**Issue by nrukin** [pythonarcade/arcade#1068]
### Actual behavior:

Created tileset in Tiled with custom hitboxes on tiles, and map with that tileset
When loading map in arcade, size of rectangular hitbox wrong

Hitboxes in Tiled Editor
![Снимок экрана 2022-01-26 105936](https://user-images.githubusercontent.com/35288125/151126123-f76c6e2d-7d55-49e1-af60-f88064ea4336.png)

Hitboxes in arcade
![Снимок экрана 2022-01-26 105922](https://user-images.githubusercontent.com/35288125/151126201-f9047ddc-4069-48c5-99d3-42fe245cbb9a.png)

### Expected behavior:
Size of rectangular hitbox in arcade the same as in Tiled

### Steps to reproduce/example code:
Example code and tileset in attached file:
[example.zip](https://github.com/pythonarcade/arcade/files/7939945/example.zip)

**Comment by einarf** [comment]
Nice find 👍

**Comment by Cleptomania** [comment]
This was fixed with #1069 so should be in the next release. Thanks for PR on it.

**Comment by einarf** [comment]
2.6.10 released
