### ISSUE TITLE
Texture class missing texture_id? and Sprite class not checking for texture presence

### ISSUE THREAD

**Issue by alejcas** [pythonarcade/arcade#1079]
## Bug Report
I see that `Sprite` class defines a [method (__lt__)](https://github.com/janscas/arcade/blob/development/arcade/sprite.py#L506) that uses inside `self._texture_texture_id`, but I see that `Texture` class doesn't have texture_id defined.

Maybe I'm missing something... or it's a bug.

Anyway, as Sprite._texture is optional, the method signature should be changed to protect against that:

```python
# before:
def __lt__(self, other):
    return self._texture.texture_id.value < other.texture.texture_id.value

# after:
def __lt__(self, other):
    if self._texture is not None:
        return self._texture.texture_id.value < other.texture.texture_id.value
    else:
        # TODO: default to??
        pass
```

**Comment by einarf** [comment]
I cannot find anything in the code base setting `texture_id` on a sprite. I think this is legacy stuff that can be removed.

**Comment by einarf** [comment]
I just removed it. There's nothing anywhere in arcade even referencing this properly.
