### ISSUE TITLE
Enable legacy behavior in collision check

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#1083]
## Enhancement request:

(This is probably more of a bug report, if I understand your intentions correctly, but based on the code itself, legacy behavior is removed so I will call it "enhancement request", change it if you want.)

### What should be added/changed?

The functions check_for_collision_with_list and check_for_collision_with_lists should have the following behavior possible (preferably by default): spatial hashing used if available, otherwise CPU based (I suppose you could arguable throw in GPU based for 1500+ sprites if you want in the default, but legacy should at least be possible).

The current behavior does NOT allow for this behavior if I am reading the code correctly. For example, see check_for_collision_with_list:
```
    if sprite_list.spatial_hash and method == 1:
        # Spatial
        sprite_list_to_check = sprite_list.spatial_hash.get_objects_for_box(sprite)
        # checks_saved = len(sprite_list) - len(sprite_list_to_check)
    elif method == 3 or (method == 0 and len(sprite_list) <= 1500):
        sprite_list_to_check = sprite_list  # type: ignore
    else:
        # GPU transform
        sprite_list_to_check = _get_nearby_sprites(sprite, sprite_list)  # type: ignore
```
So for method=0 it is CPU-based (mid branch) or GPU transform (bottom branch).
For method=1 it is using spatial hash (top branch) or GPU transform (bottom branch)
For method=2 it is GPU transform.
For method=3 it is CPU-based.

In check_for_collision_with_lists (plural), we have
```
        if sprite_list.spatial_hash and method == 1:
            # Spatial
            sprite_list_to_check = sprite_list.spatial_hash.get_objects_for_box(sprite)
            # checks_saved = len(sprite_list) - len(sprite_list_to_check)
        elif method == 3:
            sprite_list_to_check = sprite_list  # type: ignore
        else:
            # GPU transform
            sprite_list_to_check = _get_nearby_sprites(sprite, sprite_list)  # type: ignore
```
This is exactly the same, except for the middle branch which is lacking the method==0 check, which just means that for method=0, it will always be GPU transform (else branch).

### What would it help with?

When I updated to 2.6.10, my game became unplayable because the performance of collision checks took a nose dive. There is no reason to remove legacy behavior and force GPU transform (I suspect this may not have been the intention).

**Comment by einarf** [comment]
I think the right way to go here is:
* Restore default  behavior
* Make collision algo selectable in each spritelist
* Move selection code into spritelist
* Make property in spritelist for setting algo

**Comment by bunny-therapist** [comment]
This is still open. It means that spatial hashing actually does not work in arcade (unless you do a workaround and pass in method=1 when you are using spatial hashing).

**Comment by einarf** [comment]
2.6.12 released
