### ISSUE TITLE
GPU Collision broken on 2013 macbooks

### ISSUE THREAD

**Issue by morrissimo** [pythonarcade/arcade#1089]
## Bug Report

In the "simple platformer" [tutorial](https://api.arcade.academy/en/latest/examples/platform_tutorial/index.html), several source code modules are missing statements required for the code to run correctly.

The affected modules (at least that I've discovered so far - I'm still going through the tutorial!):

* Step 4 - Add User Control
* Step 5 - Add Gravity
* Step 7 - Add Coins and Sound
* Step 8 - Display the Score

In all cases, the issue was the same: one or more statements to create sprite lists were missing from the `setup()` method.

### Actual behavior:

Using the source code provided for Step 4 - Add User Control as an example:

1. save the source code locally
2. execute the source code: `$ python 04_user_control.py`
3. get a stack trace:
```
Traceback (most recent call last):
  File "/base/path/to/sandbox/arcade/examples/platform_tutorial/04_user_control.py", line 128, in <module>
    main()
  File "/base/path/to/sandbox/arcade/examples/platform_tutorial/04_user_control.py", line 124, in main
    arcade.run()
  File "/base/path/to/sandbox/arcade/window_commands.py", line 242, in run
    pyglet.app.run()
  File "/base/path/to/python/venv/arcade/lib/python3.10/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run(interval)
  File "/base/path/to/python/venv/arcade/lib/python3.10/site-packages/pyglet/app/base.py", line 184, in run
    timeout = self.idle()
  File "/base/path/to/python/venv/arcade/lib/python3.10/site-packages/pyglet/app/base.py", line 245, in idle
    self.clock.call_scheduled_functions(dt)
  File "/base/path/to/python/venv/arcade/lib/python3.10/site-packages/pyglet/clock.py", line 275, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/base/path/to/sandbox/arcade/application.py", line 295, in _dispatch_updates
    self.dispatch_event('on_update', delta_time)
  File "/base/path/to/python/venv/arcade/lib/python3.10/site-packages/pyglet/window/__init__.py", line 1327, in dispatch_event
    super().dispatch_event(*args)
  File "/base/path/to/python/venv/arcade/lib/python3.10/site-packages/pyglet/event.py", line 422, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/base/path/to/sandbox/arcade/examples/platform_tutorial/04_user_control.py", line 117, in on_update
    self.physics_engine.update()
  File "/base/path/to/sandbox/arcade/physics_engines.py", line 243, in update
    return _move_sprite(self.player_sprite, self.walls, ramp_up=False)
  File "/base/path/to/sandbox/arcade/physics_engines.py", line 49, in _move_sprite
    if len(check_for_collision_with_lists(moving_sprite, walls)) > 0:
  File "/base/path/to/sandbox/arcade/sprite_list/spatial_hash.py", line 378, in check_for_collision_with_lists
    sprite_list_to_check = _get_nearby_sprites(sprite, sprite_list)  # type: ignore
  File "/base/path/to/sandbox/arcade/sprite_list/spatial_hash.py", line 293, in _get_nearby_sprites
    return [
  File "/base/path/to/sandbox/arcade/sprite_list/spatial_hash.py", line 294, in <listcomp>
    sprite_list[i]
  File "/base/path/to/sandbox/arcade/sprite_list/sprite_list.py", line 260, in __getitem__
    return self.sprite_list[i]
IndexError: list index out of range
```

### Expected behavior:
1. save the source code locally
2. execute the source code: `$ python 04_user_control.py`
3. observe the platformer tutorial game window appear

### What documentation needs to change? 
The referenced source code modules for the tutorial should be updated to include the missing lines, so that the source code provided will in run as intended.

### Where is it located?
As noted, I have only observed this issue with 4 tutorial source code modules so far:
```
arcade/examples/platform_tutorial/04_user_control.py
arcade/examples/platform_tutorial/05_add_gravity.py
arcade/examples/platform_tutorial/07_coins_and_sound.py
arcade/examples/platform_tutorial/08_score.py
```

### What is wrong with it? How can it be improved?
The missing calls to `add_sprite_list()` need to be added! 

With at least these four tutorial modules, adding calls to initialize the sprite list(s) expected by the rest of the module resolves the crash. Again, using the source code provided for Step 4 - Add User Control as an example, the following change resolves the crash:
```diff
--- a/arcade/examples/platform_tutorial/04_user_control.py
+++ b/arcade/examples/platform_tutorial/04_user_control.py
@@ -42,6 +42,8 @@ def setup(self):
 
         # Initialize Scene
         self.scene = arcade.Scene()
+        self.scene.add_sprite_list("Player")
+        self.scene.add_sprite_list("Walls", use_spatial_hash=True)
 
         # Set up the player, specifically placing it at these coordinates.
         image_source = ":resources:images/animated_characters/female_adventurer/femaleAdventurer_idle.png"
```

**Comment by pvcraven** [comment]
You shouldn't be getting an error at all even without the changes. What version Arcade? Do you have Shapely installed? What version Python? What OS?

I think there's another error floating around here I'd like to be able to duplicate the error you are getting.

**Comment by morrissimo** [comment]
Mac Big Sur 11.6.3
Python 3.10.2

Installed dependencies:
```
$ pip freeze --local
arcade==2.6.10
attrs==21.4.0
black==22.1.0
cffi==1.15.0
click==8.0.3
flake8==4.0.1
isort==5.10.1
mccabe==0.6.1
mypy-extensions==0.4.3
pathspec==0.9.0
Pillow==9.0.1
platformdirs==2.5.0
pycodestyle==2.8.0
pycparser==2.21
pyflakes==2.4.0
pyglet==2.0.dev13
pymunk==6.2.1
pytiled-parser==2.0.1
tomli==2.0.1
typing_extensions==4.0.1
```

**Comment by Cleptomania** [comment]
An early version of `arcade.Scene` did not create the SpriteList if it didn’t already exist, however I think that was only in 2.6.0 pre-release versions. Now when adding a Sprite, if the requested SpriteList doesn’t exist it should be automatically created.

My guess is this is also somehow related to missing shapely

**Comment by morrissimo** [comment]
Finally got some time to revisit this

> shapely

Had to dig around a bit to fill in some of the [context](https://api.arcade.academy/en/latest/development/release_notes.html#id7) I was missing. Installed shapely:
```
$ pip freeze --local | grep -i shapely
Shapely==1.8.1.post1
```
...but of course that didn't fix the original issue I was seeing - instead it just blew up with something shapely-specific:
```
OSError: Could not find lib geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib', '/opt/homebrew/lib/libgeos_c.dylib'].
```
Not a surprise, given the release notes on the upstream issues the shapely project is working on. So I uninstalled shapely :)

Went back to troubleshooting on the first tutorial module where I saw this behavior, `04_user_control.py`, and was able to narrow things down a bit more:
1. the "Walls" sprite list not being pre-declared is enough to cause the originally reported issue
2. the `add_sprite()` code _is_ creating a new sprite list if one isn't found, but (as noted in `add_sprite()`'s docstring) it doesn't set any additional options - so the auto-added "Walls" sprite list isn't created with `use_spatial_hash=True`
3. the simple physics engine `_move_sprite()` method calls `sprite_list.spatial_hash.check_for_collision_with_lists()` (several times), passing the player sprite and the "Walls" sprite list; if the "Walls" sprite list was auto-added and doesn't use spatial hashing, then `check_for_collision_with_lists()`'s methodology logic uses the GPU-based `sprite_list.spatial_hash._get_nearby_sprites()` method to whittle down the sprites needing to be checked for collision with the player sprite

...and `_get_nearby_sprites()` is where things go sideways for me. So, I exploded the listcomp in the return statement into a loop and added some `print()`s:
```python
# arcade/sprite_list/spatial_hash.py#L290
    """
    # .. otherwise build and return a list of the sprites selected by the transform
    return [
        sprite_list[i]
        for i in struct.unpack(f'{emit_count}i', buffer.read(size=emit_count * 4))
    ]
    """
    print(f"[_get_nearby_sprites] sprite_count: {sprite_count}")
    print(f"[_get_nearby_sprites] emit count: {emit_count}")
    retlist = []
    for idx, i in enumerate(struct.unpack(f"{emit_count}i", buffer.read(size=emit_count * 4))):
        print(f"[_get_nearby_sprites] {idx}: {i}")
        retlist.append(sprite_list[i])
    return retlist
```
...and now I get this output right before the exception:
```bash
[_get_nearby_sprites] sprite_count: 23
[_get_nearby_sprites] emit count: 23
[_get_nearby_sprites] 0: 0
[_get_nearby_sprites] 1: 1
[_get_nearby_sprites] 2: 2
[_get_nearby_sprites] 3: 3
[_get_nearby_sprites] 4: 1065353216
```
`IndexError: list index out of range` indeed :/

Other things I tried:
* changed the default value for the `method=` kwarg on `check_for_collision_with_lists()` from a 1 to a 3 - this had the effect of not falling back to the GPU collision detection method even when the sprite list being checked didn't have spatial hashing enabled. This resolved the error
* added "ensure walls use spatial hashing" code in the simple physics engine `__init__`, to loop over any SpriteLists passed in as the walls and call each list's `enable_spatial_hashing()` method. Unsurprisingly, this resolved the error

As I'm seeing this error when the GPU-based collision detection is used, my ancient Macbook Air's specs seem like they might be relevant - from my "About this Mac" dialog:
```
MacBook Air (13-inch, Mid 2013)
Processor 1.3 GHz Dual-Core Intel Core i5
Memory 4 GB 1600 MHz DDR3
Graphics Intel HD Graphics 5000 1536 MB
```

Anyway - that's a lot of fumbling to read through, but hopefully it helps narrow down the cause of the issue 🤷

**Comment by einarf** [comment]
I found the issue. Working on fix. It affects the reeaaly old macbooks.

**Comment by einarf** [comment]
Fixed and pushed to development branch. The problem was that the old mac driver don't like return  statements in the geometry shader. If we just protect the emitting with an `if` block it works as intended.

Apparently the mac drivers are emulating transforms on the CPU. This is more than fast enough for our use case.

**Comment by einarf** [comment]
2.6.12 released
