### ISSUE TITLE
Feature request: New method in the Sprite class to rotate it to face a given Point

### ISSUE THREAD

**Issue by sallywag** [pythonarcade/arcade#1091]
### **Enhancement request:**

A new method in the Sprite class to rotate it to face a given Point (or another Sprite). Perhaps give the option for it to instantly face a given Point or gradually turn towards it. Perhaps allow a Sprite as the parameter as well as a Point, so you can do something like `player.look_at(enemy)`.

### **What should be added/changed?**

A new method in the Sprite class. For example:

`    def look_at(self, point: Point) -> None:
        self.angle = math.degrees(
            math.atan2(point.x - self.center_y, point.y - self.center_x)
        )`

### **What would it help with?**

Simplify rotating one sprite to face another. This seems like something that is commonly done in 2D games that should not require manual calculations.

**Comment by einarf** [comment]
Seems this have been requested multiple times. It's an easy feature to add that will help a lot of people getting started.

**Comment by pushfoo** [comment]
Should shapes or any other types also have this as a feature?

**Comment by einarf** [comment]
Shapes are more or less just in maintenance mode right now. It's very limited what we can do with them due to the design I think. I am more hoping to get those back in track again in 2.7.x when we get pyglet and arcade compatible.

**Comment by einarf** [comment]
Should be in 2.6.11 now.
