### ISSUE TITLE
pyglet.gl.lib.GLException: Invalid enum.

### ISSUE THREAD

**Issue by sasdallas** [pythonarcade/arcade#1092]
## Bug Report
I am attempting to make a game in Arcade. I am doing step 1 of the Platforming tutorial.\
It will not allow me to run a window.

### Actual behavior:
Error message: 
```
pyglet.gl.lib.GLException: (0x500): Invalid enum. An unacceptable value is specified for an enumerated argument.
```

### Expected behavior:
The window to open.

### Steps to reproduce/example code:
Code:
```
import arcade

WIDTH = 800
HEIGHT = 640
TITLE = "game"

class MainWindow(arcade.Window):
    def __init__(self):
        super().__init__(WIDTH, HEIGHT, TITLE)
        arcade.set_background_color(arcade.csscolor.CORNFLOWER_BLUE)
    
    def setup(self):
        pass

    def on_draw(self):
        self.clear()


w = MainWindow()
w.setup()
arcade.run()
```

Then, just run `python3 main.py`.

### Other information:
I am running this on [GitPod](https://gitpod.io).

Docker container info:\
Container: `gitpod/workspace-full-vnc` (Uses noVNC)

Thank you!

**Comment by Cleptomania** [comment]
As far as I’m aware Gitpod does not support GPU accelerated applications(OpenGL, Vulkan, etc etc). Arcade requires a GPU with support for OpenGL 3.3 or higher.

It does work with repl.it, however tends to be quite laggy unless you use a boosted repl from their paid plan.

**Comment by sasdallas** [comment]
@Cleptomania That’s odd. I have replit, and am using a boosted repl, however it doesn’t work.

Instead, the repl exits with the error `ImportError: Library ‘GL’ not found.`

**Comment by sasdallas** [comment]
How do I fix this issue?

**Comment by sasdallas** [comment]
I’ll close this issue and start a new one for replit.
