### ISSUE TITLE
Expose text height

### ISSUE THREAD

**Issue by facundobatista** [pythonarcade/arcade#1095]
(first of all, thanks for Arcade, it's amazing)

## Enhancement request:

The height of the resulting text should be exposed in the Text object.

### What should be added/changed?

```
    @property
    def height(self) -> str:
        """
        The height of the content.
        """
        return self._label.content_height
```

### What would it help with?

It will simplify writing several lines in the screen without doing weird math with the font size (making it indenpendent, in fact).

Something like the following:

```
pos_y = 600
for phrase in several_phrases:
    text = arcade.Text(phrase, start_x=500, start_y=pos_y, anchor_y="top", font_size=25)
    text.draw()
    pos_y -= test.height
```

**Comment by einarf** [comment]
Looked at this brifely. It seems `width` and `height` is different from `content_width` and `content_height`. I think the first ones are meant to be some label metadata while the other last ones are the physical size of the text.

**Comment by alejcas** [comment]
> Looked at this brifely. It seems `width` and `height` is different from `content_width` and `content_height`. I think the first ones are meant to be some label metadata while the other last ones are the physical size of the text.

I can confirm that content_X are the size of the text

**Comment by einarf** [comment]
The question is then how we separate `width` / `height` and `content_width` / `content_height`. I don't think the former values have a much meaning for arcade, but they could potentially.

**Comment by einarf** [comment]
Fixed with the following changes:

* Added `content_width`, `content_height` and `content_size`
* Added missing info in various docstrings
* Added `.text` property alias for `.value`
* Added `height` property

`width` and `height` is more relevant to text flow and scrolling while the `content_*` variants are for the exact pixel size of the text.

**Comment by einarf** [comment]
Be  free to comment on the referenced commits. Flagging this as fixed for now.

**Comment by einarf** [comment]
Thanks for the comment on the commits. I think the api docs should be pretty clear now.

**Comment by einarf** [comment]
2.6.11 released

**Comment by einarf** [comment]
FYI: I also added added `left`, `right`, `top` and `bottom` properties in development branch now.

**Comment by facundobatista** [comment]
Awesome, thanks!
