### ISSUE TITLE
Assert error when using multiline=True with arcade.gui.UILabel

### ISSUE THREAD

**Issue by JackAshwell11** [pythonarcade/arcade#1097]
### Actual behavior:

An assertion error is outputted:
`AssertionError: When the parameters 'multiline' and 'wrap_lines' are True, the parameter 'width' must be a number.`

### Expected behavior:

The label is shown as a multiline widget. This can be avoided by using a UITextArea, but should be fixed.

### Steps to reproduce/example code:

Using this code inside a UIManager:

```python
question_text = arcade.gui.UILabel(
            text="f",
            width=750,
            height=350,
            text_color=arcade.color.BLACK,
            font_size=24,
            multiline=True,
            align="center",
)
```

**Comment by Ibrahim2750mi** [comment]
This should also be fixed now.

**Comment by eruvanos** [comment]
Fixed in dev
