### ISSUE TITLE
Documentation: Update lighting example doc

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1103]
### What documentation needs to change? 
The docstring for the lighting example

### Where is it located?
https://api.arcade.academy/en/latest/examples/light_demo.html#light-demo

### What is wrong with it? How can it be improved?
It mentions 2.4 as an upcoming release despite 2.4 being very old. The explanation of requirements for use can be clearer overall as well.

This is confusing for beginners, as at least one user on discord interpreted the current doc to mean lights had to be downloaded from github:
> Okay, it’s just that the web page says that the light needs to be downloaded from GitHub.

**Comment by einarf** [comment]
There was a few more instances referencing "upcoming 2.4 release". All removed in 70d84ec55e17c0a7432d61ae0572aa792caccc8b
