### ISSUE TITLE
Promote using `Text` objects in examples

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1111]
The future of text is `Text` objects. `arcade.draw_text(..)` will in most cases be 10-100 times slower no matter how many fancy tricks we come up with.

We should start to promote using `Text` objects over `draw_text()` in examples to slowly start a process were we can possibly remove `arcade.draw_text` in the future.

**Comment by einarf** [comment]
Examples exposed in docs will need their line numbers updated if code is highliged there.

**Comment by einarf** [comment]
Added performance warning 3941029ace683bff3913496fc60a88d68368780f

**Comment by pushfoo** [comment]
The View examples currently have some draw_text in them on `development` branch. If anyone reads this, feel free to fix that. I'll clean it up later if nobody beats me to it.

**Comment by einarf** [comment]
Done
