### ISSUE TITLE
Compute Shader Object missing UBO support.

### ISSUE THREAD

**Issue by DragonMoffon** [pythonarcade/arcade#1112]
## Bug Report

If a compute shader loads a program with a UBO in it. It crashes due to the Compute Shader object not having the. '_query_uniform_block' attribute.

### Actual behaviour:

when creating a Compute Shader with a UBO it crashes with the error:
```python
    shader = ctx.load_compute_shader("shaders/compute_example.glsl") 
File \arcade\context.py", line 365, in load_compute_shader
    return self.compute_shader(source=path.read_text())
File "\arcade\gl\context.py", line 741, in compute_shader
    return ComputeShader(self, source)
File "\arcade\gl\compute_shader.py", line 74, in __init__
    self._introspect_uniform_blocks()
File "\arcade\gl\compute_shader.py", line 175, in _introspect_uniform_blocks
    index, size, name = self._query_uniform_block(loc)
AttributeError: 'ComputeShader' object has no attribute '_query_uniform_block'. Did you mean: '_query_uniform'?
```

### Expected behaviour:

For it to return a compute shader without issue.

### Steps to reproduce/example code:

write a compute shader with a UBO in it.

**Comment by einarf** [comment]
Fixed in development branch.

**Comment by einarf** [comment]
2.6.12 released
