### ISSUE TITLE
Enhancement: Adding a clear method in UIManager

### ISSUE THREAD

**Issue by Ibrahim2750mi** [pythonarcade/arcade#1114]
### What should be added?
In [arcade.gui.ui_manager](https://api.arcade.academy/en/latest/_modules/arcade/gui/ui_manager.html#UIManager) there should be a method to clear the container.

### What would it help with?
Consider a situation where you want to have buttons which will open to more buttons in the same position, instead of creating a new arcade.gui.ui_manager or manually removing with [walk_widgets](https://api.arcade.academy/en/latest/api/gui.html#arcade.gui.UIManager.walk_widgets) and the remove method.

**Comment by eruvanos** [comment]
Will be released with next version

**Comment by eruvanos** [comment]
Released
