### ISSUE TITLE
Bibtex entry

### ISSUE THREAD

**Issue by gaorkl** [pythonarcade/arcade#1119]
## Enhancement request:

Given the quality and versatility of the library, more and more people from the AI community might start to use it.
When writing scientific papers, we usually cite libraries that we use.

### What should be added/changed?

I would suggest to add a bibtex entry to your README.
For example:
https://github.com/maximecb/gym-minigrid
https://github.com/openai/gym

### What would it help with?

Free advertising is always nice.

**Comment by einarf** [comment]
Quickly added this : https://github.com/pythonarcade/arcade#citation
