### ISSUE TITLE
Raycasting shader tutorial breaks if window resized

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1121]
### Actual behavior:

Resizing the window of the [raycasting shadow tutorial](https://api.arcade.academy/en/latest/tutorials/raycasting/index.html) produces misaligned shadows for any form of window resizing.

![Screenshot from 2022-03-22 01-11-43](https://user-images.githubusercontent.com/36696816/159417217-bf61f94e-86e5-497d-92ef-a8779c1a433b.png)
Some forms of window resizing also produce noticeable smearing artifacts.
### Expected behavior:
Shadows stay aligned when resizing, no artifacts are produced

### Steps to reproduce/example code:

**System info:**

from `lsb_release -a`:
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

DE / tiling setup:
1. Wayland
2. GNOME 3.38.5
3. pop_shell [installed from git](https://github.com/pop-os/shell/commit/396b2f3c)

from `/proc/cpuinfo`:
```
model name	: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
```

from `sudo lshw -C display`:
```
  *-display
       description: VGA compatible controller
       product: UHD Graphics 620
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
```

#### Manually Resizing:
1. Launch the example from [step 6 of the tutorial](https://api.arcade.academy/en/latest/tutorials/raycasting/#step-6-soft-shadows-and-wall-drawing)
2. Resize the window manually
3. Misaligned shadows and smearing artifacts produced 
![Screenshot from 2022-03-22 01-30-49](https://user-images.githubusercontent.com/36696816/159414309-165cbcca-0534-4a5b-ac2e-c8bdd141fdc7.png)

#### Resizing Through Tiling:
 
1. Enable tiling if it's optional on your DE
2. Launch the example from [step 6 of the tutorial](https://api.arcade.academy/en/latest/tutorials/raycasting/index.html?highlight=shadow#step-6-soft-shadows-and-wall-drawing)
3. Shadows are misaligned, but smearing artifacts are minimal
![Screenshot from 2022-03-22 01-10-43](https://user-images.githubusercontent.com/36696816/159415555-f7c314c7-dfd3-492c-8555-5ebbd577d592.png)

#### 1. Disable window resizing for tutorial

1. Change `resizable` to `False` for the tutorial
2. Add comments explaining that window resizing will be extra work, and may decrease performance of the game.

This seems like the best option. It will help users make performant games, reduce work for maintainers, and avoid ugly texture allocation issues ([example](https://github.com/kivy/kivy/issues/6708)).

#### 2. Add window resizing support
This will take additional work and may thrash memory if textures are allocated repeatedly for each resize event. Bugs in setting texture [can also over-allocate and cause crashes](https://github.com/kivy/kivy/issues/6708).

**Comment by einarf** [comment]
`.clear()` channel0 and channel1 after `use()`
Then add on_resize
```py
    def on_resize(self, width: float, height: float):
        super().on_resize(width, height)
        self.shadertoy.resize((width, height))
```

**Comment by pvcraven** [comment]
Cool, started working on fixing it. Thanks.

**Comment by einarf** [comment]
@pvcraven This also means you can add scrolling, something what would add a lot of value to the example I think. Clearing the channels is what makes that work,

**Comment by pvcraven** [comment]
Tutorial has been updated quite a bit. Issue should be fixed now. Thanks.
https://api.arcade.academy/en/development/tutorials/raycasting/index.html

**Comment by pushfoo** [comment]
The fixes work locally for both manual and automatic window resizing. It's a bit slow, but I think that's down to my GPU being very weak.

**Comment by einarf** [comment]
2.6.13 released
