### ISSUE TITLE
Python 3.10.2 crash upon import

### ISSUE THREAD

**Issue by Minyguy** [pythonarcade/arcade#1124]
## Bug Report

![image](https://user-images.githubusercontent.com/18747823/159459460-beb805fc-6acb-426b-8f10-be5fc01c8cec.png)

I don't know what else to write.

I'm running on Manjaro Gnome. (ARCH-based linux)

**Comment by einarf** [comment]
There should be a fix in pyglet master branch `pip install -I https://github.com/pyglet/pyglet/archive/refs/heads/master.zip`

**Comment by einarf** [comment]
2.6.13 released with new pyglet fixing this issue.
