### ISSUE TITLE
Add sprite options to `UISpriteWidget`

### ISSUE THREAD

**Issue by aphkyle** [pythonarcade/arcade#1128]
## Enhancement request:
Add sprite options to `UISpriteWidget`,
(Optional `surface.clear`)
(unrelated but typehints on `Surface.draw_sprite` pls, thanks)
### What should be added/changed?
Add some parameters to the `do_render` function of `UISpriteWidget`,
to draw sprites with `Sprite.draw` options.
### What would it help with?
![image](https://user-images.githubusercontent.com/81857274/159842170-d2f27d37-55b9-4b89-a350-4a00235d236c.png)
It'll make the sprites pixelated, and look better
![image](https://user-images.githubusercontent.com/81857274/159842233-7d64aa8b-039c-4168-8405-3f97f1cd389e.png)

**Comment by aphkyle** [comment]
Draft:
```py
import arcade
from arcade.gui.surface import Surface
from arcade.gui.widgets import UISpriteWidget


class CustomSurface(Surface):
    def draw_sprite(
        self,
        x: int,
        y: int,
        width: int,
        height: int,
        sprite: arcade.Sprite,
        filter=None,
        pixelated=None,
        blend_function=None,
    ):
        sprite.set_position(x + width // 2, y + height // 2)
        sprite.width = width
        sprite.height = height
        sprite.draw(filter=filter, pixelated=pixelated, blend_function=blend_function)


class CustomSpriteWidget(UISpriteWidget):
    def do_render(
        self,
        surface: CustomSurface,
        clear=True,
        filter=None,
        pixelated=None,
        blend_function=None,
    ):
        surface.__class__ = CustomSurface
        self.prepare_render(surface)
        if clear:
            surface.clear(color=(0, 0, 0, 0))
        surface.draw_sprite(0, 0, self.width, self.height, self._sprite, filter, pixelated, blend_function)
```
This is the code I used in my game, might be helpful.

**Comment by eruvanos** [comment]
Thanks for the request, 
the rendering and blending of the GUI would most likely interfere with the context parameter changes the `Sprite.draw()` function does in the background.

Because the sprite drawing feature within the GUI is more an edge case, which can often be replaced with `UIImage` I will not dig deeper into this, I am sorry.

I am really happy, that you already found a workaround, which worked for you.
