### ISSUE TITLE
Text not rendering properly when using 1 letter

### ISSUE THREAD

**Issue by Ibrahim2750mi** [pythonarcade/arcade#1133]
### Actual behavior:
Basically it renders the text, weird when just providing 1-3 letters
![](https://cdn.discordapp.com/attachments/866366788924735549/957320170777481306/2022-03-26_22-17_2.png)
![](https://cdn.discordapp.com/attachments/866366788924735549/957320170567774298/2022-03-26_22-17_1.png)
![](https://cdn.discordapp.com/attachments/866366788924735549/957320170349690910/2022-03-26_22-17.png)

### Expected behavior:
was able to get this after adding alot of space after `3`
![](https://cdn.discordapp.com/attachments/866366788924735549/957320703651250316/2022-03-26_22-20.png)

### Steps to reproduce/example code:

```py
import arcade


class MyWindow(arcade.Window):
    def __init__(self):
        super().__init__(1000, 700, "Example", resizable=True)

        arcade.set_background_color(arcade.color.DARK_BLUE_GRAY)

        self.text_list = []
        for i in range(4):
            text = arcade.Text(text="3",start_x=250 + (i*50), start_y=50)
            self.text_list.append(text)

    def on_draw(self):
        self.clear()

        for text in self.text_list:
            text.draw()


if __name__ == '__main__':
    window = MyWindow()
    arcade.run()
```

**Comment by einarf** [comment]
Are you using arcade 2.6.13? If so, can you also check that pyglet 2.0a2 is installed?

**Comment by Ibrahim2750mi** [comment]
after switching to pyglet to 2.0a2 it works!
