### ISSUE TITLE
Particles don't care about frame time

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1137]
On some systems particles are :

* Not moving smoothly
* Have a longer or shorter lifespan based on framerate
* Fades faster or slower based on framerate

Looking at this briefly it's clearly realted to `update()` methods in sprite and spritelist.

Frametime was probable hardcoded because update don't have frametime parameter:

https://github.com/pythonarcade/arcade/blob/a0213acc263dd3d89da9ffb4abd19f3d7e43e79a/arcade/particle.py#L101-L104

We do have an `on_update` method now that takes a frame time. The whole `update` vs `on_update` siutation should probably be resolved in the next major version of arcade. For now I think moving the logic to `on_update` and calling that from `update` with hardcoded delta time is a possible fix. The `Emitter` should be changed to call `on_update` and we need to somehow find a delta time to pass in without breaking anything.

**Comment by pushfoo** [comment]
This is still a valid ticket as of 2023.

**Comment by einarf** [comment]
Yes. It's a general frame time issue in arcade. I put it on 3.0 milestone for a reason. We need to solve this before release I think. It's very imporant.

Arcade currently works with ticks assuming 60fps. This is how sprite and sprite velocity also works now. We should make a thread about this on discord and figure something out.

**Comment by DragonMoffon** [comment]
could be fixed with issue #1795.

**Comment by einarf** [comment]
Fixed in https://github.com/pythonarcade/arcade/pull/2288
