### ISSUE TITLE
`calculate_hit_box_points_detailed` crashes if the provided image doesn't have black pixels

### ISSUE THREAD

**Issue by Diapolo10** [pythonarcade/arcade#1146]
## Bug Report

If the function is called with an image that doesn't have black pixels, the function crashes with a TypeError when it tries to treat the variable `color` as a `tuple`, but it contains an `int` instead.

```
Traceback (most recent call last):
  File "d:/github/rl_car/rl_car/game.py", line 314, in <module>
    main()
  File "d:/github/rl_car/rl_car/game.py", line 309, in main
    window.setup()
  File "d:/github/rl_car/rl_car/game.py", line 169, in setup
    self.track_outer_hitbox = align_hitbox(hitbox_from_image(TRACK_BARE_SPRITE))
  File "d:/github/rl_car/rl_car/game.py", line 288, in hitbox_from_image
    hitbox = list(arcade.calculate_hit_box_points_detailed(image, hit_box_detail=hit_box_detail))
  File "C:\Users\laril\AppData\Local\pypoetry\Cache\virtualenvs\rl-car-usInqqGI-py3.8\lib\site-packages\arcade\hitbox.py", line 175, in calculate_hit_box_points_detailed
    if sample_func(p1) and sample_func(p2) and sample_func(p3) and sample_func(p4):
  File "C:\Users\laril\AppData\Local\pypoetry\Cache\virtualenvs\rl-car-usInqqGI-py3.8\lib\site-packages\arcade\hitbox.py", line 164, in sample_func
    if color[3] > 0:
TypeError: 'int' object is not subscriptable
```

## System Info

Arcade 2.6.7
------------
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
version: (4, 6)
python: 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)]
platform: win32

### Actual behavior:

Crashes with an unexpected error.

### Expected behavior:

Creates and returns a hit box around the furthermost non-transparent pixels.

### Steps to reproduce/example code:

Call `arcade.calculate_hit_box_points_detailed` with any image file that doesn't contain any black pixels:

```py
from pathlib import Path

import arcade
from PIL import Image

IMAGE_FILE = Path(__file__).parent / 'some_image.png'

with Image(IMAGE_FILE) as image:
    _ = arcade.calculate_hit_box_points_detailed(image)
```

**Comment by einarf** [comment]
Great bug report!

This is because it expects and RGBA image and it's failing to find an alpha channel. We should check the image mode in the beginning of the fuction and provide some useful feedback. Function docs also needs to be more specific.

To solve this:
```py
with Image(IMAGE_FILE) as image:
    image = image.convert("RGBA")
    _ = arcade.calculate_hit_box_points_detailed(image)
```

Pillow might also support loading as RGBA directly.

**Comment by einarf** [comment]
* Added user friendly feedback when image is not RGBA
* Updated API docs to specify RGBA is needed
* Added tests
