### ISSUE TITLE
Texture cache improvements

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1154]
The current texture cache is just a dyamic property stored on the `load_texture `function in texture module. It's hard do access if you want to do anything other than clearing it with the providied ` cleanup_texture_cache()` method. I think we should just move the cache to a different module `texture_cache.py` and make it easily accessible.

In addition we should probably provide the user with some options:
* `EternalTextureCache` is default
* `WeakTextureCache` uses a weak dict
* `NullTextureCache`  does no caching what so ever
* User can make their own cache

There are a couple of other things we could resolve while doing this. Right now textures are more or less eternal unless you clear the cache. Textures written to the texture atlas are also never removed if a texture is garbage collected. Some things that would resolve this:

* Wrap the `image` (PIL image) in an `ImageData` type. This would store the unique name of the texture and is the object we cache
* The `ImageData` would know what texture atlas(es) it's currently in.
* `ImageData.__del__` or a weakref.finalize can trigger the object to remove itself from atlases

If the arcade default is a `WeakTextureCache` we can avoid a lot of use cases were the global texture atlas is flooded to the brim even when users are doing something sub-optimal.

**Comment by alejcas** [comment]
Just leaving this here. Current cache implementation saves the texture reference twice into the cache: one with the texture name and another one with a key that's build using all the params (rotation, etc.).
I don't know the reasons behind this but probably storing the texture once will improve (tiny) memory.

**Comment by einarf** [comment]
> I don't know the reasons behind this but probably storing the texture once will improve (tiny) memory.

Definitely we should simplify and store it once.

**Comment by alejcas** [comment]
Hi @einarf, what's the state on this issue?
can I somehow help here?

**Comment by einarf** [comment]
It will be fixed when we merge the `texture-revamp` branch. It's kind of already done.

**Comment by einarf** [comment]
This issue is still valid and code will be merged soon.

After a lot of discussion we're ripping off the band-aid in 3.0 with a major breaking change. The `arcade.load_*` functions will no longer do any caching. They will do exactly what most people assume they are already doing .. loading something from disk every call.

However .. we will offer a new TextureManager with the equivalent load methods and internal cache (configurable). It also means you can have several different managers to separate eternal and "per level" textures. In addition the `TextureAtlas` now hooks into python's garbage collection system and flushes dead textures. This is an important reason the `arcade.load_*` methods should not cache since beginner/intermediate users will end up with full default atlas not quite understand what is happening.

Tilemaps can take an optinal texture manager. If not supplied an internal one can be created. It's important because the internal texture loading heavily relies on the `load_texture(path, x, y, w, h)` method for cropping out a smaller section of a texture. In 3.0 this should grab a cached `SpriteSheet` and simply call `crop(..)` on it (unless the section is already cropped and cached).

The internal cache handling is kind of complex because we cache:
* images using the sha256 hash
* Hit box points for an image for each hit box algorithm
* texture instances (based on image, hit box algo, ..)

The downside is that some user doing the following will experience major slow downs due to loading a texture multiple times

```py
for _ in range(10):
    spritelist.append(Sprite(arcade.load_texture("assets:test.png")))
```

However .. the trouble of keeping the old caching behavior is a much greater evil leading to countless other issues down the line.

**Comment by alejcas** [comment]
Hi @einarf ,

what's the current state of the texture cache right now in @development branch?

Thanks!

**Comment by einarf** [comment]
Merged
