### ISSUE TITLE
arcade.gl.Limits should be more robust

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1161]
We should probably `getattr` the enums from pyglet's gl module and supply a default value in `get()` methods in case fetching the enum fails.

**Comment by Cleptomania** [comment]
Was this finished? I know we made the limits not crash if fetching it fails, but I'm unsure if there was more to be done or not.

**Comment by einarf** [comment]
Yup. Fixed that while doing some polish on the GLES stuff. The getter methods now suppress and consume the error message returning some default value instead.
