### ISSUE TITLE
GUI: Simple 9patch texture renderer

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1164]
When drawing rounded backgrounds and buttons it would be nice to draw them as a 9patch ensuring the corners don't get streched. The widget should also be resizable and the same texture can be used in all widgets needing that background.

![bilde](https://user-images.githubusercontent.com/5418180/161447593-2262d756-4d1b-4926-9dfe-19a131146af8.png)

**Comment by eruvanos** [comment]
I guess it would be enough to have some NinePatch image class, which just provides resizing and can return a texture or PIL image?

**Comment by einarf** [comment]
This is now in development but shader needs a tweak when we merge the texture-revamp branch.
