### ISSUE TITLE
Mascot and custom sprites.

### ISSUE THREAD

**Issue by DragonMoffon** [pythonarcade/arcade#1170]
## Enhancement request:

MASCOT! I think we should look into getting a mascot for use in the docs and some custom tilesets and characters in the code. Using the Kenny resources works, but it seems pretty bland and generic. Having some more custom sprites would give Arcade a nicer customised feel.

In some tutorial docs, we have used characters to point at code and the like (I read at least one tutorial that had this. I can't find it but it was at most 2 weeks ago). It is quite inconsistent, but I like the idea of it. Having a Custom mascot in various poses could spice up the tutorials. Now we would have to source such assets, and it would be preferable if we had full ownership of the assets. I'm not a great artist, so I couldn't make what I'm suggesting, but It would be nice to see in the future. It would also give Arcade some more consistent and unique branding!

I am slowly cooking up an advanced Platformer tutorial, and I'm happy to give the tileset and character I make for that to Arcade, but It will be low resolution, and some people may prefer a cleaner tileset like the Kenny stuff.

**Comment by pvcraven** [comment]
Actually, if we ever get money by making a manual-book, we could always use that for a graphic artist.

**Comment by einarf** [comment]
We can make this happen in discord channels
