### ISSUE TITLE
Suggestion: Clean up arcade specific geometry functions

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1179]
Instead we could use `pyglet.math.Vec2` or a cythonized version of this in the future. We do need to take performance into consideration here. Profiling is needed.

Also, if we have functions taking a vector with separate arguments for x and y we should strongly consider changing that to a single `Tuple[float, float]` or similar.

**Comment by pushfoo** [comment]
What's the performance overhead of tuples vs floats?

**Comment by pvcraven** [comment]
Functions taking in separate x and y values are useful for instruction. It allows students to create functional games before learning about lists.

**Comment by einarf** [comment]
> Functions taking in separate x and y values are useful for instruction. It allows students to create functional games before learning about lists.

Ok. So we need to find a balance here between what's needed in education and what's needed for the general hobby game developer. The idea here is that a `Vec2` cab also be used since it's a subclass of `tuple`.

Variant now
```py
x1 = 0
y1 = 0
x2 = 1
y2 = 0
angle = get_angle_degrees(x1, y1, x2, y2)
```

Possible future variant

```py
p1 = Vec2(0, 0)
p2 = Vec2(1, 0)
angle = p1.angle_to_point(p2) 
```

We have a lot methods in arcade that are kind or redundant and/or have unprecies names. Like `get_angle_degrees` does not convey it's an angle between points (could be vector etc) and we are kind of forced to keep building on these over time. I'm not sure how this makes sense in an educational setting. We can probably find a middle ground here if needed.

The arcade functions for calculating various things are also pretty well optimized compared to using tuples (possibly). It's a good argument for keeping them around. It's an area that needs to be explored, but at the very least they should stay in the `arcade.geometry` module/namespace I think. That applies to a lot of other things.

Also remember this issue is more about changes in a potential "3.0" version down the line and not something I would personally dare to change in 2.x.

**Comment by pushfoo** [comment]
Introducing vectors early on while teaching arcade might not be a huge leap for students, even for young ones. When I was introduced to vectors for the first time, my biggest issue was that it was on paper and somewhat badly done. Showing cleaner code side by side with non-vector code could justify their use pretty quickly.

**Comment by pvcraven** [comment]
Ordering of material.

If you require understanding of tuples to do anything with drawing or sprites, you are left with two options:

* "Here type this, we'll explain it later" (I hate this option)
* Before we can do "x", we have to advance your programming to understand lists

There's a finite time before a student will 'check out' of being interested in the material. As they are humans, this differs for each person. Some people would be fine. Others check out the first 15 minutes of class. My hope is to 'hook' them before they check out.

So I currently use basic drawing commands as the main hook. Most of these drawing commands don't need tuples. They can get some graphics going, then lists are introduced. Next classes, and they can use sprites and sprite lists. 

Other people might have different ordering of material, and as such, you don't need to really use a lot in the way of lists to work with Sprites right now. The position is still a vector, but the center_x/center_y allows options for students to easily access those items. Even if that access is slower.

**Comment by einarf** [comment]
This is fair.

If we do some contributions to the `pyglet.math` we can at least offer an alternative instead of breaking the geomtry module. The teacher can choose to use the existing built in arcade functions or use `pyglet.math`.

Let's just close this for now and come up with a better issue that will bare more fruits. We can cater to `pyglet.math` types in other ways.
