### ISSUE TITLE
Make example thumbnail images clickable parts of links

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1181]
### What documentation needs to change? 
Example listing thumbnails

### Where is it located?
[doc/examples/index.rst](https://github.com/pythonarcade/arcade/blob/141c291c6ae78d7641c61894d0a5e5cb21df9e3f/doc/examples/index.rst)

### What is wrong with it? How can it be improved?
Clickable or tappable thumbnails are the norm in the eyes of younger users who grew up with touch interfaces. Older users might not be put off, but the examples listing may seem broken to students at the moment.

**Comment by pvcraven** [comment]
I'm not sure if you can set an image `target` to a reference? I'll have to try it.

**Comment by pushfoo** [comment]
I'm not sure I understand what you mean. To be clear on the intent for this ticket, the goal is making clicks or taps of a thumbnail be treated the same way as clicks or taps on link text.

I'll examine the example rst and read the relevant sphinx doc closely when I get a chance.

**Comment by pushfoo** [comment]
I got the following to work for a single example in `doc/examples/index.rst`:
```rst
.. figure:: thumbs/happy_face.png
   :figwidth: 170px
   :target: happy_face.html
   
   :ref:`happy_face`
```
I think this can be improved upon with macro-like functionality.

**Comment by pvcraven** [comment]
That works, but I hate hard coding html links, as they are more likely to break.

**Comment by pushfoo** [comment]
To my understanding, there is an unresolved limitation in sphinx that means linking html may be the easiest way to do it: https://github.com/sphinx-doc/sphinx/issues/4351 :disappointed:
