### ISSUE TITLE
PymunkPhysicsEngine creating invisible collision boxes with some maps

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1183]
During the pyweek game jam the PymunkPhysicsEngine was creating invisible collision areas for the tmx map in this project : https://github.com/aphkyle/xn--m28h

Had to swap to PhysicsEngineSimple. It might be something with the map or we have a bug somewhere. I remember there was a bug with collision in the tilmap not long ago, so I suspect the bug was compensated for in the pymunk version, but broke again when it was fixed in the map loading?

**Comment by gran4** [comment]
@einarf I think you can close this.
