### ISSUE TITLE
Optimize Sprite.rescale_relative_to_point

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1187]
### What should be added/changed?
Each line of `Sprite.rescale_relative_to_point` currently performs a sprite list update when it should do so only once at the end of the function:
https://github.com/pythonarcade/arcade/blob/a454fad5452d5d71343e53092527baa10796d193/arcade/sprite.py#L657-L661

https://github.com/pythonarcade/arcade/blob/a454fad5452d5d71343e53092527baa10796d193/arcade/sprite.py#L642-L656
https://github.com/pythonarcade/arcade/blob/a454fad5452d5d71343e53092527baa10796d193/arcade/sprite.py#L668-L678
https://github.com/pythonarcade/arcade/blob/a454fad5452d5d71343e53092527baa10796d193/arcade/sprite.py#L685-L695
### What would it help with?
1. #1164 , if done in Python rather than GL shaders
2. `SpriteList.rescale` would be much more efficient

**Comment by einarf** [comment]
Yea that doesn't look very efficient.

**Comment by pushfoo** [comment]
Today's discord conversation about verbs vs nouns got me thinking:
 Since this method also has a version on SpriteList, would it make sense to add a default `rescale_sprite_body=True` default kwarg for this method? It would be akin to `change_angle` from the rotate around point example:
https://github.com/pythonarcade/arcade/blob/ad3f54c1362c3fc547a087b50fa36a59a6868e0f/arcade/examples/sprite_rotate_around_point.py#L29-L48
I can see this change being useful for visual effects such as zooming into markers on maps or other similar visual effects.
