### ISSUE TITLE
Make example thumbnail styles consistent

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1191]
### What documentation needs to change? 
Screenshots on the [example index](https://api.arcade.academy/en/latest/examples/index.html) and example pages.

### Where is it located?
[`doc/examples`](https://github.com/pythonarcade/arcade/tree/development/doc/examples)

### What is wrong with it? How can it be improved?
The upcoming Furo theme may make visual inconsistencies stand out more. One such inconsistency is the range of OS window decorations in example previews:

![image](https://user-images.githubusercontent.com/36696816/163111542-f0827a8e-ab14-4cf2-8bf6-519ae62fec50.png)
*Borderless*
![image](https://user-images.githubusercontent.com/36696816/163108550-9ed9259e-c12b-4389-a136-08f2d89f119d.png)
*Windows*
![image](https://user-images.githubusercontent.com/36696816/163108675-c6bc8c65-51dc-49c9-b965-89788e984458.png)
*macOS with a transparent border*

The heights of thumbnails also vary, positioning the link text at varying heights. Lastly, inter-thumbnail spacing isn't completely consistent. The combined result can be rather jarring:
![image](https://user-images.githubusercontent.com/36696816/163111445-f8447da5-ed54-4bba-b6ac-e8e0d0cab5ac.png)
![image](https://user-images.githubusercontent.com/36696816/163110384-fbbdda3d-bc59-4bd2-93c7-e157ba685c9f.png)

We could improve the thumbnails by doing the following:
1. Make all example screenshots borderless, containing only the examples themselves
2. Improve inter-thumbnail spacing consistency
3. If supported by sphinx, set a consistent height instead of a consistent width

The Tetris thumbnail could also be made more legible by removing the grid from the preview and adding an option to enable or disable the grid spacing in-game.

**Comment by einarf** [comment]
We no longer use Furo theme. This is fixed in the `rdt-docs` branch
