### ISSUE TITLE
Expose the new gamecontroller api in pyglet

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1196]
Right now we are using the old joystick api. Pyglet 2 comes with a new gamecontroller api that has much mode advanced support. Because pyglet doesn't come with a full database of gamecontollers we probably also need to include 400kb file with all known controllers.

See: https://github.com/pyglet/pyglet/issues/574

**Comment by einarf** [comment]
Pyglet don't have all the mappings, so we might have to look into loading additional controllers from another more updated database:
```py
import os
import urllib3 as urllib
import pyglet

# Download the latest Controller mapping database:
url = "https://raw.githubusercontent.com/gabomdq/SDL_GameControllerDB/master/gamecontrollerdb.txt"
try:
    with urllib.request.urlopen(url) as response, pyglet.resource.file("gamecontrollerdb.txt", 'wb') as f:
        f.write(response.read())
except urllib.error.URLError:
    pass

# Add the additional mappings to pyglet:
if os.path.exists("gamecontrollerdb.txt"):
    try:
        pyglet.input.controller.add_mappings_from_file("gamecontrollerdb.txt")
        print("Added additional controller mappings from 'gamecontrollerdb.txt'")
    except AssertionError:
        print("Failed to parse 'gamecontrollerdb.txt'.")
```

There are other version of the game controller db around.

**Comment by Cleptomania** [comment]
This is finished with #1473. We have added the SDL controller DB as part of that.
