### ISSUE TITLE
Changing the style of a UIFlatButton at runtime does not appear to do anything

### ISSUE THREAD

**Issue by benjamin-kirkbride** [pythonarcade/arcade#1209]
title

**Comment by benjamin-kirkbride** [comment]
the `trigger_render()` method does not help

**Comment by benjamin-kirkbride** [comment]
there is no publicly accessible `style` attribute. Changing the private one does work.

![image](https://user-images.githubusercontent.com/3373830/166343455-7b6ceb2a-9dbe-4c67-aece-09c0bfafb324.png)

Is this intended to not be part of the public API? What is the intended way to do this? Destroy and recreate the button? I really doubt that that is more performant ?

**Comment by einarf** [comment]
2.7 branch has proper style suppor as far as I know.

**Comment by Ibrahim2750mi** [comment]
After a rewrite of styles, the style attribute is now public.

**Comment by eruvanos** [comment]
FIxed, Example: https://github.com/pythonarcade/arcade/blob/6d249df03490b0fa2b0bf60db9332a28bf4f0107/arcade/gui/examples/style_v2.py
