### ISSUE TITLE
Improve documentation around create_empty and rendering to texture

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1210]
### What documentation needs to change? 
The documentation for `arcade.Texture.create_empty`

### Where is it located?
https://api.arcade.academy/en/latest/api/texture.html?highlight=create_empty#arcade.Texture.create_empty

### What is wrong with it? How can it be improved?
The [current documentation](https://api.arcade.academy/en/latest/api/texture.html?highlight=create_empty#arcade.Texture.create_empty) leans heavily on Pillow for rendering into textures, which is cumbersome and inefficient in multiple ways. A user previously asked about pre-rendered images for units that include color, icons, and flags. @einarf [suggested using a `render_into` method on a texture atlas as a more efficient way than using pillow](https://discord.com/channels/458662222697070613/696054807840030740/955778162355216414):
```python
with self.spritelist.atlas.render_into(texture) as fbo:
     self.flag_sprite.draw()  # needs location/scale as well I guess
```

**Comment by pushfoo** [comment]
My notes also have this link: https://github.com/pythonarcade/arcade/blob/development/arcade/experimental/atlas_render_into.py

Is this something we can move out of experimental and into a full example? If so, I could take care of it while audio playback gets discussed more.

**Comment by einarf** [comment]
> Is this something we can move out of experimental and into a full example? If so, I could take care of it while audio playback gets discussed more.

This should definitely be done. I can look into moving and tweaking them in development branch

**Comment by einarf** [comment]
in 2.6.14
