### ISSUE TITLE
Make sure all examples include run instructions in their module docstring

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1211]
### What documentation needs to change?
Examples in the example section of the site. I'm not sure how many, but the first one I noticed is the[ music control demo](https://api.arcade.academy/en/latest/examples/music_control_demo.html).

### Where is it located?
`arcade/examples/*.py`

### What is wrong with it? How can it be improved?
Some examples may be missing run instructions or a well-formatted docstring at the top of the module.

**Comment by einarf** [comment]
This fixed for all exmaples and we have unit tests for it
