### ISSUE TITLE
missing vars in arcade.experimental.shadertoy pkg

### ISSUE THREAD

**Issue by jrbsystech** [pythonarcade/arcade#1213]
## System Info

Run this and paste the output here: python -m arcade

### Steps to reproduce/example code:
just load one of the example shadertoy shaders and try to compile it.

## Enhancement request:
when trying some basic shadertoy glsl I found the following vars missing:

arcade.gl.exceptions.ShaderException: Error compiling fragment shader (0): 0(31) : error C1503: undefined variable "iFrame"

arcade.gl.exceptions.ShaderException: Error compiling fragment shader (0): 0(43) : error C1503: undefined variable "iChannelResolution"

arcade.gl.exceptions.ShaderException: Error compiling fragment shader (0): 0(120) : error C1503: undefined variable "iFrameRate"

also: can the iMouse.z be added for it to be a vec3? For now just using iMouse.x.. No 3D zooming atm.
### What should be added/changed?

here are some typical examples:
example from shadertoy: 
https://www.shadertoy.com/view/ldtGWj
https://www.shadertoy.com/view/4sG3WV

### What would it help with?
full functionality of Shadertoy shader compiles.

### Where is it located?
arcade.experimental.shadertoy

### What is wrong with it? How can it be improved?
add and assign vars in main package..

**Comment by einarf** [comment]
Missing uniforms should be in development branch now
