### ISSUE TITLE
typo in arcade academy that conducts to a contradiction :)

### ISSUE THREAD

**Issue by cubr3** [pythonarcade/arcade#1219]
### What documentation needs to change? 
Nuitka page in arcade academy documentation

### Where is it located?
https://api.arcade.academy/en/latest/tutorials/compiling_with_nuitka/index.html

### What is wrong with it? How can it be improved?
the sentence "Note that the build is platform independent, meaning a Windows build will not work out-of-the-box on other OS" is always a contradiction.

should be: "Note that the build is platform dependent, meaning a Windows build will not work out-of-the-box on other OS"

**Comment by pushfoo** [comment]
Per https://github.com/Nuitka/Nuitka/issues/43, this seems like the correct change to make. PR shortly.
