### ISSUE TITLE
Bug: gui_slider example stops rendering text if dragged all the way right

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1223]
## System Info

Tip of development branch:
```
Arcade 2.6.14
-------------
vendor: Intel
renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
version: (4, 6)
python: 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
platform: linux
```
**Installing from pip is not affected by this bug**

### Actual behavior:
Dragging the slider all the way to the right makes the text vanish and not come back

### Expected behavior:
Dragging the text all the way to the right does not make text vanish.

### Steps to reproduce/example code:
1. Install arcade from the tip of development branch (6e43ec5 at time of writing)
2. `python -m arcade.examples.gui_slider`
![image](https://user-images.githubusercontent.com/36696816/169416670-4270cc43-63aa-4501-838a-4e4d3f0538a7.png)
3. Drag the slider all the way to the right
4. Text disappears
![image](https://user-images.githubusercontent.com/36696816/169416720-bab9355c-dabb-4f26-bbf7-6d5651dd569e.png) 
7. Drag slider left
8. Label text does not come back
![image](https://user-images.githubusercontent.com/36696816/169416793-27cb218c-1f94-4553-aa35-ab3e6b54a26c.png)

### Further info
2.6.14 installed from pip is not affected. [Git blame shows recent changes to the layout update functionality](https://github.com/pythonarcade/arcade/blame/6e43ec53e7bfa3dee1aa574404794e3695aad381/arcade/gui/widgets/text.py#L142-L153) that may be related.

**Comment by andrewhong04** [comment]
It seems like I cannot reproduce this bug. Has it been fixed by this PR? #1222

**Comment by pushfoo** [comment]
I can't replicate this on the tip of development either. However, I don't think that PR changed anything meaningful. It's more likely that other changes fixed this issue and created #1228.

**Comment by pushfoo** [comment]
Checking out the commit mentioned in the original issue (6e43ec5) restores the problem mentioned, so it does appear that more recent changes fix this.

**Comment by pushfoo** [comment]
This appears to have been closed by 225209a6. @eruvanos should we mark this as fix waiting for release?

**Comment by eruvanos** [comment]
Guess so. Thanks for checking :)

**Comment by pushfoo** [comment]
I can no longer replicate this with the 2.6.15 release installed from pip, so I'm marking it as closed.
