### ISSUE TITLE
Upgrade to Furo theme breaks line number display in examples

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1224]
## System Info
```
Browser: Version 101.0.4951.64 (Official Build) built on Debian 11.3, running on Debian 11.3 (64-bit)
```
### Actual behavior:
Line numbers do not align with code on [2.6.14](https://api.arcade.academy/en/2.6.14/examples/sprite_collect_coins.html#sprite-collect-coins) and [later](https://api.arcade.academy/en/later/examples/sprite_collect_coins.html#sprite-collect-coins):
![image](https://user-images.githubusercontent.com/36696816/169921364-e45d72f0-d626-48e0-bd18-3d0bfe4eaf1a.png)

### Expected behavior:
Line number styles align with code as in the old theme on [2.6.13](https://api.arcade.academy/en/2.6.13/examples/sprite_collect_coins.html#sprite-collect-coins) and earlier:
![image](https://user-images.githubusercontent.com/36696816/169921538-248493d8-47bb-4ae4-b8b3-dfe68764ede1.png)

### Steps to reproduce/example code:

1. Choose either the [2.6.14](https://api.arcade.academy/en/2.6.14/examples/) or [latest](https://api.arcade.academy/en/latest/examples/) version in the doc's version switcher
2. Click through to any example listed
3. Observe mismatch between line number height and code line height, with longer examples most affected

**Comment by pvcraven** [comment]
Temp-fixed by pinning pygments version.
