### ISSUE TITLE
Adding HTML Labels

### ISSUE THREAD

**Issue by eschan145** [pythonarcade/arcade#1234]
### What should be added/changed?
A label in `arcade.text_pyglet` that supports HTML text, based from `pyglet.text.HTMLLabel`.
### What would it help with?
Users would be able to create HTML text labels. This could be used for instructions with rich text, paragraphs, backstories, etc.

**Comment by einarf** [comment]
In arcade 2.7 you will be able to mix arcade and pyglet features freely.. like using HTMLLabel and Batch. This code is in the development branch (main branch on github)

**Comment by Cleptomania** [comment]
I'm not sure I see much value in adding a wrapper for HTMLLabel in Arcade given the improvements to mixing features from Arcade and pyglet. Normal `arcade.Text` objects can now be drawn with a Pyglet batch so it's even easier to mix them. Currently in 2.7+ you should be able to use HTMLLabel from Pyglet directly with no issue.

If anyone feels like there would be much benefit to adding a wrapper for it feel free to re-open this.
