### ISSUE TITLE
Enhancement: Split button row generation into a new UI widget class

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1248]
### What should be added/changed?
Generating a row of buttons from labels should become a dedicated UI element. An unencapsulated version of this behavior is currently present in UIMessageBox:
https://github.com/pythonarcade/arcade/blob/118722555fbe27ad727cb800b72ff3d3560b8f94/arcade/gui/constructs.py#L59-L63

### What would it help with?
It would make it easier to create button rows for other UI elements such as the file chooser (#1201). For example, the bottom row of buttons in this mockup could be implemented using the proposed widget:
![image](https://user-images.githubusercontent.com/36696816/174502732-7f0737fe-e610-4372-9a24-2e232daea2ef.png)

**Comment by JackAshwell11** [comment]
I've submitted #1253 which adds a UIButtonRow class.

**Comment by eruvanos** [comment]
Fixed with https://github.com/pythonarcade/arcade/pull/1580

Will be released within 3.0.
