### ISSUE TITLE
JavaScript Error in API docs

### ISSUE THREAD

**Issue by pvcraven** [pythonarcade/arcade#1249]
Go to this page: https://api.arcade.academy/en/development/quick_index.html

Shows this error:

![image](https://user-images.githubusercontent.com/1463116/174522355-8e088ca1-cac7-4fed-9467-abdefbd110a0.png)

**Comment by pushfoo** [comment]
This doesn't occur on 2.6.15 or earlier doc versions, so it's introduced or uncovered by recent changes.

**Comment by pushfoo** [comment]
~~The linked page no longer exists on the live site. Should this be closed?~~ The page was moved, not deleted. The issue still exists.

**Comment by pushfoo** [comment]
I can't replicate this on local builds, nor on any of the following:
1. https://api.arcade.academy/en/2.6.16/api_docs/api/quick_index.html
2. https://api.arcade.academy/en/development/api_docs/api/quick_index.html

Close it now, or wait till near-final 3.0 to verify? @pvcraven

**Comment by cspotcode** [comment]
I also can't replicate, seems fixed to me.
