### ISSUE TITLE
Documentation: Improve style of Attributes section

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1259]
### What documentation needs to change? 
The rendering & styling of entries in the attributes sections of classes.

### Where is it located?
On documentation for classes such as `arcade.Sprite`

### What is wrong with it? How can it be improved?
The current rendering of attributes writes the attribute names for classes as all caps characters:
![image](https://user-images.githubusercontent.com/36696816/175793307-75d8d23e-de44-40e6-91c7-f837cb41f835.png)

This interferes with the following:
* Searching the page with ctrl-f 
* Legibility, as these can look like python-style constants at a glance

Yes, this ticket his may overlap with #1239. However, integrating table plugins into our theme may be slower than tweaking sphinx config & CSS to make attributes match parameter formatting.

**Comment by einarf** [comment]
We'll just use the standard styled rendering with the new RTD docs. Customizing this is unlikely to happen. There's some new custom css in there at least.
