### ISSUE TITLE
Specific objects unresponsive to physics

### ISSUE THREAD

**Issue by eschan145** [pythonarcade/arcade#1273]
In a `PymunkPhysicsEngine`, can I make an object not react at all (no motion) to collisions with another specific type of object?
![image](https://user-images.githubusercontent.com/103769713/178642677-fc4abe05-844b-4ce3-a0db-286f5b62bfe2.png)
In the image above, could I make it so that when the player bumps into the rock, the rock will go through the key?

* If a rock hits the key, the key will not react
* If a gem hits the key, the key will react

Changing the body_type parameter will not work, it just shouldn't react to one type of item but still react to the other type.

**Comment by einarf** [comment]
I think you would have to copy and customize the physicsengine to support that. It's not an uncommon thing to do.

**Comment by eschan145** [comment]
How would I do that? Would I subclass `arcade.pymunk_physics_engine.PymunkPhysicsEngine`? Or would I rewrite a separate copy?

**Comment by einarf** [comment]
I would just start working on a copy since that gives the most freedom.
