### ISSUE TITLE
Wait for next Frame to Render / Enforce Frame to Render

### ISSUE THREAD

**Issue by Vinyzu** [pythonarcade/arcade#1281]
Hello,
i was planning to do some kind of loading animation, and to do that, i figured i have to wait for the next frame to load, so the loading animation loads.

Basicly, my question is if there is a way to wait for the next frame to render/draw or to manually render/draw the next frame.

Thanks in advance!

**Comment by Vinyzu** [comment]
Edit: I found the arcade.Window().test() method (which is exactly what i wanted =), but im not quit sure if its actually supposed to be used for rendering the next frame...

**Comment by einarf** [comment]
The typical way is using a `View` doiing the loading. It displays some loading screen and start loading resources. If you actually need some loading animation you have to get a bit more creative depending on how smooth you want this animation to be. The loading needs to give back control to the drawing periodically to update the animation somehow,

Looks like the community rpg project have an example of a `LoadingView`: https://github.com/pythonarcade/community-rpg/blob/main/rpg/views/loading_view.py

It's a pretty simple setup driven by a load function being called multiple times until everything is loaded: https://github.com/pythonarcade/community-rpg/blob/e71ba00a24a40de8a0bde37748b9c221d397aac6/rpg/load_game_map.py#L176-L207

There are more advanced ways to solve this as well. For example:
* Use a generator function halting/yielding after a minimum amount of time (let's say 20ms)
* Load data in a thread. This is fine for things like tetures and sound. Spritelists can also be created in thread if created with the `lazy=True` flag.
