### ISSUE TITLE
Incorrect command to launch view_instructions_and_game_over example

### ISSUE THREAD

**Issue by caarmen** [pythonarcade/arcade#1287]
### What documentation needs to change? 
The python command given in the `view_instructions_and_game_over` example.

### Where is it located?
arcade/examples/view_instructions_and_game_over.py

### What is wrong with it? How can it be improved?

The command specifies a python file extension, and it shouldn't.

Current doc:
```
If Python and Arcade are installed, this example can be run from the command line with:
python -m arcade.examples.view_instructions_and_game_over.py
```

Expected doc:
```
If Python and Arcade are installed, this example can be run from the command line with:
python -m arcade.examples.view_instructions_and_game_over
```

**Comment by einarf** [comment]
Thank you. We talked about adding unit test for this.
