### ISSUE TITLE
Missing `Optional[]` in `arcade.Window.__init__()`

### ISSUE THREAD

**Issue by lemonyte** [pythonarcade/arcade#1291]
## Bug Report
The type hint for the `screen` parameter in `arcade.Window.__init__()` is missing an `Optional[]` hint, and the default value is `None`. This causes type checkers like Pyright to underline `super().__init__()` in a subclass of `arcade.Window` with default arguments as an error. If possible I would like to work on this issue myself.

https://github.com/pythonarcade/arcade/blob/71807836c5359a0d0feddd7ffb276c03abd42e49/arcade/application.py#L85-L89

![image](https://user-images.githubusercontent.com/49930425/182242770-ccf737be-685e-4231-a349-80eb57b6f61b.png)

## System Info
Arcade 2.6.15

vendor: Intel
renderer: Intel(R) UHD Graphics
version: (4, 6)
python: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
platform: win32

### Actual behavior:
Pyright underlines the `__init__()` call with a [type error](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules).

### Expected behavior:
There should be no type errors for the default arguments, especially when other parameters use the `Optional[]` hint.

### Steps to reproduce/example code:
In VS Code, enable type checking by setting the `Python > Analysis > Type Checking Mode` option to `basic` or `strict`.
Paste the following code into a Python file.
```python
import arcade


class MyGame(arcade.Window):
    def __init__(self):
        super().__init__()
```

## Enhancement request:
Fix the typing issue.

### What should be added/changed?
Add `Optional[]` around the `pyglet.canvas.Screen` type hint.
```python
screen: pyglet.canvas.Screen = None,
```
Changed to:
```python
screen: Optional[pyglet.canvas.Screen] = None,
```

### What would it help with?
It would remove the Pyright error.

**Comment by pushfoo** [comment]
> If possible I would like to work on this issue myself.

Sounds good! We'll be ready to review a PR whenever you can make one.

**Comment by lemonyte** [comment]
Created PR #1292.
