### ISSUE TITLE
Multiple carets showing up on GUI text edit

### ISSUE THREAD

**Issue by eschan145** [pythonarcade/arcade#1308]
I'm making my own GUI toolkit using the Python Arcade library. Quite recently I found out that the `TextInput` widget isn't working. No text is displayed and the caret also isn't displayed. I know other than that it's working properly, as I was able to get some text that the user typed. But it isn't displaying.

I looked at the examples for the arcade GUI widgets and added a TextInput widget, but even that didn't draw correctly. In pyglet, its working correctly. I was able to run the text_input example without any bugs.

**EDIT**: The default text is being displayed, but the user can't type any additional text

**Comment by eschan145** [comment]
Actually I found out that I had maded changes to the Python arcade code, which made drawing incorrect. I reinstalled the Python arcade and Pyglet libraries and found that it is working now.

**Comment by eschan145** [comment]
But there's a problem. On a Windows 11, when you highlight some text, I get an extra caret. So if I highlight text three times, I would have seven carets.

**Comment by eruvanos** [comment]
Could somebody check if this issue still exists on Windows 11?

**Comment by einarf** [comment]
I don't see this in Win11. What do you mean by extra caret? Visually or some internal object.

These things are REALLY hard to reproduce unless you supply a minimal runnable example.

**Comment by eschan145** [comment]
I don't have time to check it now, but it was visual. The carets kept on being duplicated in the `TextInput`, although only one of them would work.

**Comment by einarf** [comment]
I think this is getting fixed in pyglet master branch  now.

**Comment by eruvanos** [comment]
Agree, we can reopen it, if it reappears.
