### ISSUE TITLE
Hanging while calling my_sprite.draw()

### ISSUE THREAD

**Issue by pvcraven** [pythonarcade/arcade#1315]
At least two current example code programs in 2.7 are hanging with a similar setup when calling a draw() command. It seems there needs to be a call to my_sprite_list.draw() and my_sprite.draw() for the hang to occur. I'm running on a Mac, and Clepto says this doesn't hang on Ubunto for him. 

Example code which prints "before player draw" but not "after player draw":

    import arcade
    
    SPRITE_SCALING = 0.5
    SPRITE_SCALING_COIN = 0.2
    
    SCREEN_WIDTH = 800
    SCREEN_HEIGHT = 600
    SCREEN_TITLE = "Example"
    
    
    class MyGame(arcade.Window):
    
        def __init__(self, width, height, title):
            super().__init__(width, height, title)
    
            self.player_sprite = None
            self.wall_list = None
    
        def setup(self):
            self.wall_list = arcade.SpriteList()
    
            self.player_sprite = arcade.Sprite(":resources:images/animated_characters/female_person/femalePerson_idle.png",
                                               SPRITE_SCALING)
            self.player_sprite.center_x = 50
            self.player_sprite.center_y = 64
    
            wall = arcade.Sprite(":resources:images/tiles/boxCrate_double.png", SPRITE_SCALING)
            wall.center_x = 300
            wall.center_y = 300
            self.wall_list.append(wall)
    
            arcade.set_background_color(arcade.color.AMAZON)
    
        def on_draw(self):
            self.clear()
    
            self.wall_list.draw()
            print("Before player draw")
            self.player_sprite.draw()
            print("After player draw")
    
    
    def main():
        window = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
        window.setup()
        arcade.run()
    
    
    if __name__ == "__main__":
        main()

I know calling `draw` directly on the sprite should be discouraged, but it should work or the method should be removed.

**Comment by einarf** [comment]
Weird. This is not the case in 2.6? I wonder if you stumbed over the same issue @eruvanos mentioned to me a whole back. Can you see what line is stalls on? If I'm right here it might stall on texture uploading.

And yes, it's seems to be a mac thing. Very critical to fix.

**Comment by einarf** [comment]
The following can be done: Enable gl debug in pyglet in both 2.6 and 2.7 and compare the output. It should give a dump of all the gl command issued.

**Comment by pvcraven** [comment]
Further investigation shows it getting stuck on this line in sprite.draw():

`self._atlas.use_uv_texture(1)`

And inside of that function:

`self._uv_texture.write(self._uv_data, 0)`

...and inside of that:

            gl.glTexSubImage2D(
                self._target,  # target
                level,  # level
                x,  # x offset
                y,  # y offset
                w,  # width
                h,  # height
                self._format,  # format
                self._type,  # type
                data,  # pixel data
            )

**Comment by einarf** [comment]
Yes. That's exactly what we ran into before.

**Comment by pvcraven** [comment]
Any magic for the debug? This doesn't seem to print anything extra:

    import pyglet
    pyglet.options['debug_gl'] = True
    pyglet.options['debug_gl_trace'] = True
    pyglet.options['debug_gl_trace_args'] = True

**Comment by einarf** [comment]
Might need to do that before you import arcade.

**Comment by einarf** [comment]
From from @eruvanos 
Left side works (2.6.x). Right side hangs.

![bilde](https://user-images.githubusercontent.com/5418180/187708516-c1fd26c9-c705-4cda-90b3-707c4ec3a38a.png)

The byte size of the data we are writing is 262144. That matches 4 floats per pixel.

**Comment by pvcraven** [comment]
Dump with the hanging version of the program:
https://pastebin.com/FvWPcFTE

**Comment by pvcraven** [comment]
2.6 working version dump: https://pastebin.com/C6war8ZB

**Comment by einarf** [comment]
Shot in the dark. Can you hardcode `_ext_separate_shader_objects_enabled = False`?
https://github.com/pythonarcade/arcade/blob/69674157c1936297cdff66455e09f97c18c491d7/arcade/gl/context.py#L199-L202

We might got some stack corruption going on here because some pointers are off? Very often in these sitiations the error is not even related to the problem.

**Comment by pvcraven** [comment]
I changed 199 to be False and it still hung.

**Comment by einarf** [comment]
You even commeted out the if check below?

**Comment by einarf** [comment]
To be clear. This is the needed modification. I should have been more clear if there was a misunderstanding.

```py
self._ext_separate_shader_objects_enabled = False
# if self.gl_api == "gl": 
#     have_ext = gl.gl_info.have_extension("GL_ARB_separate_shader_objects") 
#     self._ext_separate_shader_objects_enabled = self.gl_version >= (4, 1) or have_ext 
```

**Comment by pvcraven** [comment]
This is what I've got now, still hanging:

        self._ext_separate_shader_objects_enabled = False
        # if self.gl_api == "gl":
        #     have_ext = gl.gl_info.have_extension("GL_ARB_separate_shader_objects")
        #     self._ext_separate_shader_objects_enabled = self.gl_version >= (4, 1) or have_ext

**Comment by pvcraven** [comment]
Related? https://developer.apple.com/forums/thread/690849

**Comment by einarf** [comment]
It doesn't explain why it doesn't hang in 2.6 though. We at least have some information to go on now.

**Comment by pvcraven** [comment]
I wonder why do sprite_list.draw() calls seem to work find, but not sprite.draw() calls?

**Comment by einarf** [comment]
Could there possibly be something in pyglet triggering this issue? I'm still puzzled by this issue.

**Comment by pvcraven** [comment]
Non working dev branch trace:
[development_branch_trace.txt](https://github.com/pythonarcade/arcade/files/9541226/development_branch_trace.txt)

**Comment by pvcraven** [comment]
Working maintenance branch trace:
[maintenance_run.txt](https://github.com/pythonarcade/arcade/files/9541238/maintenance_run.txt)

**Comment by pvcraven** [comment]
Try 2 for logging maintenance branch:
[maintenance_run.txt](https://github.com/pythonarcade/arcade/files/9541291/maintenance_run.txt)

**Comment by pvcraven** [comment]
These runs are with the mac_killer program I recently added.

[vers_26.txt](https://github.com/pythonarcade/arcade/files/9542835/vers_26.txt)
[vers_27.txt](https://github.com/pythonarcade/arcade/files/9542836/vers_27.txt)

**Comment by einarf** [comment]
Great. I will try to compare and possibly add lots of logging.

**Comment by pvcraven** [comment]
This sample code now runs with today's dev branch on my mac.

**Comment by einarf** [comment]
Awesome! 🎉 

Let's close this?

**Comment by pvcraven** [comment]
Closing. Yay!
