### ISSUE TITLE
Installation instructions for PyCharm need updating

### ISSUE THREAD

**Issue by pvcraven** [pythonarcade/arcade#1321]
Installation instructions for PyCharm refer to 'requirements.txt' which is no longer a thing. This needs updating.

**Comment by cspotcode** [comment]
https://github.com/pythonarcade/template also needs to be updated.

**Comment by einarf** [comment]
It's fine to mentioned this as a simple way to store dependencies. However, the pycharm venv document is so out of date I ended up archiving it for now.
