### ISSUE TITLE
Sprite loading error (file not found)

### ISSUE THREAD

**Issue by LukovDev** [pythonarcade/arcade#1351]
## Bug Report
Traceback (most recent call last):
  File "E:\KUKOVDEV\SURVAL\Main.pyw", line 47, in <module>
    Main = Main()
  File "E:\KUKOVDEV\SURVAL\Main.pyw", line 36, in __init__
    sprite = arcade.Sprite("data/sprites/blocks/env/snow.png")
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\arcade\sprite.py", line 256, in __init__
    self._texture = load_texture(
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\arcade\texture.py", line 504, in load_texture
    file_name = resolve_resource_path(file_name)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\arcade\resources\__init__.py", line 39, in resolve_resource_path
    raise FileNotFoundError(f"Cannot locate resource : {path}")
FileNotFoundError: Cannot locate resource : data\sprites\blocks\env\snow.png

## System Info

Arcade 2.6.16
vendor: ATI Technologies Inc.
renderer: AMD Radeon(TM) Vega 3 Graphics
version: (4, 6)
python: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
platform: win32

### Actual behavior:
The path to the file relative to the one being launched is correct, but an error occurs. But if you enter the full path in the file system (C:/folder1/folder2/sprite.png) this error does not occur

### Expected behavior:
The sprite should load without specifying the full path
(folder2/sprite.png)

### Steps to reproduce/example code:
I use Arcade 2.6.16 and just write:
sprite = arcade.Sprite("folder/sprite.png")

### What should be added/changed?
--

### What would it help with?
--

## Documentation request:
--

### What documentation needs to change? 
--

### Where is it located?
--

### What is wrong with it? How can it be improved?
--

**Comment by LukovDev** [comment]
Maybe I'm doing something wrong. If this is the case, help how it can be fixed

**Comment by LukovDev** [comment]
It turned out that everything was done correctly, just for an unknown reason PyCharm gives an error because of which the game does not start.
Run it through the console and everything will work correctly

**Comment by pushfoo** [comment]
> But if you enter the full path in the file system (C:/folder1/folder2/sprite.png) this error does not occur

> Run it through the console and everything will work correctly

This sounds like an issue with the working directory. Additional ways of making it work include: 
* [add a resources directory via the arcade API](https://github.com/pythonarcade/arcade/blob/maintenance/arcade/resources/__init__.py#L45)
* Edit the PyCharm run config or project settings to set working directory
