### ISSUE TITLE
Unify `make.bat` and `make.sh`

### ISSUE THREAD

**Issue by Jayman2000** [pythonarcade/arcade#1353]
### What should be added/changed?

`make.bat` has more features than `make.sh`. I propose replacing both of them with a single Python script.

### What would it help with?

It would ensure that the build script has the same number of features regardless of which platform it’s being run on. It would allow instructions to be simplified (you wouldn’t have to say “If you’re on Windows, run `make.bat`. If you aren’t, run `make.sh`.).

**Comment by einarf** [comment]
Closing this and hooking it to https://github.com/pythonarcade/arcade/issues/995 so we keep that as a visible suggestion.
