### ISSUE TITLE
Tiled Map Editor tilesheet animation doesn't function properly

### ISSUE THREAD

**Issue by JGneiting** [pythonarcade/arcade#1362]
## System Info

Arcade 2.6.16
-------------
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce GTX 1660/PCIe/SSE2
version: (4, 6)
python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
platform: win32

### Actual behavior:

When arcade loads a map created with Tiled map editor, animations created from a tilesheet based on a single image do not play, only animations based on a collection of images.

### Expected behavior:

Loading a map from Tiled should play both types of animation, those based on images combined in a tilesheet and those based on separate image files.

### Steps to reproduce/example code:

[Example.zip](https://github.com/pythonarcade/arcade/files/9866660/Example.zip)

From the Example.zip file, run main.py, this will demonstrate the issue.
The arrow on the right spins as expected, while the one on the left does not.
Opening the ExampleMap.tmx in Tiled shows a map where both arrows are animated properly.

**Comment by Cleptomania** [comment]
Just now had some time to look into this. This definitely appears to be a bug with pytiled-parser. I've opened an issue there and will detail anything I find there. I'll update here with a resolution whenever I have one.

Right now it seems like this can probably be fixed without any updates to Arcade itself, however it will definitely require a patch version of pytiled-parser. For Arcade, this means you won't automatically get the new version of pytiled-parser likely until Arcade 2.7.0. You can explicitly install the new version of pytiled-parser(Once I get this fixed and get the release out of course) alongside Arcade 2.6.16(pip will complain about the version being incompatible but it will be fine).

**Comment by Cleptomania** [comment]
Ignore the above comment. Upon deeper investigation this is an issue in how Arcade loads the images from the pytiled-parser data. Putting this on the roadmap to be fixed in 2.7.
