### ISSUE TITLE
Simplifying Sprite

### ISSUE THREAD

**Issue by Cleptomania** [pythonarcade/arcade#1370]
There has been much discussion on Discord surrounding trimming down the `Sprite` class. In general, this idea has been viewed favorably, but there has been a lot of ideas floated around of the best approach to this and what exactly should be done.

As of right now, the general idea sits at these three classes to start with. Other things could be broken off or added/removed as seen fit later on, but this is basic idea right now:

`SimpleSprite` -> `Sprite` -> `BoundarySprite`

`SimpleSprite` gives us the bare minimum for drawing a texture on the screen. Basic position(maybe rotation and color included at this level, but perhaps those get included at `Sprite`), sprite list/texture referencing. Basically the bare minimum for drawing a sprite.

`Sprite` is still a bit up in the air what stays here, and what goes to `SimpleSprite` or `BoundarySprite`. For sure position  and texture related stuff moves to `SimpleSprite`. The current plan would be for the `boundary_xxx` fields to move to `BoundarySprite`. Some things in the air here are the pymunk handle, the properties dictionary, physics engine handle, `change_x/y`, etc. We could have some of these things stay in the initial breakup and move them into specialized subclasses later.

`BoundarySprite` receives all of the `boundary_bottom`, `boundary_top`, etc fields from `Sprite` and replaces it for use in the Platformer physics engine and Tiled integration. There could possibly be an argument for `change_x/y` to be at this level, personally I think they're fine in `Sprite`.

The real goal here is trimming unnecessary fat from places it doesn't need to be. If a game never makes use of the Boundary fields, then it shouldn't need to have them for all 500,000 sprites it creates for example. Having the core pieces pulled into simpler classes also makes things like any potential native optimizations in the future easier, as well as general maintenance of the codebase being easier to navigate.

**Comment by einarf** [comment]
Also `PymunkSprite` that will contain the Pymunk data class used by the PymunkPhysicsEngine. Right now this proprety is `None` by default, but will be created when you access it the first time. It consumed an enomrous amount of memory in 2.5 and earlier.

* Can we use mixins or is that too complicated?
* We also talked about using `__slots__` to save memory, but I don't remember if this caused complications
* To accept any of thse changes there should at the very least be a **measureable** improvement.

**Comment by einarf** [comment]
We've spit up sprite now and can consider doing what was mentioned here.

**Comment by Cleptomania** [comment]
I think this is in a relatively finished state for Arcade 3.0. We haven't split-off the Pymunk stuff, but I think making BasicSprite available for more advanced users to build a custom Sprite off of is enough to call this done for now. If we feel the need to split-off pymunk we can handle that in it's own issue.
