### ISSUE TITLE
better "in" operator for SpriteLists

### ISSUE THREAD

**Issue by alejcas** [pythonarcade/arcade#1377]
Hi just checking this before doing any PR:

Today the IN operator using SpriteList will iterate over the entire list using the `__iter__` magic method having O(n) instead of a better O(1).

```python

l = arcade.SpriteList()
s = arcade.Sprite()

exists = s in l  # this will iterate potentially over the entire sprite list
```

Instead SpriteList should implement `__contains__` magic method with this code:

```python
def __contains__(self, sprite: Sprite):
    return sprite in self.sprite_slot  # sprite_slot is a dict so this lookup is O(1)
```
This way spritelist lookup is much faster.

Plus this is indeed what `SpriteList.append` does:
https://github.com/pythonarcade/arcade/blob/development/arcade/sprite_list/sprite_list.py#L599

**Comment by einarf** [comment]
Nice find. Definitely go for it 👍 

I'd add 100-500k sprites and profile it to be sure. There's probably a difference, but it's nice to get some rumbers.

**Comment by alejcas** [comment]
Merged

**Comment by alejcas** [comment]
> Nice find. Definitely go for it 👍
> 
> I'd add 100-500k sprites and profile it to be sure. There's probably a difference, but it's nice to get some rumbers.

Should be way faster when the list is big and you try to check the last added element

**Comment by einarf** [comment]
Thanks again for this. Local test with 100k sprites shows that 1000 `in` opreators use 1.25 second while the new operator is practically free. This also makes adding sprite to list a little bit faster.

That's pretty amazing results for such a small thing. This was somthing in missed during the last SpriteList rewrite.
