### ISSUE TITLE
Feature Request: get_sprites_at_rect

### ISSUE THREAD

**Issue by alejcas** [pythonarcade/arcade#1384]
### What should be added/changed?
A method to retrieve sprites that collides with a rect (left, right, bottom, top).

`arcade.get_sprites_at_rect(rect: Tuple[int, int, int, int], spritelist: arcade.SpriteList) -> List[arcade.Sprite]`

rect should be (left, right, bottom, top)

As discussed in discord (just copying einarf text here):

- Add a simpler method in spatial hash that takes the min/max xy values representing the box: `get_objects_for_rect`?
- Then if no spatial hashing you can call `are_polygons_intersecting`? 

### What would it help with?
Nowadays if you want a similar behavior you need to create a Sprite with a hitbox representing this rect and then check collisions with this sprite. But that could lead to a scenario where you are increasingly adding Sprites just to get collision detection and that would increase memory consumption.

In my case that would lead to a x2 sprites...

**Comment by eschan145** [comment]
Sprites have a `collides_at_point` method. It takes a tuple of [`x`]() and [`y`]() coordinates. It just uses the `are_polygons_intersecting` method. This could be used for the `get_sprites_at_rect`.

**Comment by einarf** [comment]
> Sprites have a `collides_at_point` method. It takes a tuple of `x` and `y` coordinates. It just uses the `are_polygons_intersecting` method. This could be used for the `get_sprites_at_rect`.

That won't cover this use case.

https://github.com/pythonarcade/arcade/blob/a3de98296d197374475a60ca859c14659e821e6c/arcade/sprite.py#L1139-L1149

**Comment by einarf** [comment]
https://github.com/pythonarcade/arcade/issues/1556

**Comment by einarf** [comment]
https://github.com/pythonarcade/arcade/pull/1567

**Comment by alejcas** [comment]
I don’t see anything in #1567 related to “get sprites at rect”
Am I missing something?

**Comment by einarf** [comment]
> I don’t see anything in #1567 related to “get sprites at rect”
> Am I missing something?

I will be in there. I just haven't pushed up everything yet 😄

**Comment by einarf** [comment]
Spatial hash method is working at least. Just need a collision method now.
![sprites_in_rect](https://user-images.githubusercontent.com/5418180/220513433-a03f08f9-8bd4-4b42-a3da-7fd30b51df99.gif)

**Comment by einarf** [comment]
`arcade.get_sprites_in_rect((l, r, b, t), spritelist)` merged into development.

**Comment by alejcas** [comment]
Can I see the collision method? Is it somewhere?

**Comment by alejcas** [comment]
> Can I see the collision method? Is it somewhere?

I saw it! This is great!!!
