### ISSUE TITLE
SpriteSolidColor is not of the color, one may expect (I am beginner at game engines)

### ISSUE THREAD

**Issue by misolietavec** [pythonarcade/arcade#1403]
## System Info

Arcade 2.7.1.dev4
-----------------
vendor: Intel
renderer: Mesa Intel(R) HD Graphics 530 (SKL GT2)
version: (4, 6)
python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]
platform: linux

### Actual behavior:
Changing color from red to blue by keypress causes change from red to black in draw(), or changing from red to yellow is rendered as constantly red. 

### Expected behavior:
I expect the red sprite to be drawn by red color, blue by blue color, etc.  If not so, why it is called `SpriteSolidColor`?

### Steps to reproduce/example code:
```python
import arcade


class Game(arcade.Window):
    def __init__(self, width, height, title):
        super().__init__(width, height, title)
        self.background_color = arcade.color.SEA_BLUE
        self.rect = None
                 
    def setup(self):
        self.clear()
        self.rect = arcade.SpriteSolidColor(200, 120, arcade.color.RED)


    def on_key_press(self, key, _modifiers):
        if key == arcade.key.M:
            if self.rect.color == arcade.color.RED:
                self.rect.color =  arcade.color.YELLOW
            else:
                self.rect.color =  arcade.color.RED
        print(self.rect.color)

        
    def on_draw(self):
        self.clear()
        self.rect.draw()


game = Game(640, 480, "SpriteSolidColor")

game.setup()
arcade.run()    
```

### What should be added/changed?
I consider this behaviour very confusing. It gives me many headaches debugging SameGame (it goes straightforward in pyp5js, p5.js and pyscript, also in Ursina). 

### What would it help with?
Certainly, if Arcade is targeted at education, it should have intuitive, simple behaviour.

**Comment by einarf** [comment]
I have changed this behavor in the `texture_revamp` branch that hopefully will be merged soon.

We allocate a single white texture for all of these sprites. The color property of the sprite will then be multiplied with this texture. It's what most users would expect as you describe above.

**Comment by einarf** [comment]
Will close this when the branch is merged.

**Comment by misolietavec** [comment]
OK

**Comment by einarf** [comment]
You can do the following: `arcade.SpriteSolidColor(200, 120, arcade.color.WHITE)`

then the color propery should work as expected. It will make a sprite with a white texture and the color will be multiplied by this texture.

**Comment by einarf** [comment]
I changed it so that `SpriteSolidColor` also don't take up any texture memory regadless of how many or how large your sprites are.

**Comment by misolietavec** [comment]
Works like charm in `texture_revamp` branch.

**Comment by einarf** [comment]
Thanks for testing! Will close this when merged to development branch. It will be in 2,7 release.
