### ISSUE TITLE
Sprite.texture naively uses Sprite.scale not Sprite.scale_xy [2.7.1.dev5+]

### ISSUE THREAD

**Issue by DragonMoffon** [pythonarcade/arcade#1408]
The sprite was recently updated to use a 2D scale attribute. However, the `Sprite.scale` property has been updated to use the width scale, but updating textures was never adjusted.

If you set `Sprite.scale_xy = (-1, 1)` and then set `Sprite.texture` the new texture will be improperly flipped vertically as well as horizontally. In a similar vein if you set `Sprite.scale_xy = (1, -1)` and then set `Sprite.texture` the new texture will not be flipped vertically.

As seen at https://github.com/pythonarcade/arcade/blob/35e9b0a99c2dc09760696e08e52dbbda2d96a07d/arcade/sprite.py#L898-L917.

An update to the code could look like
```python
@texture.setter
    def texture(self, texture: Texture):
        """Sets texture by texture id. Should be renamed but keeping
        this for backwards compatibility."""
        if texture == self._texture:
            return

        if not isinstance(texture, Texture):
            raise ValueError(f"The 'texture' parameter must be an instance of arcade.Texture."
                             f"It is an instance of '{type(texture)}'.")
        assert isinstance(texture, Texture)

        self.clear_spatial_hashes()
        self._point_list_cache = None
        self._texture = texture
        self._width = texture.width * self.scale_xy[0]
        self._height = texture.height * self.scale_xy[1]
        self.add_spatial_hashes()
        for sprite_list in self.sprite_lists:
            sprite_list.update_texture(self)
```

**Comment by einarf** [comment]
Another related issue with scale : https://github.com/pythonarcade/arcade/pull/1379

**Comment by einarf** [comment]
Fixed in development
