### ISSUE TITLE
Make it possible to load TileMap without a Window

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#1411]
### What should be added/changed?

Make it possible to use arcade.load_tilemap without having an active arcade.Window.

### What would it help with?
This used to work. I have some tests in my CI which load the game tilemaps and runs some tests. However, when I went from 2.6.16 to 2.7.1.dev3, those tests started crashing because TileMap calls arcade.get_window to get a texture atlas. I tried passing in a texture atlas to TileMap, but then the atlas itself calls arcade.get_window.

**Comment by einarf** [comment]
Fixed in development branch
