### ISSUE TITLE
PyArcade is not working inside a VMWare VM

### ISSUE THREAD

**Issue by Annakan** [pythonarcade/arcade#1421]
## System Info

Arcade 2.6.16
-------------
vendor: VMware, Inc.
renderer: SVGA3D; build: RELEASE;  LLVM;
version: (3, 3)
python: 3.10.8 (main, Dec  1 2022, 10:40:48) [GCC 12.2.0]
platform: linux

### Actual behavior:

In most demo or examples only the background is painted, and nothing is rendered, although the game is running and no error is displayed.
Some but few functionality are working, in the bouncing shape example only the lines are rendered, not the circles or rectangles.

To reproduce, one can run https://api.arcade.academy/en/latest/examples/shapes.html#shapes-slow in any VMWare workstation since Version 15 (it has been reproduced in 15, 16 and even 17 that is recently out and that extended OpenGL support to 4.3).

Most other examples just result in the background being rendered like : 

* https://api.arcade.academy/en/latest/examples/procedural_caves_cellular.html#procedural-caves-cellular
* https://api.arcade.academy/en/latest/examples/sprite_no_coins_on_walls.html#sprite-no-coins-on-walls

but the lightning demo works :

https://api.arcade.academy/en/latest/examples/light_demo.html#light-demo

### Expected behavior:

100% of the demos and functionality working ?

### Steps to reproduce/example code:

Install a linux image (I use Arch/Manjaro with KDE) in VMWare Workstation (and probably player and is free) and run the aforementioned demos.

I don't know yet if the behavior is the same with a window VM

**Comment by einarf** [comment]
Werid. I'm curious if ending the `on_draw()` method with `self.ctx.flush()` and/or `self.ctx.finish()` makes a difference.

**Comment by Annakan** [comment]
Just tested with one and both on the boucingshape exemple and no difference.
Nor with the procedural cave cellular automata example :(

**Comment by Annakan** [comment]
I suspect the problems comes from pyglet (or that pyglet triggers the problem), since I tried to execute https://codeboje.de/Effect-Animation-with-Pyglet/ demo and had the same result : an initialized responsive empty window ...

**Comment by einarf** [comment]
Yup. It can definitely be related to something in pyglet. Have you tried headless/EGL?

**Comment by einarf** [comment]
Also I think an issue should be created in the pyglet project here? If it really is a problem in pyglet there won't be much we can do in this project.

**Comment by Annakan** [comment]
Ok I found the trigger for that bug/behavior.

I will open a pyglet bug but I suspect this is an underlying implementation bug, I don't know enough OpenGL to be sure.

This buggy behavior is triggered by anti-aliasing being set to True.

So in every demo adding `antialising=False` to the window init solves the problem.

However, the true trigger is in the window init code with anti-aliasing set to True in arcade/application.py

```python
        if antialiasing:
            try:
                config = pyglet.gl.Config(
                    major_version=gl_version[0],
                    minor_version=gl_version[1],
                    opengl_api="gl",
                    double_buffer=True,
                    sample_buffers=1,
                    samples=samples,
                )
```   

**sample_buffers=1** is the culprit
simply putting  sample_buffers=**2** (or more) makes the bug disappear.

Now, why it affects filled rectangles and circles and most other things bur not lines nor text is beyond my ogl skills.

The same bug is triggered in native pyglet by setting the same **sample_buffers=1** parameter in the OpenGL config.

I will need to monkeypatch the window init to override that if I need antialising.

**Comment by Annakan** [comment]
As I feared the problems run deeper.
Technically VmWare (and AFAIK virtualbox) should fully support `OpenGL 3.3 Core` that is the level Arcade requires(https://api.arcade.academy/en/latest/gl/index.html).

But even without **antialiasing** or with **sample_buffers=2+** there are functionality not working properly in arcade (I need to test lower level library), for instance "layers" (SpriteList ordered in a scene) do not seem to work, the first layer is drawn, whatever it is, others not.
(it is more complicated, at times I was able to have one layer and another "player"/ one sprite layer to be drawn, at other times only one layer was drawn, even though collision keep working (but those are handled at the python level aren't they ?).

I will look into reproducing this on a small example with a lower level library if I have the time but for people needing this, they need to be aware that things are not working as smoothly as in native .

**Comment by caffeinepills** [comment]
In your VMWare options for the VM, do you have "Accelerate 3D graphics" checked? If so, uncheck it.

**Comment by Annakan** [comment]
Sorry for the delay.

Good call, disabling 3D acceleration (and thus I suppose switching to Pure software Mesa ) makes everything work fine....Performance seems to suffer but I lack a reference point to measure how much.

```bash
❯ glxinfo | grep 'OpenGL version'
OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.2.4```

**Comment by einarf** [comment]
It's hard to know what could be the issue here. Definitely at least disable antialiasing for the window framebuffer. It's not well supported in VMs usually. Separate framebuffers with MSAA is better supported and the reason most modern games don't usually render directly to the window framebuffer any more.

**Comment by pvcraven** [comment]
Going to close due to inactivity. Please reopen if there's more info or a brainstorm on how we can support this better.
