### ISSUE TITLE
Switch color constants to RGBA

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1422]
### What should be added/changed?

- [X] Make all color constants in `arcade.color` into RGBA constants
- [X] Make all color constants in `arcade.csscolor` into RGBA constants
- [x] Add a `TRANSPARENT_BLACK` constant to `arcade.color`

### What would it help with?
1. Provide better immediate-term support for sprite generation with Pillow or drawing into contexts
2. Set the stage for future sprite generation API improvements
3. Make tests for #1342 and other functionality cleaner

This is also a chore einarf and Clepto agreed should be done months ago

**Comment by einarf** [comment]
I have already made them into RGBA in my branch
https://github.com/pythonarcade/arcade/blob/texture-revamp/arcade/color/__init__.py
https://github.com/pythonarcade/arcade/blob/texture-revamp/arcade/csscolor/__init__.py

**Comment by pushfoo** [comment]
How long till that gets merged? I'd like to add some more constants to `arcade.color` and revamp the docstring for `arcade.csscolor` afterward.

**Comment by einarf** [comment]
Think we can get away with cherry picking that commit into development. I can look at that a bit later today

**Comment by einarf** [comment]
https://github.com/pythonarcade/arcade/pull/1423
