### ISSUE TITLE
Add gray checkerboard background under color swatches

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1429]
### What should be added/changed?
Update the color table generation with a two-tone gray checkerboard underneath the transparent or partially opaque color swatches.

I wasn't able to get this working in #1428 due to alignment issues when trying to use Z-indexed divs.

### What would it help with?
`TRANSPARENT_BLACK` is currently rendered as a black border around a rectangle filled with the current background color of the page. This may be confusing for beginners.

Implementing this change would make the transparency of all colors easier to understand since the checkerboard pattern is an intuitive indicator for the absence or transparency of pixel data in an RGBA image.

**Comment by sabadam32** [comment]
Fixed by PR  https://github.com/pythonarcade/arcade/pull/2007 in #1878
