### ISSUE TITLE
Anti-aliasing does not seem to work on Windows

### ISSUE THREAD

**Issue by w568w** [pythonarcade/arcade#1432]
## Bug Report

`antialiasing` seems to have no effect even on a simple drawing task.

## System Info

The operating system is `Windows 10 22H2`, with AMD integrated graphics.
```
Arcade 2.7.1.dev8
-----------------
vendor: ATI Technologies Inc.
renderer: AMD Radeon(TM) Graphics
version: (4, 6)
python: 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
platform: win32
```

#### 1. With default parameters:
![image](https://user-images.githubusercontent.com/8389787/206623055-8d5e1069-4bea-41e2-9af9-2f5514b1e54a.png)
#### 2. With `samples=16`:
![image](https://user-images.githubusercontent.com/8389787/206623120-dff4f28c-66bf-48ec-a54d-0a4be2d4dbed.png)
#### 3. With `antialiasing=False`:
![image](https://user-images.githubusercontent.com/8389787/206623207-4d290825-2ac9-4e94-87f3-9839f74c7335.png)

They all look the same. **Also, there is no info/warning/error output during running**.

### Expected behavior:

The program fragment comes from issue #1040, and the expected line should look like "the descending line" there.

### Steps to reproduce/example code:

```python
import arcade


class MyGame(arcade.Window):
    def __init__(self, width, height, title):
        super().__init__(width, height, title) # parameters were changed here
        arcade.set_background_color(arcade.color.WHITE)

    def on_draw(self):
        arcade.start_render()
        arcade.draw_line(self.width, 0, 0, self.height, (0, 0, 0))


MyGame(200, 150, 'test')
arcade.run()

```

**Comment by einarf** [comment]
hmm weird. I will test on my AMD laptop. Is this a new issue in 2.7?

**Comment by w568w** [comment]
> Is this a new issue in 2.7?

No. I have reproduced the bug in the lastest stable version, `2.6.13`.

**Comment by w568w** [comment]
Maybe the problem has nothing to do with the graphic card model, since it also appears on NVIDIA GPU:

```
Arcade 2.7.1.dev8
-----------------
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
version: (4, 6)
python: 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
platform: win32
```

---

I am not so familiar with `pyglet`, but I find that `screen.get_best_config(config)` is returning a config where `config.sample_buffers` and `config.samples` are both `0` here:

https://github.com/pythonarcade/arcade/blob/48a9ce520c8c56f55022aa73432fdb193920c2f0/arcade/application.py#L128

Is this an expected behavior?

**Comment by einarf** [comment]
I can confirm this is definitely a window issue. `get_best_config` seems to ignore the multisample values returning 0 values. I think this started happening when we disabled the shadow context/window.

**Comment by einarf** [comment]
With shadow context I get MSAA enabled.
![bilde](https://user-images.githubusercontent.com/5418180/208262571-7d69c68c-50dc-40a9-8caf-d314e55fa6d1.png)

We can experiment by enabling it for anything other than Mac OS. This is how it used to be.

**Comment by einarf** [comment]
Fixed in development branch
