### ISSUE TITLE
Use **kwargs in arcade.Sprite.__init__ so signature can be preserved in subclasses

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#1433]
### What should be added/changed?

Either just add an unused **kwargs to arcade.Sprite.__init__, or use **kwargs exclusively and pop values from it, with no explicit arguments.

### What would it help with?

It would make it much easier to subclass arcade.Sprite without breaking the Liskov substitution principle of the __init__ method. For example, say you want to create a subclass of arcade.Sprite called "Enemy", and you want to add things like life, damage, etc to it. Currently, you cannot add new arguments (args/kwargs) without breaking Liskov principle (changing signature of __init__ method). If there was a **kwargs there, you could just do kwargs.pop("life") before passing in kwargs to super().__init__ (i.e., you could peel off kwargs in child classes before calling parent classes).

If arcade.Sprite used **kwargs only, with no explicit args/kwargs, you could also have the freedom to fix some values. For example, create a subclass "KnightSprite" which explicitly sets texture/filename to use the graphics for a knight. Currently, filename/texture are explicit parameters to arcade.Sprite.__init__, so all subclasses thereof must have those parameters as well to preserve the signature.

**Comment by pushfoo** [comment]
I agree this approach can be useful, but I'm not sure how it fits into the prior discussion around simplifying `Sprite` on GitHub (#1370) and discord.

**Comment by bunny-therapist** [comment]
I don't see any contradiction. Actually, I feel like it would even make it easier. If you are going to be making several Sprite classes which inherit from each other, this approach would allow you to keep the same __init__ signature. Otherwise I believe it would be impossible - I mean, if you need to, e.g., pass boundary_top to BoundarySprite constructor, but not to Sprite or SimpleSprite constructor, then you would end up with different signatures unless you adopted the approach suggested here.

**Comment by alejcas** [comment]
adding a **kwargs at the end of parameters list would do everything you need

**Comment by pushfoo** [comment]
> bunny-therapist:
> I don't see any contradiction.

I agree that adding `**kwargs` at the end of `__init__`'s arguments seems like the best way to approach the problem you've outlined, and have even [used the same technique in one of my own projects](https://github.com/pushfoo/fontknife/blob/18bd20a6b0abff2105c207d9a7b555a55e37651b/fontknife/formats/common/__init__.py#L169-L205) for convenience.

However, to my understanding, simplifying the Sprite class is about more than reducing the weight or code complexity of the class. It is also a way to keep arcade useful as an educational tool by making sure its elements are beginner friendly, including for younger students.

The proposed changes will make working with `Sprite` more difficult for the beginner demographic. Correctly using `**kwargs` as proposed requires some understanding of keyword arguments and dictionaries. That may be difficult for some of the younger students, and will compound with the following problems that seem to arise when using this pattern:
* Autocomplete and inference features in IDEs break down
* Debugging becomes more difficult, especially as the inheritance hierarchy grows (Kivy widgets are a good example)

Some of these issues may be addressed with documentation and type annotation. However, type annotations put increased burdens on first time users, so I'm hesitant to make the proposed changes to the core classes of the framework without further consideration.
