### ISSUE TITLE
Uncleared contents during frame swap

### ISSUE THREAD

**Issue by BrettskiPy** [pythonarcade/arcade#1435]
## Bug Report
Swapping a view in fullscreen will cause flashing leftovers of the previous view along the border of the screen. 

![screen_flashing](https://user-images.githubusercontent.com/30988215/207523633-c6d37291-03d4-4dd4-9862-ab28df25024a.gif)

### System information
Arcade version: 2.7.1.dev8
OS: Windows 10

### Steps to reproduce

1: Use full screen in a view
2: Switch to a new view using `self.window.show_view()` 
3: Observe the flashing as seen in the gif. 

### Code I believe to be relevant
 ```python
class StoryView(arcade.View):
    def __init__(self):
        super().__init__()
        arcade.set_background_color(arcade.color.BLACK)
        self.camera_gui = arcade.Camera()
        self.background = arcade.load_texture("assets/main_menu/columns.jpg")

    def on_draw(self):
        self.clear()
        self.camera_gui.use()
        arcade.draw_lrwh_rectangle_textured(
            300, 0, self.window.width - 300, self.window.height, self.background
        )
``` 
And 
```python
class OtherView(arcade.View):
    def __init__(self):
        super().__init__()
        arcade.set_background_color(arcade.color.BLACK)
        self.camera_gui = arcade.Camera()
        self.background = arcade.load_texture("assets/story/happy_mort.jpg")

    def on_draw(self):
        self.clear()
        self.camera_gui.use()
        arcade.draw_lrwh_rectangle_textured(
            300, 0, self.window.width - 300, self.window.height, self.background
        )
```
### Conversation from Einarf in help channel 3
Per Einarf - "I thought I fixed the `clear()` method. Optionally just specify a viewport that covers the entire screen when you clear it.`0, 0, w, h` ... but I thought I changed it to clear the entire screen unless you pass in a viewport. Because this is the lesser evil. What you are seeing is the front and back buffer showing uncleared contents as the frames are swapping"

**Comment by einarf** [comment]
Yup. The issue looks horrific, but its probably just about scissor box and `clear()`

Clearing with scissor box enabled by default is nice because your background color only affects the scissor area. However.. if you have several views and  keep changing viewports and scissor boxes you will end up witht he problem described above.

It's probably better to change things around. `clear` will always clear everything UNLESS you pass in a viewport.

**Comment by einarf** [comment]
Try again with latest dev branch

**Comment by BrettskiPy** [comment]
Upgraded from 2.7.1.dev8 to 2.7.1.dev9 and the issue has been resolved. Thank you.
