### ISSUE TITLE
Split large test files to improve readability

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1437]
### What should be added/changed?
Many of the current test modules (such as  [`test_sprite.py`](https://github.com/pythonarcade/arcade/blob/development/tests/unit2/test_sprite.py)) cram too much functionality into single files and functions.

As discussed on discord, we should do the following:
- [ ] Split large single-file modules into folders, with possible sub-folders for objects with numerous complicated properties
- [ ] Move tests for specific functionality into clearly labelled files within appropriate  folders (`test_sprite_scale_xy`)
- [ ] Split very large single-function tests into smaller clearly labelled functions when it increases readability of test results
- [ ] Use limited fixtures where appropriate, avoiding complicated fixture hierarchies  when possible

These tasks will improve the readability of CI output, which is something [other contributors](https://github.com/pythonarcade/arcade/pull/1431#issuecomment-1340877924) and I have had difficulties with before.

We should try to avoid complicated fixtures to keep writing tests accessible to less experienced contributors.

**Comment by einarf** [comment]
Since the task have been lingering for 2 years I will close (considering it's also a "low bar" task). I will probably have to revamp all the sprite tests when adding support for headless testing anyway.
