### ISSUE TITLE
Consolidate tests into clear unit & integration folders

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1438]
### What should be added/changed?
Per discord discussion, the following changes should be made as time is available:
- [x] `unit` and `unit2` should be consolidated
- [x] add an `integration` folder if necessary 
- [x] move the tests in the gui, tiled, tilemap_tests, etc folders into the appropriate consolidated folders

This would make the test hierarchy more legible to everyone, including less experienced contributors.

**Comment by einarf** [comment]
https://github.com/pythonarcade/arcade/pull/1614
