### ISSUE TITLE
Add support for compressed hit box cache

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1448]
### What should be added/changed?
Add support for saving and loading a compressed version of the [hitbox cache](https://github.com/pythonarcade/arcade/blob/development/arcade/cache/hit_box.py).

### What would it help with?
einarf pointed out that [the pre-generated hitbox cache file for the built-in textures is surprisingly large at ~230kb in size](https://github.com/pythonarcade/arcade/blob/texture-revamp/arcade/resources/cache/hit_box_cache.json). Adding support for compressed texture loading may help with #1159, especially for projects with lots of assets.

**Comment by einarf** [comment]
Already fixed.
