### ISSUE TITLE
Documentation - example has wrong code snippet

### ISSUE THREAD

**Issue by dmohorcic** [pythonarcade/arcade#1470]
### What documentation needs to change?

In the examples for Camera Use the example for [Move with a Scrolling Screen - Margins](https://api.arcade.academy/en/latest/examples/sprite_move_scrolling_box.html#sprite-move-scrolling-box) has the same code as [Move with a Scrolling Screen - Centered](https://api.arcade.academy/en/latest/examples/sprite_move_scrolling.html#sprite-move-scrolling).

### Where is it located?

It is located here: https://api.arcade.academy/en/latest/examples/sprite_move_scrolling_box.html#sprite-move-scrolling-box

### What is wrong with it? How can it be improved?

The incorrect code snippet is displayed. Currently it uses [sprite_move_scrolling.py](https://github.com/pythonarcade/arcade/blob/development/arcade/examples/sprite_move_scrolling.py), but it should use [sprite_move_scrolling_box.py](https://github.com/pythonarcade/arcade/blob/development/arcade/examples/sprite_move_scrolling_box.py)

**Comment by Ibrahim2750mi** [comment]
@dmohorcic The two examples you mentioned use different code for the function `scroll_to_player` to serve the purpose of, to move with a scrolling screen. Can you recheck on the website if thats what you wanted to point out?

**Comment by dmohorcic** [comment]
@Ibrahim2750mi yes, the code on the website is the same for both examples, but should be different.

The example for camera with margins has the wrong code. I did not state that clearly in my issue.

**Comment by Ibrahim2750mi** [comment]
@dmohorcic The code displayed on both the pages are different. You can even see this with number of lines of code in both the pages i.e [Move with a Scrolling Screen - Margins](https://api.arcade.academy/en/latest/examples/sprite_move_scrolling_box.html#sprite-move-scrolling-box) has 229 lines of code and [Move with a Scrolling Screen - Centered](https://api.arcade.academy/en/latest/examples/sprite_move_scrolling.html#sprite-move-scrolling) has 193 lines of code. Major difference is in the `scroll_to_player` function. So I don't see how the code is same for both the examples. Are you pointing to a specific part in the code that should be different but is not?

**Comment by dmohorcic** [comment]
@Ibrahim2750mi ah yes, I see that I am wrong. The thing that made me think that is the code for sprite_move_scrolling_box.py uses next line:
"""
...
If Python and Arcade are installed, this example can be run from the command line with: python -m arcade.examples.sprite_move_scrolling
"""
which runs the wrong example code.

**Comment by pvcraven** [comment]
A fix to the incorrect comment is currently in the 2.7 branch. Going to close.
