### ISSUE TITLE
UIFlatButton cut text

### ISSUE THREAD

**Issue by eruvanos** [pythonarcade/arcade#1482]
csdaniel reported that the UIFlatButton cuts text:
https://discord.com/channels/458662222697070613/1067536374682628197/1067550222420545677

The bug can not be reproduced at the moment. A simple example works:

```
import arcade
from arcade import Window
from arcade.gui import UIManager


class MyWindow(Window):

    def __init__(self):
        super().__init__()

        self.manager = UIManager()
        self.manager.enable()

        self.button = arcade.gui.UIFlatButton(text='pleasecutme',)
        self.button.center_on_screen()
        self.manager.add(self.button)

    def on_draw(self):
        arcade.start_render()
        self.manager.draw()


if __name__ == '__main__':
    MyWindow().run()
```

**Comment by csd4ni3l** [comment]
latest arcade version from github + what arcade installs for pyglet(2.0.3)

**Comment by csd4ni3l** [comment]
i think it happens when you use width and height arguments. can you try that out?

**Comment by csd4ni3l** [comment]
(it worked with width and height arguments before, maybe its calculated incorrectly now and thats why it does it but i dont know)

**Comment by eruvanos** [comment]
@csd4ni3l please modify the example above so it reproduces the bug.

**Comment by csd4ni3l** [comment]
i will when i have time sorry

**Comment by csd4ni3l** [comment]
found the bug,its when using a style
without style:
![Screenshot from 2023-01-28 10-41-19](https://user-images.githubusercontent.com/96988024/215259462-20ff7276-2c84-4382-ae5d-a8e9f46d9f63.png)
with style:
![Screenshot from 2023-01-28 10-41-26](https://user-images.githubusercontent.com/96988024/215259477-90a1da56-a4ed-4475-b645-8348f8f3154d.png)

**Comment by csd4ni3l** [comment]
```py
import arcade
from arcade import Window
from arcade.gui import UIManager
button_style = {'normal': {'bg': (0, 150, 0, 255), 'font_color': (30, 30, 30, 255)}, 'hover': {'bg': (16, 179, 35, 255), 'font_color': (30, 30, 30, 255)}, 'press': {
    'bg': (0, 150, 0, 255), 'font_color': (30, 30, 30, 255)}, 'disabled': {'bg': (0, 150, 0), 'font_color': (30, 30, 30, 255)}}
class MyWindow(Window):

    def __init__(self):
        super().__init__()

        self.manager = UIManager()
        self.manager.enable()

        self.button = arcade.gui.UIFlatButton(text='pleasecutme',width=100,height=100,style=button_style)
        self.button.center_on_screen()
        self.manager.add(self.button)

    def on_draw(self):
        arcade.start_render()
        self.manager.draw()


if __name__ == '__main__':
    MyWindow().run()
```

**Comment by csd4ni3l** [comment]
more proof:
![Screenshot from 2023-01-30 17-13-03](https://user-images.githubusercontent.com/96988024/215531539-8f56f071-4763-406e-9259-47f76414c765.png)

**Comment by eruvanos** [comment]
> https://github.com/pythonarcade/arcade/issues/1482#issuecomment-1408908388

mh, this does not show a bug on my machine, I will try to find it :/
<img width="170" alt="image" src="https://user-images.githubusercontent.com/9437863/215736972-95cf11d6-eadf-4610-b9e5-b554ced226c0.png">

**Comment by csd4ni3l** [comment]
which pyglet and arcade version?
