### ISSUE TITLE
Camera scrolls in screenspace as opposed to projection-space [2.7.1.dev12]

### ISSUE THREAD

**Issue by DigiDuncan** [pythonarcade/arcade#1493]
## System Info
```
Arcade 2.7.1.dev12
------------------
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
version: (3, 3)
python: 3.11.0 | packaged by conda-forge | (main, Jan 16 2023, 14:12:30) [MSC v.1916 64 bit (AMD64)]
platform: win32
```

### Actual behavior:
All cameras move at the same speed when give the same `move()` command, despite their differing zoom levels.

### Expected behavior:
Cameras `move()` amount is scaled relative to it's current `scale`. (as it was pre-2.7)

### Steps to reproduce/example code:
https://gist.github.com/DigiDuncan/2f194def17db0c1d471f69da9179ee9a

**Comment by einarf** [comment]
@janscas if you wanted to take a look

**Comment by einarf** [comment]
The multiplication order was reversed in the new pyglet version. My hunch is that translation is multiplied wrong.

**Comment by alejcas** [comment]
Didn’t have the time today. I’ll try tomorrow

**Comment by alejcas** [comment]
Pyglet version?

**Comment by DigiDuncan** [comment]
> Pyglet version?

2.0.3

**Comment by alejcas** [comment]
@DigiDuncan can you provide any example in the arcade examples that is also not working? I can't run your code.

Error: ' 'ParallaxView' object has no attribute 'camera'

**Comment by alejcas** [comment]
Also I think parallax.py example works as expected...

**Comment by alejcas** [comment]
Besides what @einarf explained about pyglet changing the matrix multiplication orden, the last camera PR I submitted changed the way zoom works.

Maybe I broke it....

Before, the zoom was modifying the right and top of the projection matrix and also the view matrix by just setting a param called zoom.

**The problem with this is that changing the projection to view ratio will also produce a zoom. So setting the projection to view ratio to something like 0.5 (the projection is 1/2 smaller than the viewport) and also setting a zoom of 0.5 WILL NOT output a zoom of 0.5 but a much larger zoom... but the user was setting zoom=0.5 producing NOT the desired effect **

So I tried to correlate scale (effectively zoom) and the projection to view ratio so changing one or the other will output the same zoom effect.

The before code looked like this:

```python
# simplified code...
def _set_projection_matrix():
    right *= zoom
    top *= zoom
    self._projection_matrix = Mat4.orthogonal_projection(left, right, bottom, top, self._near, self._far)

def _set_view_matrix():
    result_position = Vec3(
        (result_position[0] / ((self.viewport_width * self._zoom) / 2)),
        (result_position[1] / ((self.viewport_height * self._zoom) / 2)),
        0
    )
    self._view_matrix = ~(Mat4.from_translation(result_position) @ Mat4().scale(Vec3(self._zoom, self._zoom, 1.0)))
```

With PR #1431 I directly correlated zoom level with projection to view ratio. So setting zoom (or scale) to 0.5 will reduce the projection to 1/2 of the view, producing the desired zoom effect.

Now the code looks more like this (notice how nor _set_projection_matrix or _set_view_matrix is affected by the zoom):

```python
# simplified code...

def scale(new_scale):
    sx, sy = new_scale
    left, _, bottom, _ = self._projection
    _, _, width, height = self._viewport
    # apply new scale
    self.projection = (left, width * sx, bottom, height * sy)   # ZOOM IS NOW HAPPENING HERE

def _set_projection_matrix():
    # NOT MULTIPLYING BY THE ZOOM LEVEL right or top
    # BUT WE PREVIOUSLY REDUCED THE PROJECTION SIZE TO THE ZOOM RATIO SPECIFIED
    self._projection_matrix = Mat4.orthogonal_projection(*self.projection, self._near, self._far)

def _set_view_matrix():
    result_position = Vec3(
        (self.position[0] / (self.viewport_width / 2)),
        (self.position[1] / (self.viewport_height / 2)),
        0
    )
    self._view_matrix = ~(Mat4.from_translation(result_position)  # NOT MULTIPLYING BY THE ZOOM LEVEL
```

**Comment by DigiDuncan** [comment]
> @DigiDuncan can you provide any example in the arcade examples that is also not working? I can't run your code.
> 
> Error: ' 'ParallaxView' object has no attribute 'camera'

Apologies! I've updated the gist. It seems some old Charm code found it's way in there.
https://gist.github.com/DigiDuncan/2f194def17db0c1d471f69da9179ee9a

I made sure it runs as its own file, and only requires Arcade.

**Comment by DigiDuncan** [comment]
For reference, the test (pre-2.7) looked like this:
![parallax](https://user-images.githubusercontent.com/3279495/216656366-eb8d02f8-4053-4d1f-914d-2a36feea06ed.gif)

**Comment by alejcas** [comment]
I can confirm now that this issue was introduced in my PR #1431.

I think I will rollback to the older approach. But that way zoom will be disconnected from projection to viewport ratio.

Let me a few days to do so.

**Comment by alejcas** [comment]
Hi, with PR #1626 this should be fixed.

**Comment by einarf** [comment]
Merged
