### ISSUE TITLE
create_lines_with_colors doesn't work properly for width > 1

### ISSUE THREAD

**Issue by kosvitko** [pythonarcade/arcade#1502]
## Bug Report
When invoking create_lines_with_colors with width > 1 the output looks like (but not exact) call to line_strip functions:
all segments of lines are connected.
When invoking create_lines_with_colors with width 1 everything is as expected (lines segments are separated)

## System Info
Run this and paste the output here: python -m arcade
Arcade 2.6.17
-------------
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce GTX 960M/PCIe/SSE2
version: (4, 6)
python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)]
platform: win32

### Actual behavior:
with width > 1 (thick lines code) all points in points array are connected, colors are gradients in every other connection:
```
(0, 1) color: (c0, c1)
(1, 2) color: (c1, c2) <==== wrong segment
(2, 3) color: (c2, c3)
...
```
### Expected behavior:
Connected only pairs of points i.e. (0,1), (2,3), etc..
```
(0, 1) color: (c0, c1)
(2, 3) color: (c2, c3)
...
```

### Steps to reproduce/example code:
```
        self.shape_list = arcade.ShapeElementList()
        point_list = ((0, 50),
                      (10, 10),
                      (50, 0),
                      (10, -10))
        color = [random.choice(colors) for i in range(len(point_list))]
        my_lines = arcade.create_lines_with_colors(points, color, 4)
```

## Enhancement request:
fix 
### What should be added/changed?
1. modify create_lines_with_colors so that 2 triangles are configured instead of 1 rectangle
```
-            new_color_list += color1, color1, color2, color2
-            triangle_point_list += points[1], points[0], points[2], points[3]
+           new_color_list += color1, color1, color2, color1, color2, color2
+           triangle_point_list += points[0], points[1], points[2], points[0], points[2], points[3]
```
2. modify create_triangles_filled_with_colors so that separate triangles are rendered:
```
-    shape_mode = gl.GL_TRIANGLE_STRIP
+    shape_mode = gl.GL_TRIANGLES
```
3. 
### What would it help with?
bring the expected behavior

**Comment by kosvitko** [comment]
to check other create_ functions, that use create_triangles function, as "strip" behavior could be expected by them

**Comment by kosvitko** [comment]
updated python to 3.11 to be able to build arcade package.

**Comment by einarf** [comment]
Thanks for the report. There are some rough things in ShapeElementList currently. The plan was to rewrite it using pyglet batch in 3.0 / development branch, but it doesn't hurt fixing this I guess.
