### ISSUE TITLE
Highlights on long lines in code boxes end early

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1510]
### Actual behavior:

Highlights do not cover the entirety of wide lines:
![image](https://user-images.githubusercontent.com/36696816/218278628-30a1284c-54c7-4e46-9df6-39080e04fd0b.png)

### Expected behavior:
Highlights extend the full width of the code box

### Versions affected
3.0dev, 2.6.17, likely earlier versions

### Steps to reproduce/example code:
1. View any page with long highlighted lines in a codebox, such as [the simple background example](https://api.arcade.academy/en/latest/examples/sprite_collect_coins_background.html)
2. Scroll down to a highlighted line which is too long to fit on screen
3. Scroll right to the right
4. Observe the cutoff highlight

**Comment by Ibrahim2750mi** [comment]
Its [not fixable](https://stackoverflow.com/questions/75843630/set-line-character-limit-for-sphnix-emphasize-lines-directive?noredirect=1#comment133786426_75843630). The best we can do is wrap them to 100 character per line. That would be alot of work, are you wiling to do it @pushfoo?

**Comment by pushfoo** [comment]
That link doesn't explain why it isn't possible.

> The best we can do is wrap them to 100 character per line.

I agree that this is probably the best approach in the short term.

**Comment by Ibrahim2750mi** [comment]
> That link doesn't explain why it isn't possible.

About that, I think its a limitation with sphinx if you have seen the highlighted comment, also maybe we can try a custom style with sphinx to fix this as mentioned in the comments?

**Comment by einarf** [comment]
https://github.com/pythonarcade/arcade/issues/2243
