### ISSUE TITLE
Drawing is freezing when using GLSL and "draw_text"

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#1520]
##  Steps to reproduce:
Run following script:

```
import arcade
from arcade.experimental import Shadertoy


class Main(arcade.Window):
    def __init__(self):
        super().__init__()

        self.shadertoy = None
        self.channel0 = None
        self.channel1 = None
        self.sprite = arcade.Sprite(":resources:images/animated_characters/male_person/malePerson_idle.png", center_x=400, center_y=350)
        self.i = 0
        self.shadertoy = Shadertoy.create_from_file((800, 600), 'shader.glsl')
        self.channel0 = self.shadertoy.ctx.framebuffer(color_attachments=[self.shadertoy.ctx.texture((800, 600), components=4)])
        self.channel1 = self.shadertoy.ctx.framebuffer(color_attachments=[self.shadertoy.ctx.texture((800, 600), components=4)])
        self.shadertoy.channel_0 = self.channel0.color_attachments[0]
        self.shadertoy.channel_1 = self.channel1.color_attachments[0]
        self.shadertoy.program['lightPosition'] = (400, 300)
        self.shadertoy.program['lightSize'] = 10000000

    def on_draw(self):
        self.channel0.use()
        self.channel0.clear()
        self.channel1.use()
        self.channel1.clear()
        self.use()
        self.clear()
        self.shadertoy.render()
        self.sprite.draw()
        arcade.draw_text(f'{self.i}', 400, 200, arcade.color.FRENCH_WINE, 40, anchor_x='center')
        self.i += 1


Main()
arcade.run()
```

`shader.glsl` file was taken from here: https://api.arcade.academy/en/latest/tutorials/raycasting/step_06_gl.html

## Issue:
Drawing is freezing after a few moments:

![Untitled Project](https://user-images.githubusercontent.com/21060932/218844497-68ad1931-6ed3-412d-ac17-2a74bac68268.gif)

## System info:
OS: Win 11
Python: 3.11
Arcade: 2.6.17

**Comment by pushfoo** [comment]
Can you try using the `arcade.Text` object instead?

**Comment by alderven** [comment]
> Can you try using the `arcade.Text object` instead?

Works like a charm. Thank you!

**Comment by pushfoo** [comment]
Could you please also try updating the text's value outside the draw call when using `draw_text`? 

Although the best solution is to avoid using `draw_text` altogether due to it being a pretty ugly series of kludges, I have a hunch that might let others debug this more thoroughly.

**Comment by alderven** [comment]
> Could you please also try updating the text's value outside the draw call when using `draw_text`?

It didn't help

**Comment by pushfoo** [comment]
Thank you. My hunch is probably wrong.

On the upside, using `Text` is the better option from the speed perspective alone: it may be up to 12,000 times faster if I correctly remember what I another developer said.

**Comment by pushfoo** [comment]
@alderven
I have some follow-up questions:
1. How long does it take to happen?
2. What GPU do you have? Try pasting the output of `python -m arcade` here

I can't replicate this on my system, neither with 2.6.17 nor the latest development branch.

**Comment by alderven** [comment]
> 1. How long does it take to happen?

It can happen on frame 14 or frame 1000. Always randomly.

> 2. What GPU do you have? Try pasting the output of python -m arcade here

```
Arcade 2.6.17
-------------
vendor: Intel
renderer: Intel(R) UHD Graphics
version: (4, 6)
python: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
platform: win32
```

**Comment by einarf** [comment]
It could just be a driver issues. It's not uncommon to have old intel iGPU drivers. Depending on the manufacturer you may or may not get drivers updates from win update.

**Comment by einarf** [comment]
I think I know what the issue is. Since we cache the labels we can end up re-drawing the same label multiple times a frame and you end up modifying a vertexdomain while the redering call is happening. This is not very popular on iGPUs.

I'd say we just remove the label cache and accept that it will be 10 times slower.

**Comment by einarf** [comment]
0ca1a04 should fix this

Try latest development branch
