### ISSUE TITLE
Enhancement: Unprotect _SpatialHash

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1556]
### What should be added/changed?
Per Discord discussion with @einarf , [`_SpatialHash`](https://github.com/pythonarcade/arcade/blob/3ffbf27c3e4ee991cbf20aee21c2a0eb97e96ff1/arcade/sprite_list/spatial_hash.py#L24) should be unprotected and possibly specified as a [Protocol type](https://docs.python.org/3/library/typing.html#typing.Protocol).

### What would it help with?
Improve customization options such as enabling #1297

**Comment by einarf** [comment]
https://github.com/pythonarcade/arcade/issues/1556

**Comment by einarf** [comment]
https://github.com/pythonarcade/arcade/pull/1567

**Comment by einarf** [comment]
Will be in when my branch is merged. Closing.
