### ISSUE TITLE
Avoid marking non-aliased imports as private

### ISSUE THREAD

**Issue by MrWardKKHS** [pythonarcade/arcade#1558]
## Bug Report
It is standard (see PEP 484 stub file section) to mark redundantly
imported items as exported. 

Pyright users currently see a linting error when using arcade.color and other imports from arcade in the global namespace.

## System Info

Run this and paste the output here: python -m arcade

Arcade 3.0.0.dev13
------------------
vendor: Intel
renderer: Intel(R) Iris(R) Xe Graphics
version: (3, 3)
python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
platform: win32
pyglet version: 2.0.4
PIL version: 9.4.0

### Actual behavior:
Pyright displays an error 
![image](https://user-images.githubusercontent.com/60589645/219992176-0febf04e-3253-49f8-8aa8-fe91fb8e0d96.png)

### Expected behavior:
No linting for these symbols

### Steps to reproduce/example code:
any use of arcade.color, arcade.key, arcade.experimental etc. while using pyright

### What should be added/changed?
Imports from the arcade __init__ file should be redundantly aliased as themselves
`from arcade import color as color` etc

### What would it help with?
Linting and static type checking for pyright users.

**Comment by einarf** [comment]
https://peps.python.org/pep-0484/#stub-files

> Modules and variables imported into the stub are not considered exported from the stub unless the import uses the import ... as ... form or the equivalent from ... import ... as ... form. (UPDATE: To clarify, the intention here is that only names imported using the form X as X will be exported, i.e. the name before and after as must be the same.)
