### ISSUE TITLE
Improve clarity of CI errors for example docstring formatting

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1570]
### What should be added/changed?
The output of [the example docstring tests](https://github.com/pythonarcade/arcade/blob/development/tests/unit/test_example_docstrings.py) should be clearer. At the moment, it looks like this:

```console
FAILED tests/unit/test_example_docstrings.py::test_docstrings - AssertionError: python -m arcade.examples.bloom_defender not in arcade.examples.bloom_defender docs...
```

 Specifically, we should look into adding at least two things:
1. Explain more clearly when a docstring is missing entirely
2. Explain when a docstring has an incorrect run command + what it should be

I am not sure how to include this in CI at the moment. Outputting the expected run command on failure may be easier.

### What would it help with?
Two regular contributors have been confused by the output of the CI docstring checks. Improving legibility here would improve our development speed.

**Comment by gran4** [comment]
The file you are referencing doesn't seem to exist anymore.

**Comment by pushfoo** [comment]
Ty for pointing out the dead link & for the reminder! I've updated the issue & started a PR.

**Comment by einarf** [comment]
The output is improved a little bit now and paul added detailed into in the unit test itself.
