### ISSUE TITLE
Documentation: Update Edge Artifacts Page to Use Cameras

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1592]
## Documentation request:

Per my understanding of discussion on Discord, the [set_viewport](https://api.arcade.academy/en/latest/api/window.html#arcade-set-viewport) function will be removed in favor of using Cameras in 3.0.

If this is the case, [the edge artifacts page](https://github.com/pythonarcade/arcade/blob/development/doc/programming_guide/edge_artifacts/index.rst) needs to be updated after the following occur:
1. I merge my SpriteList doc changes
2. `set_viewport` is removed

I can take care of this after my doc changes. We may also want to think about cleaning up that page in general.

**Comment by pushfoo** [comment]
I'm  also considering adding a camera subclass or flag which snaps the viewport to whole pixels or validates it.

**Comment by DragonMoffon** [comment]
will do as part of camera refactor

**Comment by einarf** [comment]
This should not be a problem any more except in extreme situations. It's explained in relation to the border size parameter on the atlas.
