### ISSUE TITLE
Bug : drawing multiple lines causes other draw calls to produce no output

### ISSUE THREAD

**Issue by NilsApffel** [pythonarcade/arcade#1610]
## Bug Report
When drawing 2 or more lines with arcade.draw_line, the next call to arcade.draw_scaled_texture_rectangle does not produce the expected output.

## System Info
```
Arcade 2.6.17
-------------
vendor: Intel
renderer: Intel(R) UHD Graphics
version: (4, 6)
python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
platform: win32
```

### Actual behavior:
2 lines are drawn, but the example image and the rectangle are not drawn
![actual_output](https://user-images.githubusercontent.com/97693900/222958631-78da2640-78ca-4d8b-a854-b8f93a67a1f2.png)

### Expected behavior:
2 lines are drawn, the example image is drawn, the rectangle is drawn
![expected_output](https://user-images.githubusercontent.com/97693900/222958628-bb6a2ae2-2b5e-45bd-876d-477fcacfdea2.png)

### Steps to reproduce/example code:
```
import arcade

class GameWindow(arcade.Window):
    def __init__(self):
        super().__init__(600, 400)
        arcade.set_background_color(arcade.color.ORANGE)
        self.all_sprites = arcade.SpriteList()

    def setup(self):
        arcade.set_background_color(arcade.color.ORANGE)
        self.all_sprites = arcade.SpriteList()

    def on_draw(self):
        self.clear()
        arcade.draw_line(
            start_x=40, 
            start_y=60, 
            end_x=100, 
            end_y=160, 
            color=arcade.color.LIGHT_GRAY, 
            line_width=2
        )
        # arcade.draw_line( # UNCOMMENT THIS TO REVEAL BUG
        #     start_x=50, 
        #     start_y=50, 
        #     end_x=10, 
        #     end_y=16, 
        #     color=arcade.color.LIGHT_GRAY, 
        #     line_width=2
        # )
        arcade.draw_scaled_texture_rectangle(
            center_x=300,
            center_y=300,
            texture=arcade.load_texture('test.png')
        )
        arcade.draw_lrtb_rectangle_filled(
            left=0,
            right=100,
            top=400,
            bottom=300,
            color=arcade.color.BLUE
        )
        

if __name__ == "__main__":
    app = GameWindow()
    app.setup()
    arcade.run()
```
![test_image](https://user-images.githubusercontent.com/97693900/222958465-5fdc51ca-eef6-49b1-8d00-e08bafe48a4f.png)

**Comment by einarf** [comment]
I think this is an Intel UHD specific issue. It could as well be a driver issue. Is it possible in your situation to use `draw_lines` instead? You could also check if your drivers are somewhat up to date. Depending on the manufacturer you might not get driver updates through windows update. (AMD iGPUs can have same issue if drivers are old)

We've been looking into some way to solve this issue for a while. It's related to small rendering calls.

**Comment by einarf** [comment]
There is something these drivers are doing to the rendering queue I think. You can `window.ctx.flush()` between draw calls force all queued rendering calls to be completed before continuing, but this also slows things down.

**Comment by einarf** [comment]
It could be that we need to orphan the position buffer here: https://github.com/pythonarcade/arcade/blob/aa5874ccdb317652ccc78123f09dfdaad7244327/arcade/draw_commands.py#L453-L454

`ctx.shape_line_buffer_pos.orphan()` before the write, but that doesn't explain why subsequent rendering calls are not appearing.

**Comment by NilsApffel** [comment]
Thanks for the advice ! Updating my drivers did not solve the problem, but adding a `self.ctx.flush()` after the `draw_line` calls does seem to be a viable interim solution. Switching my code to using `draw_lines` is trickier, but probably a better long-term solution.

**Comment by einarf** [comment]
Ok. I will try something in arcade 3.0 / dev branch. Will post here when this is done and you can test it if you want. Help would be appreciated.

**Comment by einarf** [comment]
You can try with arcade 3.0 latest dev branch.
```
pip install -I https://github.com/pythonarcade/arcade/archive/refs/heads/development.zip
```

**Comment by NilsApffel** [comment]
Using the arcade 3.0 dev version, the example code above works as intended, and so does my real code. Thank you !

**Comment by einarf** [comment]
Awesome. Thank you for testing!

**Comment by einarf** [comment]
Also just a last note:

If you are going to draw a lot of stuff (50+) you should consider using `SpriteList` for drawing your textures and `ShapeElementList` for drawing static geometry. This is several orders of magnutide faster than using `draw_` calls. Also never call `load_texture` in the draw loop.
