### ISSUE TITLE
Endless loop in class EmitInterval

### ISSUE THREAD

**Issue by tobiasbp** [pythonarcade/arcade#1628]
## Bug Report
If _emit_interval_ is set to _0.0_ in class _EmitInterval_, [this](https://github.com/pythonarcade/arcade/blob/3ffbf27c3e4ee991cbf20aee21c2a0eb97e96ff1/arcade/particles/emitter.py#L61
) loop will never end:
```
while self._carryover_time >= self._emit_interval:
            self._carryover_time -= self._emit_interval
            emit_count += 1
```

Recreate by using an emit controller like this:
```
ec = EmitInterval(0.0)
```

Potential fix:
```
# was self._emit_interval = emit_interval
self._emit_interval = max(emit_interval, 0.001)
```

**Comment by einarf** [comment]
Thanks. Maybe just raising an error is reasonable here?

**Comment by tobiasbp** [comment]
> Thanks. Maybe just raising an error is reasonable here?

Yes, that's much better. Do you want me to make a PR?

**Comment by einarf** [comment]
> Yes, that's much better. Do you want me to make a PR?

That would be awesome 👍

**Comment by Miho42** [comment]
I talked to @tobiasbp. I'd like to give it a try :)
I'll create a PR.
