### ISSUE TITLE
Bug: Wrong dark mode search box color on Quick API page under Chrome/Chromium

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1632]
## System Info
Browsers affected:
```
Chromium, Version 110.0.5481.177 (Official Build), 64 bit
```
Browsers unaffected:
```
FireFox, 102.8.0esr (64-bit)
```

All Furo doc versions appear to be affected, including:
* Local tip of development + SpriteList doc PR (#1620 )
* https://api.arcade.academy/en/development/api_docs/api/quick_index.html
* https://api.arcade.academy/en/latest/quick_index.html
* https://api.arcade.academy/en/2.6.15/quick_index.html

### Actual behavior:
Under Chromium, the text in Quick API search box under dark mode is black rather than the lighter color used in the main search box.
![image](https://user-images.githubusercontent.com/36696816/223949265-5c2aac87-f973-4bc5-bc5f-c514f2c7b03a.png)

FireFox appears to be unaffected.

### Expected behavior:
Text in the Quick API search box uses the same lighter color as the main search box
![image](https://user-images.githubusercontent.com/36696816/223949393-7aeb8c72-82bb-40f7-b66f-2a796248223a.png)

### Steps to reproduce/example code:
1. `cd` into the doc directory
2. Build doc locally with `make html`
2. Launch local dev server with `python -m http.server -d build/html`
3. Open Chromium
4. Ensure dark mode is set
5. Navigate to Quick API Index page
6. Enter any text into the search box

**Comment by pushfoo** [comment]
The [rtd-docs](https://github.com/pythonarcade/arcade/commits/rtd-docs/) branch has a fix for this.

**Comment by einarf** [comment]
Just closing this now.
