### ISSUE TITLE
Tiles that were rotated in Tiled have wrong hitbox

### ISSUE THREAD

**Issue by ksetrae** [pythonarcade/arcade#1695]
## System Info  

Arcade 3.0.0.dev20
vendor: NVIDIA Corporation
renderer: GeForce GTX 1650/PCIe/SSE2
version: (3, 3)
python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
platform: win32
pyglet version: 2.0.5
PIL version: 9.4.0

also pytiled-parser==2.2.0

### Actual behavior:
Tiles that were created in Tiled and rotated there have wrong hitbox.

### Expected behavior:
Expecting tiles to change hitbox accordingly with rotation.  
Would this be difficult to fix? I learned that a bug with incorrect rotation was present in Arcade 3.0.0.dev16, but after switching to dev20 visually it was fixed, but hitbox is still problematic. 

### Steps to reproduce/example code:
I attached a little project in which you can just run main.py and see that right side of ground sprites has space between them and boxes, these are exactly ones that were rotated.
The left side sprites (unrotated) do have correct hitboxes.
![screenshot](https://user-images.githubusercontent.com/39910639/231217610-c8f85bad-4918-4a2f-bfa2-41d93e94b019.PNG)

[tile_hitbox_demo.zip](https://github.com/pythonarcade/arcade/files/11202364/tile_hitbox_demo.zip)

**Comment by pushfoo** [comment]
@einarf Is this related to the rotation direction switch for angles?

**Comment by Cleptomania** [comment]
It's a kind of awkward side effect of the rotation direction switch. The Transpose/Transverse transforms on the textures didn't get switched for the hit box points rotation. Quick fix just need to swap around the hit box points adjustment for those two Transforms and it works.

I'm leaving this open for the moment as a good first issue for some upcoming sprints, I'll put in a fix after that if no one else runs with it.

**Comment by Cleptomania** [comment]
This was fixed with #1711
