### ISSUE TITLE
TileMap

### ISSUE THREAD

**Issue by Baanista** [pythonarcade/arcade#1703]
There is a error with TilMaps. I believe this is due to a change of the class's name.@gran4 know more on the issue.

**Comment by Cleptomania** [comment]
We'll need much more information to investigate this at all.

Namely what version of Arcade, what the error is, and if possible a minimal example that reproduces the problem.

**Comment by pvcraven** [comment]
I'm going to close this as there's been no additional info in three weeks, and the original report has next-to-no info.
