### ISSUE TITLE
Bug: Fix Surface.draw_texture's NinePatchTexture handling

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1705]
### Actual behavior:
`arcade.gui.Surface.draw_texture` has following incorrect behavior:

1. The check for `angle` uses `x` and `y` arguments
2. The check for `alpha` uses `x` and `y` arguments

https://github.com/pythonarcade/arcade/blob/e76f34554f04d7e6e8e0e88f8a279469f6d4e475/arcade/gui/surface.py#L100-L110

### Expected behavior:

1. The angle check uses the `angle` argument
2. The alpha check uses the `alpha` argument

**Comment by eruvanos** [comment]
Actually if the `prepare_render()` method is called, the viewport is changed, to limit rendering within bounds of the widget. Which means, a position on the NinePatchTexture would move it out of the viewport.

So in most situations setting position would break the draw function.

**Comment by pushfoo** [comment]
I've updated the ticket to reflect that. I still think we can make the correction as part of PyCon if someone is interested, but it may be a good idea to double check #1682 since there may have been a misunderstanding during its writing & review.
