### ISSUE TITLE
No error if import going unused.

### ISSUE THREAD

**Issue by gran4** [pythonarcade/arcade#1734]
## System Info
Mac 2017, arcade development tests(so the development version)

### Actual behavior:
Doesn't pick up if there is a import going unused.

### What should be added/changed?
Look at and PR tests(and mine) and you can see that there is no error if there is an unused import.

**Comment by cspotcode** [comment]
This is one of the things that pyright can flag, I'm experimenting with enabling pyright on CI in #1738, though the actual code changes will probably be extracted into other PRs to be merged.  #1738 experiments with a bunch of things, not all of them should go in.

Unfortunately pyright, even in "basic" typechecking mode, has a bunch of errors on arcade's codebase, so we'd need to either turn off those diagnostics or fix them.

**Comment by einarf** [comment]
We don't really do type checking on unit tests right now.

**Comment by einarf** [comment]
Closing this one. It can be improved in a typing pass later.
