### ISSUE TITLE
Add Community RPG to Docs

### ISSUE THREAD

**Issue by gran4** [pythonarcade/arcade#1735]
### What documentation needs to change? 

Can someone add a section about https://github.com/pythonarcade/community-rpg. It's pretty cool and we can get other people to open source contribute. I didn't know this existed so it would be helpful to put it on there.

**Comment by pushfoo** [comment]
The Community RPG is already linked [On the Examples page under Concept Games](https://api.arcade.academy/en/latest/examples/index.html#concept-games) on both 2.6 and development branch.

To my understanding, it's not put front and center at the moment for two reasons:

1. The current version does not work readily or easily
2. There was some sort of refactor project in progress by @benjamin-kirkbride
