### ISSUE TITLE
Is it possible to make contributors be able to put labels on issues?

### ISSUE THREAD

**Issue by gran4** [pythonarcade/arcade#1736]
Is it possible to make contributors be able to put labels on issues?
Is there any reason to not?

Also(Sort of OFF Topic but), could an ai auto put tags such as size onto PRs?

**Comment by gran4** [comment]
It seems like there are a lot of issues without labels. If I can, how do I?

**Comment by einarf** [comment]
This is possible if contributors are giving Triage role. These questions are however better on the discord server.
