### ISSUE TITLE
Texture cache file entries allow duplicates because the cache key is a new `Path` instance each time

### ISSUE THREAD

**Issue by cspotcode** [pythonarcade/arcade#1752]
## Bug Report

May be related to #1586.  Uncovered by pyright.

`TextureCache` does this:

https://github.com/pythonarcade/arcade/blob/37ba31f39ae5d89b042e0332ff73fa99062b1c58/arcade/cache/texture.py#L94-L97

Except that `file_path` is an instance of `Path`.  This means the `if` will always fail and that exception will never throw.

I think the tests are relying on this behavior since they load the same texture multiple times:

https://github.com/pythonarcade/arcade/blob/37ba31f39ae5d89b042e0332ff73fa99062b1c58/tests/unit/cache/test_hit_box_cache.py#L73-L84

I can include a fix as part of my work on #1751, but I'm not sure what the fix should be: throw the exception?  Silently allow the same entry to be put in cache multiple times?

**Comment by einarf** [comment]
I think I partly fixed this in my branch'. The initial caching was kind of over-engineered to get something up and running after the texture revamp. We'll just simplify the caching and move it inside the texture manager itself.

**Comment by einarf** [comment]
Fixed. We only use string keys
