### ISSUE TITLE
Standardize arcade docstrings

### ISSUE THREAD

**Issue by gran4** [pythonarcade/arcade#1756]
### What should be added/changed?
Standardize docstrings because right now arcade seems to use 2 unrelated doc string formats

### What would it help with?
My sanity and the sanity of people who do not know the code 100%.

EDIT: What I meant by 100% was that if someone knew it well was going to benefit less than a person who does not know it.

**Comment by pushfoo** [comment]
I strongly agree with the ideas of standards and increasing legibility in general, but I'm concerned there is at least one misunderstanding involved here.

> Standardize docstrings because right now arcade seems to use 2 unrelated doc string formats

Can you please provide examples of this?

>  of people who do not know the code 100%.

Nobody, not even einarf, knows the entire codebase completely. It changes too much, and we also often forget what we worked on in the past as we work on other things. Docstrings and comments help with that.

**Comment by gran4** [comment]
Everybody benifits, I guess. What I meant by 100% was that if someone knew it well was going to benefit less than a person who does not know it.

**Comment by gran4** [comment]
@einarf , @pushfoo , @pvcraven , @eschan145 , @Cleptomania 

What version of doctrines should arcade standarize?

**Comment by pushfoo** [comment]
I edited my earlier response for clarity. I apologize for the typo in it.

> right now arcade seems to use 2 unrelated doc string formats

Please link or name specific examples of where this is occurring, with an explanation of how the formats deviate from what's expected, or what's unclear.

**Comment by gran4** [comment]
The Sprite class seems to use reStructedTextFormat, while _heuristic in path.py uses google format

**Comment by cspotcode** [comment]
I thought this was going to be accomplished with an automated converter?

Thinking of the thread where this was discussed:
https://discord.com/channels/458662222697070613/1093579169977356369

**Comment by gran4** [comment]
Some times, arcade does ` :param float left: The left of the screen.`

while other times it does 
`:param volume: Volume of the sound (0 to 1).`
        `:type volume: float`

**Comment by gran4** [comment]
@cspotcode I think I'll close this because it looks like a duplicate.
