### ISSUE TITLE
VideoPlayerView is not accessable

### ISSUE THREAD

**Issue by MrWardKKHS** [pythonarcade/arcade#1779]
## Enhancement request:
Allow VideoPlayerView to be imported

### What should be added/changed?
arcade\experimental\__init__.py should have VideoPlayerView added to exports

### What would it help with?
Quality of life \ ease of use improvement for users trying to play videos \ cutscenes

**Comment by einarf** [comment]
There's some more work needed to make it a bit more flexible, but I don't see any harm in this. The cv2 player could also potentially be imported wrapped in an ImportError.

Ideally we should complete it and move it into `arcade.video`. It's something we can wrap up later in 3.x.x.

**Comment by MrWardKKHS** [comment]
This was fixed by #1780
