### ISSUE TITLE
Should UI controls accept `None` for text?

### ISSUE THREAD

**Issue by cspotcode** [pythonarcade/arcade#1799]
https://github.com/pythonarcade/arcade/blob/238108299bebc74e6588a766c22147f76d7711d9/arcade/gui/widgets/dropdown.py#L64-L66

`self._value` might be `None`, but `UIFlatButton` claims it won't accept `None`.

```python
self._default_button = UIFlatButton(
    text=self._value, width=self.width, height=self.height
)
```

**Comment by gran4** [comment]
Look at line 42:
instead of `default: Optional[str] = None`
how about
`default: str = ""`

**Comment by eruvanos** [comment]
With `None` the developer has the option to say, nothing is selected, while an empty string could be a valid option.
While checking the code I fixed some bug (https://github.com/pythonarcade/arcade/pull/1806)

Feel free to reopen this issue, if you still have concerns.
