### ISSUE TITLE
Extra initial default texture frame in OneShotAnimationSprite

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#1803]
## System Info

Arcade 3.0.0.dev20
------------------
vendor: Intel
renderer: Intel(R) UHD Graphics
version: (3, 3)
python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
platform: win32
pyglet version: 2.0.6
PIL version: 9.4.0

### Actual behavior:

Before the animation starts, there is an extra frame with the default texture.

If I add `self.texture = self.frames[self.cur_frame_idx].texture` to the end of `OneShotAnimationSprite.__init__`, the problem disappears.

### Expected behavior:

The animation frames in OneShotAnimationSprite are the textures passed to it, with no additional default texture.

### Steps to reproduce/example code:

Create a OneShotAnimationSprite, passing it a list of textures, look at the animation.

**Comment by bunny-therapist** [comment]
I edited the title since the bug seems to affect `AnimatedTimeBasedSprite` as well. I noticed the blinking default texture in animated sprites loaded from a Tiled map.

**Comment by einarf** [comment]
Right. I'm guessing the default texture is added to `textures` list? If you just append that one you will keep the default texture. It's something we need to figure out a way to improve. It's a consequence of requiring a texture with a fallback.

**Comment by bunny-therapist** [comment]
I haven't looked at it in a while, but I don't think it is added to the `textures` list. If it was, the workaround I wrote would not work and one would instead have to increment `self.cur_frame_idx` to skip past the default texture. I think that `textures` are set correctly, but since no one texture is passed to `__init__`, `self.texture` is assigned the default texture and there is nothing in the `__init__` that sets the texture to the first list in the `textures` list (which is why my workaround works).

**Comment by einarf** [comment]
Should be fixed in 2e0bc4bf7e80cc48b971931024bf57457ec415f8

Be free to give feedback on these changes. The initial texture is set when assiging the animation. Some renaming happened as well.
