### ISSUE TITLE
Make 3.0 plan visible to contributors

### ISSUE THREAD

**Issue by cspotcode** [pythonarcade/arcade#1808]
As contributors to arcade who want to help ship 3.0, we need to see the plan.  That plan is currently hidden, it should be visible.

If that plan is not written down, then it should be written down somewhere.  If multiple plans exist, they should be consolidated.

A clear and visible plan can be a great motivator.

**Comment by pushfoo** [comment]
I'm having trouble coordinating with others on 3.0 work. I've posted a screenshot before when I was surprised to find out others don't have read access on the dashboard, and today is at least the second time this has come up. I would appreciate being able to coordinate this better with others.

**Comment by Cleptomania** [comment]
There is a 3.0 project under the GitHub Projects feature, but I seem to not be able to change its visibility to public so I’ll see if @einarf or @pvcraven is able to do that.

I’m not sure how accurate that is, we’ve never really sat down and outlined everything for 3.0 before. It’s mostly just naturally evolved as we worked on stuff.

From my perspective, the last thing I really want to get done on my end is finishing the rewrite of the platformer tutorial. I think it will be helpful to have that done in time with the full 3.0 release.

**Comment by cspotcode** [comment]
Ok, based on the information available to me, the easiest plan is:

a) Change visibility on the relevant Github Project so that anyone can read it
b) Update the github project to be accurate

Achieving (b) might be easier if pushfoo gets permission to move cards around?  That way, we spread out the workload.

**Comment by pvcraven** [comment]
This project has been made public.
https://github.com/orgs/pythonarcade/projects/1/views/1
