### ISSUE TITLE
Handle empty/missing hit box points

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#1815]
The old behavoir in 2.6 was to always return some reasonable hit box for sprites. We simply used the a bounding box around the entire image as a fallback. There wave been requests to handle this differently. For example disable collision entirely for sprites with no valid points.

I don't know how this will impact the underlying systems performance wise or what needs to be updated both rust and python implementations. Is this a good idea in the first place?

PR restoring the old behavor is here : https://github.com/pythonarcade/arcade/pull/1814

**Comment by bunny-therapist** [comment]
Hitboxes are not just used for collision. They are (in arcade 3 at least) also used for properties like top, bottom, left, right. The current behavior is for these properties to crash when the list of points is empty. For example, calling sprite.top for a sprite with no hitbox points raises `ValueError: max() arg is an empty sequence`

The old behavior is preferable.

If the community still decides to allow empty hitbox points and disable collisions for such sprites, then things such as the top, bottom, left, right properties should be reimplemented; they cannot be allowed to just crash.

**Comment by einarf** [comment]
Definitely the old behavior is preferable for now. Changing this would require quite a bit or revamping. More than we want to do in 3.0.

**Comment by einarf** [comment]
https://github.com/pythonarcade/arcade/pull/1814 merged
