### ISSUE TITLE
Bug in Atlas.sync_texture_image

### ISSUE THREAD

**Issue by alejcas** [pythonarcade/arcade#1828]
## Bug Report

There's a bug related to this PR in the new Atlas.sync_texture_image

https://github.com/pythonarcade/arcade/pull/1816

When called the image is not exactly as it should be.
The border from the top, left corner gets cropped and a little of white border gets added on the bottom, right border.

Like this (the white border is not from the image itself):

![image](https://github.com/pythonarcade/arcade/assets/7224106/5c5fc77e-90bf-40f5-b420-435ac8914788)

Also talked about this on discord:

https://discord.com/channels/458662222697070613/696054807840030740/1116639873110118400

**Comment by gran4** [comment]
It looks like it is 1 pixel off?
If so, then that may be a simple change in get_texture_image
(not sure about this at all)
viewport = (
            region.x + self._border,
            region.y + self._border,
            region.width,
            region.height,
        )

to

viewport = (
            region.x + self._border-1,
            region.y + self._border-1,
            region.width,
            region.height,
        )
maybe self._boarder is for a different thing that goes from 1 instead of from 0 or vise versa?

**Comment by einarf** [comment]
It was something really stupid (of course). The stored region info already have borders applied, so I was just applying the borders twice. Will merge a fix shortly. The read/write method names are ambiguous so I'm also looking into better names.
