### ISSUE TITLE
arcade.get_fps() return 0 rather than get current FPS

### ISSUE THREAD

**Issue by Caynet1997** [pythonarcade/arcade#1834]
import arcade

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_TITLE = "2D Project with Arcade"
FPS = 120

class Level:
    def __init__(self, game):
        self.game = game

class Text:
    def __init__(self, game):
        self.game = game

    def draw_fps(self):
        # I  use arcade.get_fps() to get 0 FPS so i can only get FPS from class Game
        self.fps = arcade.Text(f"{1/self.game.fps:.1f}", 0, WINDOW_HEIGHT-30, arcade.color.ASH_GREY, 18)
        self.fps.draw()

class Game(arcade.Window):
    def __init__(self, width, height, title):
        super().__init__(width, height, title)
        arcade.set_background_color(arcade.color.BLACK)
        self.text = Text(self)

    def setup(self):
        pass

    def on_draw(self):
        self.clear()
        self.fps = self._draw_rate
        self.text.draw_fps()
        fps = arcade.get_fps()
        print(f"Current FPS: {fps}")

    def on_update(self, delta_time):
        pass

    def on_key_press(self, key, key_modifiers):
        pass

    def on_key_release(self, key, key_modifiers):
        pass

    def on_mouse_motion(self, x, y, delta_x, delta_y):
        pass

    def on_mouse_press(self, x, y, button, key_modifiers):
        pass

    def on_mouse_release(self, x, y, button, key_modifiers):
        pass

def main():
    game = Game(WINDOW_WIDTH, WINDOW_HEIGHT, WINDOW_TITLE)
    game.set_draw_rate(1/FPS)
    game.setup()
    arcade.run()

if __name__ == "__main__":
    main()

**Comment by Caynet1997** [comment]
version of Arcade is 3.0.0.dev24

**Comment by Caynet1997** [comment]
arcade.enable_timings() must be called before getting the FPS. 😅

**Comment by einarf** [comment]
Possibly something we can add in docstrings here?
