### ISSUE TITLE
Inquiry regarding Python Arcade on Replit.

### ISSUE THREAD

**Issue by HovanCL** [pythonarcade/arcade#1837]
I understand previously that Python Arcade no longer works on Replit because of certain changes. I am new to Python Arcade and was just wondering if there is a possibility for Python Arcade to work with Replit again in the future from your end. Or will Replit need to make changes on their end to make this possible? I view this issue from a learner's perspective, hoping to keep my Python Arcade projects in Replit and access them anywhere.

**Comment by einarf** [comment]
As far as I know it stopped working due to a change in the base images on replit. #1093

**Comment by eruvanos** [comment]
Works again, I tested with 2.6 and 3.

Here is a template I submitted: https://replit.com/@eruvanos/Python-Arcade-Demo?v=1
