### ISSUE TITLE
optimize fonts by only loading 3 by default instead of all kenney fonts

### ISSUE THREAD

**Issue by cspotcode** [pythonarcade/arcade#1844]

**Comment by pushfoo** [comment]
This may actually be a dupe of #1011, specifically this comment: https://github.com/pythonarcade/arcade/issues/1011#issuecomment-1088190556

If it's not a dupe and merely an overlap, this issue should mention using three metric-compatible SIL open font license fonts.

**Comment by cspotcode** [comment]
I see

> we should use the bundled font solution

Would you mind re-titling #1011 to say that, to describe briefly what must happen?  Is the task to bundle 3 fonts and load them at startup?

**Comment by pushfoo** [comment]
> Would you mind re-titling https://github.com/pythonarcade/arcade/issues/1011 to say that, to describe briefly what must happen?

Done, along with some revisions to the ticket for clarity.

> Is the task to bundle 3 fonts and load them at startup?

Yes, although the initial draft of the ticket was more conservative due to concerns about font licensing.

**Comment by einarf** [comment]
We don't load any fonts at startup any more. For unifying fonts between OSes there's another issue on that
