### ISSUE TITLE
Make a consistency guide for features and versioning.

### ISSUE THREAD

**Issue by DragonMoffon** [pythonarcade/arcade#1849]
This conversation crops up on the discord server every now and then, and with 3.0 coming up, I thought it would be good to agree on this.

Basically, I'd like to formalise in what version can / should new features be added and how.

For example, we could use an x.y.z structure. Anything goes in x version changes. y changes must be backward compatible but can otherwise be anything . z changes must be backward compatible and only resolve bugs or improve existing features.

That is just one idea, but we have a chance to formalise this, and we should, IMO.

**Comment by Cleptomania** [comment]
I think having the `y` changes have to be backwards compatible isn't going to work, Arcade sees too rapid of development and a lot of change that can break backwards compatibility in very small and not necessarily noticeable ways.

Until now the unofficial versioning has been X.Y.Z where X is the marketing version(think how Unreal Engine does it, with Unreal Engine 4, 5, etc, these versions are for when we have huge fundamental changes that have broad significant impacts on performance, how people interact with Arcade, a huge amount of internals re-working, etc).

Y is akin to what semantic versioning would call the major version. Guaranteed to have at least a breaking change, but from one version to the next it's probably nothing that's too hard to update, or it's localized to mostly being within one system(like TileMap in 2.5 -> 2.6 for example was completely re-written with no regard for the old API).

Then z is for everything else, and we will generally never intentionally break the API in this version, but I even still think we shouldn't make that guarantee, some problems are small and easy fixes, but just require a tiny API breaking change.

Consistency is more important than matching a specific versioning system. I think we would be better served to advocate for users properly pinning versions and being able to reference changelogs easily when upgrading. Arcade has the benefit of not being a library that really exposes security concerns, or functions as the backbone of SaaS applications, so there's a lot less pressure to ensure that we have releases that don't break the API in any way.

**Comment by DragonMoffon** [comment]
Fair enough! Maybe have an edited version of this somewhere in the contributing doc, and an even smaller piece in the main doc + stuff on pinning arcade versions.

One thing Im curious about is how we handle change logs, if at all? It currently feels like there has been lots of 3.0 work that hasnt been properly recorded. Since PRs are squished into a single commit, we might want to set up a formal description on how to do change logs. That way, it's easy to collate them with every version release. This isn't something that I know anything about, but I imagine it would be very helpful. Like my camera refactor is pretty beefy, and unless 3.0 gets released right after Im done with it, I doubt I'll fully remember everything I did in there.

**Comment by Cleptomania** [comment]
We don’t have anything formal surrounding changelogs. It’s been a best effort approach in the past, and I don’t think that Arcade has seen nearly the level of development in a single version update as we have with 3.0.

It is much easier for us to go through and build the changelog since we have the cleaner git history now, so that’s a plus.
