### ISSUE TITLE
Scene.add_sprite_list creates new SpriteList if empty SpriteList instance is passed

### ISSUE THREAD

**Issue by julianhoratschek** [pythonarcade/arcade#1851]
## Bug Report

scene.add_sprite_list("name", sprite_list=list_instance) will not add the desired Instance to scene-object, if list_instance is empty, but creates a new SpriteList within Scene instead.

## System Info

Arcade 2.6.17                                 
-------------                                 
vendor: NVIDIA Corporation                    
renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
version: (4, 6)
python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
platform: win32

### Actual behavior:

A new SpriteList is created in Scene. It can be retrieved via scene.get_sprite_list("name"), but pre-existing, empty SpriteLists will not be added.

### Expected behavior:

Add instance of empty SpriteList to Scene instead of creating a new one and ignoring empty instance.

### Steps to reproduce/example code:

import arcade

sl = arcade.SpriteList()

scene = arcade.Scene()
scene.add_sprite_list("list_neq", sprite_list=sl)
sl_neq = scene.get_sprite_list("list_neq")
assert(sl != sl_neq)

sl.append(arcade.Sprite("path/to/sprite.png"))
scene.add_sprite_list("list_eq", sprite_list=sl)
sl_eq = scene.get_sprite_list("list_eq")
assert(sl == sl_eq)

**Comment by gran4** [comment]
It seems like this is not applicable in the 3.0 dev version and seems like this problem has already been addressed.
Now it will only create a new spritelist only if the parameter `sprite_list` is None. Look at line 192/193 in scene.py
if sprite_list is None:
      sprite_list = SpriteList(use_spatial_hash=use_spatial_hash)

In your case, it will not create a new one in the 3.0 version

**Comment by julianhoratschek** [comment]
Great! Thank you very much for the fast response:)
