### ISSUE TITLE
Fix "GUI Style" page for 3.0

### ISSUE THREAD

**Issue by cspotcode** [pythonarcade/arcade#1866]
https://api.arcade.academy/en/development/programming_guide/gui/style.html

Dupe of #1101?  I'm not sure

**Comment by cspotcode** [comment]
@eruvanos I'm not sure who's best for this, so I assigned to you.

**Comment by pushfoo** [comment]
The original issue is large and unwieldy. This makes the scope clearer, so I wouldn't call it a dupe.

I'd suggest changing the title and contents to be something like "add basic information on styling the UI."

**Comment by eruvanos** [comment]
Thanks for the poke, I should be able to work on these issues in around a month. Help always welcome of cause :)

**Comment by eruvanos** [comment]
First docs are pushed

**Comment by eruvanos** [comment]
https://api.arcade.academy/en/development/programming_guide/gui/style.html
