### ISSUE TITLE
Add "Style Guidelines" doc somewhere

### ISSUE THREAD

**Issue by cspotcode** [pythonarcade/arcade#1874]
Add contributing docs explaining conventions for:

code style
commit style
docstring style

Linking to stuff we can put in the guide:

#1871
#1789
https://discord.com/channels/458662222697070613/458662458198982676/1139202373445767378
> Yes, rated G messages please. I get it, just want to keep as many people as possible feeling welcome.
*nothing major, a quick non-judgemental(!) blurb about keeping everything in issues, PRs, commits, & code G-rated*

**Comment by cspotcode** [comment]
Another thing:

Style guidance for magic methods, based on how they emit in sphinx w/prettyspecialmethods.
Draw inspiration from python docs: https://docs.python.org/3/library/stdtypes.html#dict
> `list(d)`
>   Return a list of all the keys used in the dictionary `d`.

**Comment by pushfoo** [comment]
Examples should be included in this as well:
1. When to add examples
2. Avoid recursive / complex data structures in beginner-oriented examples (#1888)
3. The top-level docstring

**Comment by gran4** [comment]
I feel like there is a lot of duplication in the draw commands with things like `draw_lrtb_rectangle_filled` vs `draw_lrbt_rectangle_filled`. It seems that the only difference is the order of the parameters

**Comment by pushfoo** [comment]
> there is a lot of duplication in the draw commands with things like

Correct. That's why the `lrtb` variants of rectangle draw functions are deprecated/ See #1650 and the [`development` branch version of the doc](https://api.arcade.academy/en/development/api_docs/api/drawing_primitives.html#arcade.draw_lrtb_rectangle_filled). It's why the `lrtb` variants still use `AttributeError` instead of the more correct `ValueError` at the moment.

**Comment by einarf** [comment]
We have most of this covered in https://github.com/pythonarcade/arcade/blob/development/CONTRIBUTING.md now
