### ISSUE TITLE
Fix installation docs

### ISSUE THREAD

**Issue by cspotcode** [pythonarcade/arcade#1877]
Fix the installation docs section

- [x] Update template
  - https://github.com/pythonarcade/template is out-of-date
  - uses requirements.txt instead of pyproject.toml
- [x] Deduplicate PyCharm instructions
  - *It may be easier for beginners to read a bespoke guide for their OS, but arcade does not have the manpower to maintain it.  We have to simplify to avoid bitrot*
  - Windows, Mac, and PyCharm pages all duplicate PyCharm/venv instructions
  - Collapse PyCharm docs to a single page
  - Each OS page should focus on installing python and arcade library.  Link to PyCharm page

See also:
- https://github.com/pythonarcade/arcade/issues/1194#issuecomment-1110327008
- https://github.com/pythonarcade/arcade/issues/1321

**Comment by sabadam32** [comment]
There seems to be no link to the template in the docs.  Is this mentioned anywhere in the docs so a user would even know about this?
Can we make this a larger repo with `cookiecutter` templates that can be for different game types.  Corresponding to the tutorials perhaps? 
I can create a few of them.  I think this would be great for the GameJam scene also.

**Comment by einarf** [comment]
There is one link to the template in docs. I will simply just archive the current install instructions. If users need detailed help this can be found in the arcade book instead. 

We have not been maintaining this guide so I'm 100% in agreement that a standard install doc is the right path there.

**Comment by einarf** [comment]
The template repo will be deleted. We no longer provide detailed install instructions. Instead we refer to the arcade book
