### ISSUE TITLE
Fix ordering&duplication in contributing docs

### ISSUE THREAD

**Issue by cspotcode** [pythonarcade/arcade#1879]
On the website, "How to Contribute", "Contributing to Arcade", and "How to Submit Changes" all duplicate information and are in the wrong order.

"How to Contribute" is the broadest overview, encompassing non-code ways to contribute.  Yet it is nested under "Contributing to Arcade" which is almost solely focused on code changes.

"How to Submit changes" duplicates "Contributing to Arcade" in describing pull requests.

**Comment by pushfoo** [comment]
> "How to Submit changes" duplicates "Contributing to Arcade" in describing pull requests.

This should likely be turned into a link for one of them. For other cases where the content overlap is short, would you be opposed to using includes?

**Comment by einarf** [comment]
Likely also related to this : https://github.com/pythonarcade/arcade/pull/1939

**Comment by pushfoo** [comment]
This looks completed on `development`.

**Comment by Cleptomania** [comment]
Yeah this was definitely handled by the consolidation I did in #1939
