### ISSUE TITLE
AssertionError in buffered_draw_commands.Shape

### ISSUE THREAD

**Issue by azitter91** [pythonarcade/arcade#1914]
## Bug Report

There appears to be an erroneous assertion in line 48 of buffered_draw_commands.Shape that results in an AssertionError when an object is created with a border width that is not equal to 1. I have not performed an exhaustive analysis of which objects this affects, but it is not consistent across all shapes.

## System Info

Arcade 2.6.17
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
version: (4, 6)
python: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
platform: win32

### Actual behavior:
The program fails and generates an AssertionError

### Expected behavior:
The program draws the shape with the correct border width

### Steps to reproduce/example code:

```
import arcade

# Constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Arcade"

class MyGame(arcade.Window):
    def __init__(self, width, height, title):
        super().__init__(width, height, title)

        arcade.set_background_color(arcade.color.WHITE)

    def setup(self):
        # Success Case
        self.shape_list_pass = arcade.ShapeElementList()
        self.shape_list_pass.append(arcade.create_lines(
            [(40, 40), (60,20), (40, 10), (20,20)],
            arcade.color.BLACK, 1))

        # Failure Case
        self.shape_list_fail = arcade.ShapeElementList()
        self.shape_list_fail.append(arcade.create_lines(
            [(140, 140), (160,120), (140, 110), (120,120)],
            arcade.color.BLACK, 2))

    def on_draw(self):
        arcade.start_render()
        # Success
        self.shape_list_pass.draw()
        # Fails with AssertionError
        self.shape_list_fail.draw()

if __name__ == "__main__":
    game = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
    game.setup()
    arcade.run()

```
### What should be added/changed?
Either remove line 48 in buffered_draw_commands.Shape or modify it to the following:
```
assert self.line_width >= 1
```
### What would it help with?
This will enable shapes to be drawn with a line thickness other than 1.

**Comment by einarf** [comment]
This is fixed in arcade 3.0. `create_lines` no longer take a line_width. Instead a thick line version of the function have been created.
