### ISSUE TITLE
Furo Sphinx theme renders an error on some pages using toctrees

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1923]
## Bug Report

Branch: tip of development on readthedocs
![image](https://github.com/pythonarcade/arcade/assets/36696816/cd03a9db-ecc6-4259-b759-e4f450797d59)
See https://api.arcade.academy/en/development/tutorials/shader_toy_particles/index.html

**Comment by sabadam32** [comment]
https://github.com/pythonarcade/arcade/pull/2010 ready for review

**Comment by sabadam32** [comment]
Went through all the docs and didn't see any other issues.
