### ISSUE TITLE
Add get/set/delete for moving platforms/walls on the physics engine

### ISSUE THREAD

**Issue by FriendlyGecko** [pythonarcade/arcade#1973]
## Enhancement request:

Adding properties to get/set/delete moving platforms and walls for the simple platformer physics engine registry just like the ladders list has.

### What should be added/changed?

The decorator properties with getters/setters/deleters

### What would it help with?
When devs want the option to manipulate the wall/moving platforms registry post init.

**Comment by einarf** [comment]
Merged 👍
