### ISSUE TITLE
Create cookiecutter game templates

### ISSUE THREAD

**Issue by sabadam32** [pythonarcade/arcade#2015]
## Enhancement request:
Create basic game templates using [`cookiecutter`](https://github.com/cookiecutter/cookiecutter).  The idea is to make usable templates for different game types that can be used in game jams and beginner projects.  These would be created in the [template](https://github.com/pythonarcade/template) repo.

### What should be added/changed?
- [ ] `pipx` install dependency
  - [ ] Documentation for installing pipx
  - [ ] possibly a helper script to just run to install pipx
- [ ] install `cookiecutter` via `pipx`
  - [ ] Documentation for installing the package using pipx
  - [ ] Possibly a helper script to install it
- [ ] Documentation for how to access and use the templates using cookiecutter commands.
##### Templates:
 - [ ] Template for a platformer
 - [ ] Template for a top down adventure

### What would it help with?
- First time game devs who need a solid base to build from
- Game Jams.
- Teaching kids to make games.

**Comment by einarf** [comment]
We also have the `arcade` command that supports a few sub-commands. One being copying the starter template. It was something I experimeted with a while ago. The idea was to add some new tools in there over time.

**Comment by sabadam32** [comment]
Oh yeah. That will do just fine for this. Thanks

**Comment by einarf** [comment]
It needs to be documented and possibly improved, but that's likely a post 3.0.0 thing.

**Comment by einarf** [comment]
I'm guessing this should be closed?

**Comment by sabadam32** [comment]
@einarf I opened this to get input on the templates.  Things like extending the arcade command and possibly what templates were on people’s wishlist would be good to know. We can close it if you want.  We can add more details on the implementation ticket
