### ISSUE TITLE
Documentation Issue: Contributing section on home page has alignment issues

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#2023]
## Bug / Documentation: 

TL;DR: The `Contributing` heading on the home page is ugly in full screen and half-screen views

### Replication steps

1. Check out the repo
2. `pip install -Ie .[dev]`
3. `./make.py serve`
4. Go to http://localhost:8000
5. Scroll down

####  Full screen
![image](https://github.com/pythonarcade/arcade/assets/36696816/73d575c9-af93-4e99-8561-d07b83df95ea)

#### Half screen
![image](https://github.com/pythonarcade/arcade/assets/36696816/cd2e233a-2b1d-4f65-a1f0-e0a306d77ee9)

**Comment by lbcai** [comment]
Taking care of this.
