### ISSUE TITLE
Promote using modern window/screen resolutions

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#2053]
Currently the default window size is 800 x 600. We should instead try to promote modern screen resolutions like 720p and 1080p. Arcade being a GPU based library don't really suffer much of a performance hit in the vast majority of cases with larger resolutions unless you are doing something heavy with shaders. Even older iGPUs handle the average arcade game more than fine in 1080p.

Suggesting a new default resolution of 1280 x 720. it would also be nice if examples could follow this but it might not be feasable to convert all of them. Just use common sense here. We don't want to spend weeks on this. It might also impact unit tests.

**Comment by DigiDuncan** [comment]
Agreed. I prefer 720p as a default since most people have 1080p monitors, and a 1080p window size will fill the screen or be annoyingly cut off. I developed Charm in 720p first before I added resizing.

**Comment by einarf** [comment]
Moved this to 3.o mandatory. Easy change but it can break stuff for users.

**Comment by einarf** [comment]
Merged:  https://github.com/pythonarcade/arcade/pull/2145
