### ISSUE TITLE
GUI: UIAnchorLayout doesn't respect width and height

### ISSUE THREAD

**Issue by alejcas** [pythonarcade/arcade#2091]
When setting a `UIAnchorLayout` with x,y, width and height, the Layout will ignore the width and the height and set them to the window width and height no matter what the user provided:

For example:

**Under a 800x600 window, here we create a Layout with x=600, y=0 and width=200 with height =500.**
**The layout will respect x and y, but ignore width and height**

```python
anchor = self.ui.add(UIAnchorLayout(x=600, y=0, width=200, height=500))
```

Full code reusing ht Gui UIAnchorExample:

```python
from __future__ import annotations

import arcade
from arcade.gui import UIManager
from arcade.gui.widgets import UIDummy
from arcade.gui.widgets.layout import UIAnchorLayout


class MyView(arcade.View):
    def __init__(self):
        super().__init__()
        self.ui = UIManager()

        anchor = self.ui.add(UIAnchorLayout(x=600, y=0, width=200, height=500))
        anchor.with_background(color=arcade.color.WHITE)

        anchor.add(
            child=UIDummy(),
            anchor_x="center_x",
            anchor_y="top",
        )

        anchor.add(
            child=UIDummy(),
            anchor_x="right",
            anchor_y="center_y",
        )

        anchor.add(
            child=UIDummy(),
            anchor_x="center_x",
            anchor_y="center_y",
        )

        anchor.add(
            child=UIDummy(),
            anchor_x="left",
            anchor_y="bottom",
        )

        anchor.add(
            child=UIDummy(),
            anchor_x="left",
            align_x=20,
            anchor_y="center_y",
        )

        anchor.add(
            child=UIDummy(),
            anchor_x="right",
            align_x=-40,
            anchor_y="bottom",
            align_y=40,
        )

    def on_show_view(self):
        self.window.background_color = arcade.color.DARK_BLUE_GRAY
        # Enable UIManager when view is shown to catch window events
        self.ui.enable()

    def on_hide_view(self):
        # Disable UIManager when view gets inactive
        self.ui.disable()

    def on_draw(self):
        self.clear()
        self.ui.draw()


if __name__ == "__main__":
    window = arcade.Window(800, 600, "UIExample", resizable=True)
    window.show_view(MyView())
    window.run()
```

**Comment by eruvanos** [comment]
Hi,

so the UIAnchorLayout has a default size_hint of (1, 1). ([API Doc](https://api.arcade.academy/en/development/api_docs/api/gui_widgets.html#arcade.gui.UIAnchorLayout))

Following the [layout algorithm](https://api.arcade.academy/en/development/programming_guide/gui/concept.html#layout-algorithm-by-example) the width and height are changed depending of the available space to 100% of its parent.

If you want to have a fix sized UIAnchorLayout, please do UIAnchorLayout(size_hint=None, ...).

Please close the issue if all questions are answered.

**Comment by alejcas** [comment]
If you run the example you will see that UIAnchor takes more than the space left on the screen. It exceeds the space. For me it’s completely counterintuitive.
It takes a 180% of the parent (screen).

**Comment by eruvanos** [comment]
I understand your argument and will take it as feedback for further improvements.
Right now it works like designed and documented.

The current behaviour allows use cases like collapsing sidebars or some simple scrolling implementations.
