### ISSUE TITLE
Minimap example broken: Minimap has some offset

### ISSUE THREAD

**Issue by eruvanos** [pythonarcade/arcade#2093]
## Bug Report
<img width="350" alt="image" src="https://github.com/pythonarcade/arcade/assets/9437863/f525a002-17d6-4fd6-860a-f2d488168b0a">

## System Info

Run this and paste the output here: `python -m arcade.examples.minimap`

### Hint

The offset might come from the camera changes. Drawing on the atlass just sets a projection maybe something is missing?

**Comment by einarf** [comment]
The initial state of the map looks like this for me 
![image](https://github.com/pythonarcade/arcade/assets/5418180/4db7badb-f174-411a-8bbb-92eee26dbd9c)

Is this still an issue or are we looking at mac thing here?

**Comment by DragonMoffon** [comment]
Could someone test this on mac? It is probably fixed with the recent camera updates

**Comment by eruvanos** [comment]
Will check

**Comment by eruvanos** [comment]
Everything works like expected
