### ISSUE TITLE
Fix in method _on_player_eos (arcade/sound.py)

### ISSUE THREAD

**Issue by albecst** [pythonarcade/arcade#2097]
I've been creating a 2D videogame with Arcade, and I've had some trouble stopping the sounds. Sometimes, randomly, the game would crash when we stopped (and the sound of the player's footsteps would stop), showing us this error:
```
File "...\Python\Python310\lib\site-packages\arcade\sound.py", line 87, in _on_player_eos media.Source._players.remove(player)
ValueError: list.remove(x): x not in list
```

You must check if there is a player (player: media.Player = media.Player()) to remove, so I'm about to open a PR to fix this.

**Comment by Cleptomania** [comment]
This is with Arcade 2.6, I'm wondering if this was a problem of the player getting cleaned up early by Pyglet that maybe doesn't happen in the current version of pyglet.

Regardless, a try/except for the ValueError is probably the best approach here.
