### ISSUE TITLE
Wrong numbering in docstings for platorm_tutorial examples 

### ISSUE THREAD

**Issue by VisualDudek** [pythonarcade/arcade#2119]
## System Info

Run this and paste the output here: python -m arcade

### Actual behavior:
No module named arcade.examples.platform_tutorial.11_animate_character

### Expected behavior:
should run example tutorila file

### Steps to reproduce/example code:
python -m arcade.examples.platform_tutorial.11_animate_character

### What should be added/changed?
correct docstrings in platform_tutorial files

e.g.  
python -m arcade.examples.platform_tutorial.11_animate_character
should be:
python -m arcade.examples.platform_tutorial.12_animate_character
(change 11 to 12)

### Where is it located?
arcade/examples/platform_tutorial/*.py

### What is wrong with it? How can it be improved?
whong docsting example how to run each example as a module
correct numbering

**Comment by einarf** [comment]
What version of arcade are you using? What docs are you looking at? Possibly there is some version confusion. We mainly care about 3.0 / development these days.

**Comment by VisualDudek** [comment]
Hi, thnx for replay
1) version of arcade (output of `python -m arcade`):
![image](https://github.com/pythonarcade/arcade/assets/30390538/05472109-ebec-4dda-88b0-d9c08dff5abe)
2) docs I am looging:
![image](https://github.com/pythonarcade/arcade/assets/30390538/f82e0157-0695-4f5c-99e5-f3f5efe689a2)
at following url: `https://api.arcade.academy/en/latest/examples/platform_tutorial/step_12.html`
in code block we can see following instruction:
![image](https://github.com/pythonarcade/arcade/assets/30390538/73b8987b-6eb8-4590-9019-59d832b108be)
BUT in package this file is named: `12_animate_character.py`
![image](https://github.com/pythonarcade/arcade/assets/30390538/674de58d-2f2d-4877-a76b-d34f0811c38f)

**Comment by VisualDudek** [comment]
As you have mentioned, on development brach it seems that it is fixed:
![image](https://github.com/pythonarcade/arcade/assets/30390538/947b4e1b-ab8e-4f33-a742-3cdc5dd060d2)
name of file in docstring is correct.

Srry for confusion, as it seems that it will be fixed in 3.0 we can close this issue.

**Comment by einarf** [comment]
No problem. You might as well use the 3.0 pre-release because it's already much more stable than 2.x. We are also likely to release very soon.
