### ISSUE TITLE
GUI: UIManger needs a camera

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#2162]
The `UIManager` must have its own camera instance. This used to be the case before the camera changes. Use 2.6 as a reference add back the `UIManager.camera` member. This can also be set by the user if they want. The UI will use this camera to transform mouse positions.

**Comment by einarf** [comment]
@eruvanos @DragonMoffon

**Comment by eruvanos** [comment]
@einarf  I merged the current stage, only rotation does not work. But I am not sure, what might be wrong. It could also be, that the camera still has a bug with it.

**Comment by einarf** [comment]
Created https://github.com/pythonarcade/arcade/issues/2197 so this doesn't get lost in the noise
