### ISSUE TITLE
Test the camera in UIManager

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#2197]
The new camera in `UIManager` is behaving oddly. For example rotation does not get applied.

We're suspecting this is related to lingering camera bugs. 

Related to #2162

**Comment by DragonMoffon** [comment]
did #2193 complete this?

**Comment by einarf** [comment]
https://github.com/pythonarcade/arcade/pull/2200 should fix lingering issues.

@eruvanos can you take a look and verify?

**Comment by eruvanos** [comment]
Will check, thanks

**Comment by eruvanos** [comment]
Works now <3 Thanks @DragonMoffon
