### ISSUE TITLE
GUI: Lingering blend issues

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#2203]
The gui could operate on the assumption that blending was always enabled in the past. This is no longer true. We need to go through the code and ensure the right states are set (enable/disable + blend func)

Example of widgets that lost their blending. The boat on the left has blending. The boat on the right is part of the gui and apparently no longer blend properly.

These are using `UIImage(texture=unit.texture, width=32, height=32)`

![image](https://github.com/pythonarcade/arcade/assets/5418180/a4076188-b083-4e60-8a59-3e5ce090b301)

**Comment by einarf** [comment]
This is an issue from @alejcas's project. 

Think I figured out what's happening here. Blending is getting completely disabled causing some images to be alpha masked instead of alpha blended. I'll jump on this possibly tomorrow.

**Comment by einarf** [comment]
@alejcas can you test with the current dev branch now? I think we found the issue. Alpha values was boosted by 255 instead of normalized 0.0 -> 1.0. This would obviously mean that alpha blending would work just like alpha testing, something that is consistent with your screenshot.

**Comment by alejcas** [comment]
> @alejcas can you test with the current dev branch now? I think we found the issue. Alpha values was boosted by 255 instead of normalized 0.0 -> 1.0. This would obviously mean that alpha blending would work just like alpha testing, something that is consistent with your screenshot.

Yep that fix it!

**Comment by einarf** [comment]
Declared as fixed \o/
