### ISSUE TITLE
`get_angle_degrees` possibly broken

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#2238]
Looking at the the easing example we can see the ship facing the wrong direction. `arcade\examples\easing_example_2.py`

It's using `get_angle_degrees` to get the angle between two points and that definitely fails by 90 degrees. I think this broke when we changed the rotation direction? Should this function return clokswise angles or not?

**Comment by DragonMoffon** [comment]
The issue is in that example; it works correctly if you look at the `turn and move` example.

**Comment by DragonMoffon** [comment]
https://github.com/pythonarcade/arcade/assets/86714785/9e0a7095-c03e-4f5e-90e3-859540f5e089
Are you sure it's broken?
