### ISSUE TITLE
Headless fails on 3.0.0.dev31

### ISSUE THREAD

**Issue by JackAshwell11** [pythonarcade/arcade#2323]
When running tests in CI on headless mode, the following stack trace is thrown:
```
ImportError while loading conftest '/home/runner/work/Hades/Hades/tests/conftest.py'.
tests/conftest.py:25: in <module>
    WINDOW: Final[Window] = Window()
.nox/tests-3-12/lib/python3.12/site-packages/arcade/application.py:208: in __init__
    super().__init__(
.nox/tests-3-12/lib/python3.12/site-packages/pyglet/window/__init__.py:567: in __init__
    self._create()
.nox/tests-3-12/lib/python3.12/site-packages/pyglet/window/headless/__init__.py:110: in _create
    self.context.attach(self.canvas)
.nox/tests-3-12/lib/python3.12/site-packages/pyglet/gl/headless.py:131: in attach
    super().attach(canvas)
.nox/tests-3-12/lib/python3.12/site-packages/pyglet/gl/base.py:266: in attach
    raise RuntimeError(msg)
E   RuntimeError: Cannot attach <pyglet.display.headless.HeadlessCanvas object at 0x7fce58069760> to HeadlessContext(id=140524185915456, share=None)
```
No code changes were made to these tests before the update to Arcade 3.0.0.dev31

**Comment by bcorfman** [comment]
Any idea of which versions of Arcade & Pyglet allowed headless tests to still work, while we're waiting for this bug to be fixed?

**Comment by JackAshwell11** [comment]
> Any idea of which versions of Arcade & Pyglet allowed headless tests to still work, while we're waiting for this bug to be fixed?

I'm currently using Arcade 3.0.0.dev30 which works fine, haven't tried it with the latest versions

**Comment by einarf** [comment]
I will try to figure out what happened in pyglet 2.1. They did some refactoring that broke something I think.

**Comment by benmoran56** [comment]
This is a long time coming, but now fixed in pyglet. It will be in the next point release.

**Comment by pushfoo** [comment]
Thank you!

**Comment by benmoran56** [comment]
pyglet v2.1.rc1 is now out, which contains this fix.

**Comment by einarf** [comment]
`3.0.0.dev39` released using the new pyglet version fixing this problem
