### ISSUE TITLE
After upgrading to arcade 3.0 clicking New Game button no longer takes me to GameView

### ISSUE THREAD

**Issue by j-baxter2** [pythonarcade/arcade#2331]
I have upgraded to 3.0.0dev32 and upgraded pyglet to 2.1dev5. But now when I click new game in my MenuView:

MenuView.on_hide_view is executed
GameView.on_show_view is executed
And the event loop starts for GameView

But the menu buttons are still shown on the screen, and the background colour is still that of MenuView. Here is a link to the upgrading to arcade 3 branch:

https://github.com/j-baxter2/HKU/tree/upgrading-to-arcade-3

**Comment by eruvanos** [comment]
So I tried to get your example running, but it shows an error, that arcade does not have a Camera:

```
  File "/.../HKU/src/utils/camera.py", line 4, in <module>
    class HKUCamera(arcade.Camera):
                    ^^^^^^^^^^^^^
AttributeError: module 'arcade' has no attribute 'Camera'. Did you mean: 'camera'?
```

Can you run: `python -m arcade`

**Comment by eruvanos** [comment]
and check if it still works on your side?

**Comment by eruvanos** [comment]
Hi what I can see is, that the usage of sections is different then described within the documentation.

It looks like the setup of the sections produce a infinit loop. I ask the sections author to check. In general I would recommend to check the docs, how to use sections:
https://api.arcade.academy/en/development/programming_guide/sections.html

**Comment by j-baxter2** [comment]
Hi Maic. Thank you for your help, note that I have a branch called upgrading to arcade 3 where I have change camera to camera2d etc, but then I hit a wall. I feel that this change to how sections are handled may be it… I am out today, so I will try when I have time and let you know!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by eruvanos** [comment]
Already deleted the initial comments 😅

**Comment by eruvanos** [comment]
Usage of section manager created a infinite loop.
