### ISSUE TITLE
Allow tuple scale in arcade.Sprite init, same as the setter

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#2399]
### What should be added/changed?

The `scale` argument to `arcade.Sprite.__init__` is a float (https://github.com/pythonarcade/arcade/blob/development/arcade/sprite/sprite.py#L73) but the getter for the `scale` property returns a tuple and the setter for it accepts both tuple and float (https://github.com/pythonarcade/arcade/blob/development/arcade/sprite/base.py#L310). 

I would like the `scale` argument to `__init__` to work the same way as the property setter, so it accepts both a 2-tuple and a float. 

### What would it help with?

I can easily pass the scale of one sprite to the init of a new sprite, same as I could in older versions of arcade (before the scale getter started to return a tuple).

**Comment by einarf** [comment]
It should accept both. There is a PR about to be merged that also adds performant methods to do uniform scaling and other scaling cleanup. The new scale property that was initially added returns a `Vec2`, but this was such a huge impact on performance (4-5x more costly) we had to find another way.

I will put this on 3.0 mandatory in case this change was not added in the subclass.
