### ISSUE TITLE
Add optional `view` argument to `Window.run()' and `arcade.run()`

### ISSUE THREAD

**Issue by DragonMoffon** [pythonarcade/arcade#2400]
To help promote subclassing views over the window itself, we should add an optional view argument to the run methods, letting them automatically call `Window.show_view`.

It results in only a one-line change, but it makes the DX (Developer Experice) nicer.

It will also need a unit test for each method, and the examples will need updating to take advantage of the change.

**Comment by joaomarcalst** [comment]
I’ve submitted a pull request to add the optional view argument to Window.run() as discussed. While implementing, I encountered some issues with pyglet that prevented complete testing, but the initial functionality is in place. Let me know if any adjustments are needed!
