### ISSUE TITLE
Proposal: Add Portuguese Language Support for Documentation and Tutorials

### ISSUE THREAD

**Issue by joaomarcalst** [pythonarcade/arcade#2449]
### What should be added/changed?
The Arcade documentation should include a Portuguese language option, adding to the currently available English, German, and Swedish versions. This enhancement would involve a structured translation of all essential learning materials and guides into Portuguese.

### What would it help with?
Adding Portuguese documentation would increase accessibility and usability for Portuguese-speaking users, particularly in countries such as Brazil and Portugal, where there is significant interest in software development and gaming. This would also likely expand the Arcade community and encourage more contributions from a broader, linguistically diverse audience. Furthermore, it aligns with the project’s educational goals by breaking language barriers, helping new learners, and promoting Arcade usage in regions with high growth potential in game development and coding education.

### What documentation needs to change? 
The main [Arcade documentation](https://learn.arcade.academy/en/latest/) hosted in the “learn” section of the official website should be extended to support a Portuguese version. And, afterwards, extends to all documents in the site.

### Where is it located?
The documentation is hosted at https://learn.arcade.academy/en/latest/, covering a wide range of resources such as tutorials, API references, and beginner guides.

### What is wrong with it? How can it be improved?
Currently, the documentation does not include Portuguese, limiting its accessibility to Portuguese-speaking users who might struggle with English or other supported languages. By introducing Portuguese documentation, we could significantly enhance accessibility and inclusivity. This improvement will enable more users to learn and utilize Arcade effectively, potentially contributing new ideas and strengthening the project’s global reach. Adding Portuguese would also align with educational inclusivity goals and make Arcade a more widely adopted framework in underrepresented communities in open-source and gaming projects.

**Comment by einarf** [comment]
This can also apply for other languages. We don't currently have a pipeline for handling translations. If we get enough volunteers and interest in this after 3.0 it's definitely interesting. It all depends on volunteers. Currently the docs are under a huge revamp and we'll probably do a lot of doc work from 3.0 to 3.1 so things will hopefully be more stable.

The sheer amount of text that needs translation is a concern.

**Comment by joaomarcalst** [comment]
That's great, I'll be grateful to help you in that! Just send me a message.
