### ISSUE TITLE
the pytiled_parser dependency and A Path Forward™

### ISSUE THREAD

**Issue by Beefy-Swain** [pythonarcade/arcade#655]
I raised some of these points and concerns in an email to @pvcraven but figured I'd post it here for posterity.

I have resumed work on [pytiled_parser](https://github.com/Beefy-Swain/pytiled_parser), and we can expect some substantial API changes to come of that in the medium term.

My primary goal at this stage is to reach 100% branch coverage of what already exists (we are at 70% right now, but the low-hanging fruit has mostly been picked. I literally spent 2 hours yesterday increasing code coverage by two lines). This should only result in minimal API changes.

The next step would be working towards 100% TMX parsing. Right now we have a fairly large amount of the TMX format covered, maybe 70%. The largest pieces left (AFAIK) are [Template Files](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#template-files), isometric, and hex maps. This will likely result in a few major refactors and a major overhaul of the public API.

Once 100% TMX parsing is achieved, pytiled_parser will reach version 1.0.0 and it will start abiding by [semantic versioning](https://semver.org/), but until then things will be somewhat fast and loose. 

In consideration of that, challenges this poses to the Arcade project as I can predict are two fold:
1. locking specific versions of Arcade to specific versions of pytiled_parser
1. 100% branch coverage of all pytiled_parser related code within the Arcade library to prevent regression when using newer versions of pytiled_parser with it.
1. 100% branch coverage of all pytiled_parser related tutorials in the Arcade project documentation

The first of these should be quite simple to do, but it could cause retroactive issues with anyone using an older version of Arcade when they inadvertently get an incompatible version of pytiled_parser with it.

I am unsure how difficult the second and third challenges will be, as I have not been all that involved with this project since pytiled_parser was integrated into it. I am here now though, and ready to dive back in. Interested to hear input on this.

**Comment by pvcraven** [comment]
I'd say make whatever changes are appropriate in the parser. I'm guessing to the end Arcade user, the API won't change much. If we are lucky we'll just need to make changes to the Arcade code <-> Pytiled interface. Any maybe expose new functionality to the Arcade user.

**Comment by Beefy-Swain** [comment]
I will be honest, I have not done much at all with Arcade since I returned from my hiatus, so it's hard for me to say for certain what will be required. That's why I want to get a testing suite for anything relevant banged out.

I'm happy to work on that on the Arcade side, but the first step for me is to reach 100% coverage of pytiled_parser. There is a lot of stuff in it that was never tested at all, and does not work.

**Comment by einarf** [comment]
Probably a good idea to release a 2.3.x with `pytiled-parser` pinned to the specific release working right now and merge that into experimental branch.

**Comment by einarf** [comment]
@Beefy-Swain If `pytiled-parser` has a simple way to query the package version that might help the transition. Like a `__version__` in the package root for example.

**Comment by Beefy-Swain** [comment]
@einarf currently the version is stored in the package metadata: `setup.cfg`

I see no issue with adding a __version__ attribute to the package in accordance with [PEP 396](https://www.python.org/dev/peps/pep-0396/)

**Comment by pvcraven** [comment]
There's a new branch 'tmx_library_update' that I'm using for writing unit tests, and making sure that we are working with the new tmx updates.

**Comment by Beefy-Swain** [comment]
Perfect, thanks!

**Comment by benjamin-kirkbride** [comment]
Major update:

pytiled_parser is now at 95% test coverage: The only parts of the Tiled Map spec that is currently unimplemented are Wang Sets and Projects (the project feature is about a month old at this point).

We have begun integrating into Arcade. The way this will work is we are tearing out everything that exists now, and creating a sub-packaged called `tiled`, this package will `from pytiled_parser import *` and will also include any helper functions and arcade integrations that are out of the scope of the pytiled_parser project itself.

The major thing to note, beside a complete change to the API, is that pytiled_parser now uses `JSON` formatted maps and tilesets, instead of the XML `TMX` and `TSX` formats. This change, while somewhat inconvenient from a documentation update standpoint, allowed us to completely re-write pytiled_parser with nearly full support for all features of Tiled in less time than it was taking to add even one new feature to the TMX version.

**Comment by benjamin-kirkbride** [comment]
@einarf `__version__` has been added to pytiled_parser
