### ISSUE TITLE
Use pyglet 2.0

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#666]
**Benjamin**: There are a handful of workarounds in the codebase still that don't really apply to modern GL. I removed most of them for pyglet 2.0 already.
Actually, it's probably better to target pyglet 2.0 for arcade at this point.
It has greatly improved joystick support, with a new GameController API. That seems pretty useful for the target audience.

**Comment by Cleptomania** [comment]
We’re using pyglet 2.0 now but it’s a dev version, should this stay open until we switch to a full Pyglet release?

**Comment by einarf** [comment]
We can definitely close this for now.
