### ISSUE TITLE
Consider making a 2D camera

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#669]
Supporting smooth scrolling and zoom. Can be extended.

**Comment by CodeForeverAndEver** [comment]
Some things to consider:

- Camera implemented in `arcade.Camera2D`
- Implementing a way for the camera to follow the player (maybe pass player as argument to the camera)
- Ability to access the camera `x` and `y` coordinates, that can be added and subtracted from
- Separate world and screen space
- Method of Camera class to convert mouse coordinates from world to screen
- Would be nice if `arcade.set_background` was changed to `arcade.Camera2D.set_background`

Most of these ideas are coming from what the `Unity` game engine has. Here is a link to the documentation on the Camera: https://docs.unity3d.com/Manual/class-Camera.html

Hope these ideas are useful :D

**Comment by CodeForeverAndEver** [comment]
Some more things:

- Color filters
- Ability to automatically take screenshot

Also, here is a link to the PyGame camera. They have some good ideas: https://www.pygame.org/docs/tut/CameraIntro.html 

:D

**Comment by CodeForeverAndEver** [comment]
Something else to add might be a `mask object`.

When it is placed over something it can hide or reveal something else. An example in [this video from BlackThornProd](https://www.youtube.com/watch?v=4pl8DcsCQ_k).

**Comment by pvcraven** [comment]
I'm so confused, the pygame camera is for interfacing with an actual camera, isn't it?

**Comment by CodeForeverAndEver** [comment]
Yeah, looks like it is. However, some of the things they do could be applied; like colorspacing.

**Comment by Cleptomania** [comment]
There's now `arcade.Camera` in the dev branch for 2.6 release that gets us 90% of the way there. I'll close this now in favor of new issues to track specific features we might want to add to it later on.
