### ISSUE TITLE
tmx maps with terrain map fails with error

### ISSUE THREAD

**Issue by pvcraven** [pythonarcade/arcade#730]
Terrain map brushes aren't supported. Make a better error.

**Comment by benjamin-kirkbride** [comment]
They will be soon ;)

**Comment by einarf** [comment]
Can this be closed?

**Comment by Cleptomania** [comment]
pytiled-parser now supports this, but there is no support for it in Arcade. I don't believe there is any kind of sensible error message if you try to use them, so we could maybe add that for now.

**Comment by Cleptomania** [comment]
Can confirm arcade will support terrain brushes with the upcoming 2.6 release. Terrain brushes are working in the development branch now.

The terrain stuff basically just gets converted into regular tiles as far as map rendering is concerned so it works just as any other regular tile map does.

**Comment by einarf** [comment]
Reopned with 2.6 milestone and "Fix wating for release" tag

**Comment by Cleptomania** [comment]
Released with 2.6.0
