### ISSUE TITLE
Tilesets using sprite sheets with margin/spacing not supported

### ISSUE THREAD

**Issue by xlatb** [pythonarcade/arcade#731]
### Actual behavior:

Tiled map editor and pytiled_parser support margin/spacing between sprite sheet elements (i.e. borders and grid lines). Arcade ignores these when creating sprites from a tileset's sprite sheet. This causes the sprites cut from the sprite sheet to be misaligned.

### Expected behavior:

Arcade would account for the margin and spacing when calculating image coordinates within the sprite sheet.

**Comment by benjamin-kirkbride** [comment]
This will be fixed as part of the new pytiled_parser release

**Comment by xlatb** [comment]
@Beefy-Swain I believe it was already fixed [here](https://github.com/pythonarcade/arcade/pull/732/commits/ebd3b9e2cf9581ef8f0eb10f32bc38782b299f27)?

Seems to me that pytiled_parser already parses this data, but the underlying problem was that Arcade was ignoring it in its calculations.

**Comment by Cleptomania** [comment]
@xlatb pytiled_parser has recently undergone a complete re-write, and we are in the stages of re-writing the arcade integration of pytiled_parser.

This is a feature that is supported in pytiled_parser as of now and will be implemented in the arcade integration that is coming as a part of the re-write.

One of pytiled_parser’s main test tilesets uses both margins and spacing so this is definitely a feature that will be supported.

I can’t speak much to if this feature is supported/working in the current release or not though.

**Comment by pvcraven** [comment]
Should be fixed in 2.4.2
