### ISSUE TITLE
PyInstaller not working with Windows 10 -- not loading the resource files properly.

### ISSUE THREAD

**Issue by FalconFX9** [pythonarcade/arcade#737]
## Bug Report
I've been trying to make an executable using PyInstaller, and I have had no success, including by using the given PyInstaller example (I know that it was only tested on Windows 7, but the issue doesn't seem related to that?).
### Actual behavior:
I get this error when trying to run the EXE: FileNotFoundError: Cannot locate resource : C:\Users\username\AppData\Local\Temp\_MEI232402\arcade\resources\shaders\shapes\line\line_vertex_shader_vs.glsl
### Expected behavior:
Have the generated EXE run.
### Steps to reproduce/example code:
Using the example code with the example batch file (only the pyinstaller command), and manually copying and pasting the avbin.dll, avbin64.dll, chipmunk.dll and resource folder to the directory with the example.

PyInstaller command used:
pyinstaller --exclude-module tkinter --add-data resources;resources --add-data ./avbin64.dll;. --add-data ./avbin.dll;Win64 --onefile sample.py

PyInstaller message when compiling:

90 INFO: PyInstaller: 3.6
90 INFO: Python: 3.8.3
92 INFO: Platform: Windows-10-10.0.19041-SP0
93 INFO: wrote C:\Users\username\PycharmProjects\Generation Game Jam Platformer\sample.spec
95 INFO: UPX is not available.
97 INFO: Extending PYTHONPATH with paths
['C:\\Users\\username\\PycharmProjects\\Generation Game Jam Platformer',
 'C:\\Users\\username\\PycharmProjects\\Generation Game Jam Platformer']
98 INFO: checking Analysis
98 INFO: Building Analysis because Analysis-00.toc is non existent
99 INFO: Initializing module dependency graph...
102 INFO: Caching module graph hooks...
109 INFO: Analyzing base_library.zip ...
2341 INFO: Processing pre-find module path hook   distutils
2342 INFO: distutils: retargeting to non-venv dir 'c:\\users\\username\\appdata\\local\\programs\\python\\python38\\lib'
4355 INFO: Caching module dependency graph...
4473 INFO: running Analysis Analysis-00.toc
4489 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\username\appdata\local\programs\python\python38\python.exe
4571 INFO: Analyzing C:\Users\username\PycharmProjects\Generation Game Jam Platformer\sample.py
7173 INFO: Processing pre-find module path hook   site
7174 INFO: site: retargeting to fake-dir 'c:\\users\\username\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\fake-modules'
8171 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
13227 INFO: Processing module hooks...
13227 INFO: Loading module hook "hook-distutils.py"...
13231 INFO: Loading module hook "hook-encodings.py"...
13297 INFO: Loading module hook "hook-lib2to3.py"...
13301 INFO: Loading module hook "hook-numpy.core.py"...
13448 INFO: Loading module hook "hook-numpy.py"...
13449 INFO: Loading module hook "hook-PIL.Image.py"...
13724 INFO: Loading module hook "hook-PIL.py"...
13726 INFO: Import to be excluded not found: 'FixTk'
13726 INFO: Excluding import 'PyQt5'
13729 INFO:   Removing import of PyQt5 from module PIL.ImageQt
13729 INFO: Excluding import 'tkinter'
13731 INFO:   Removing import of tkinter from module PIL.ImageTk
13732 INFO: Import to be excluded not found: 'PyQt4'
13732 INFO: Import to be excluded not found: 'PySide'
13732 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
13735 INFO: Import to be excluded not found: 'FixTk'
13735 INFO: Excluding import 'tkinter'
13737 INFO: Loading module hook "hook-pkg_resources.py"...
14155 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
14205 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
14254 INFO: Excluding import '__main__'
14255 INFO:   Removing import of __main__ from module pkg_resources
14256 INFO: Loading module hook "hook-pycparser.py"...
14257 INFO: Loading module hook "hook-pydoc.py"...
14258 INFO: Loading module hook "hook-setuptools.py"...
14748 INFO: Loading module hook "hook-sysconfig.py"...
14749 INFO: Loading module hook "hook-xml.dom.domreg.py"...
14750 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
14751 INFO: Loading module hook "hook-xml.py"...
14800 INFO: Looking for ctypes DLLs
15396 WARNING: library wintab32.dll required via ctypes not found
15550 INFO: Analyzing run-time hooks ...
15557 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
15560 INFO: Including run-time hook 'pyi_rth_pkgres.py'
15582 INFO: Looking for dynamic libraries
16120 INFO: Looking for eggs
16120 INFO: Using Python library c:\users\username\appdata\local\programs\python\python38\python38.dll
16122 INFO: Found binding redirects:
[]
16134 INFO: Warnings written to C:\Users\username\PycharmProjects\Generation Game Jam Platformer\build\sample\warn-sample.txt
16263 INFO: Graph cross-reference written to C:\Users\username\PycharmProjects\Generation Game Jam Platformer\build\sample\xref-sample.html
16288 INFO: Appending 'datas' from .spec
16330 INFO: checking PYZ
16330 INFO: Building PYZ because PYZ-00.toc is non existent
16331 INFO: Building PYZ (ZlibArchive) C:\Users\username\PycharmProjects\Generation Game Jam Platformer\build\sample\PYZ-00.pyz
17651 INFO: Building PYZ (ZlibArchive) C:\Users\username\PycharmProjects\Generation Game Jam Platformer\build\sample\PYZ-00.pyz completed successfully.
17677 INFO: checking PKG
17677 INFO: Building PKG because PKG-00.toc is non existent
17678 INFO: Building PKG (CArchive) PKG-00.pkg
26471 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
26490 INFO: Bootloader c:\users\username\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
26491 INFO: checking EXE
26491 INFO: Building EXE because EXE-00.toc is non existent
26492 INFO: Building EXE from EXE-00.toc
26492 INFO: Appending archive to EXE C:\Users\username\PycharmProjects\Generation Game Jam Platformer\dist\sample.exe
26530 INFO: Building EXE from EXE-00.toc completed successfully.

Full pyinstaller message (when running .exe):

C:\Users\username\PycharmProjects\Generation Game Jam Platformer\dist>sample.exe
SoLoud dynamic link library C:\Users\username\AppData\Local\Temp\_MEI232402\arcade\soloud/soloud_x64 not found. Failed to load dynlib/dll 'C:\\Users\\username\\AppData\\Local\\Temp\\_MEI232402\\arcade\\soloud/soloud_x64'. Most probably this dynlib/dll was not found when the application was frozen.
Warning, can't initialize soloud name 'soloud_dll' is not defined. Sound support will be limited.
Traceback (most recent call last):
  File "sample.py", line 35, in <module>
  File "sample.py", line 20, in main
  File "site-packages\arcade\application.py", line 576, in open_window
  File "site-packages\arcade\application.py", line 119, in __init__
  File "site-packages\arcade\context.py", line 34, in __init__
  File "site-packages\arcade\context.py", line 164, in load_program
  File "site-packages\arcade\resources\__init__.py", line 30, in resolve_resource_path
FileNotFoundError: Cannot locate resource : C:\Users\username\AppData\Local\Temp\_MEI232402\arcade\resources\shaders\shapes\line\line_vertex_shader_vs.glsl
[22032] Failed to execute script sample

**Comment by einarf** [comment]
It belives arcade is located in `C:\Users\username\AppData\Local\Temp_MEI232402\arcade`. We load package resources based on where the python file reports itself to be located. I have no idea if this is the right location.

**Comment by FalconFX9** [comment]
I think that is normal behavior though, as when the .exe is launched, it creates a directory in TEMP with all the required libraries, in order for the app to be fully standalone. The error seems to be caused by the fact that it isn't including the libraries properly/not fully loading it, despite it being part of the resources folder that I added in the pyinstaller command.

**Comment by FalconFX9** [comment]
Ok, after a lot of tinkering I ended up getting it to work. Ended up including the entire arcade library folder instead of just the 'resources' folder as suggested in the PyInstaller example.
