### ISSUE TITLE
Filter out tests for resizing

### ISSUE THREAD

**Issue by benjamin-kirkbride** [pythonarcade/arcade#739]
Several of the tests rely on window geometry, but this does not work if you are using a tiled window manager such as i3.

These tests should be skippable with a flag.

**Comment by benjamin-kirkbride** [comment]
This was done with commit e7bc5c5866bbaedb98feeda29ea75bf24e736af1

**Comment by Cleptomania** [comment]
The tests were not actually filtered out in there, that commit merely added a fixture to pytest that can be used to filter the tests.

**Comment by Cleptomania** [comment]
Done with commit 8440165cb20b9dbee3bef5686d9ccffe2390bdc7
