### ISSUE TITLE
SpriteList uses statefull iteration

### ISSUE THREAD

**Issue by eruvanos** [pythonarcade/arcade#741]
SpriteList uses statefull iterator, which shows strange behavior if nested loops are used.

# Reproduce

```
sprites = SpriteList()
# add sprites...
for sprite in sprites:
  print(sprite)
  # do something that also loops over all sprites
  list(sprites)
```

## Expected behavior:
Loop over all sprites and print them

## Actual:
Prints first sprite, than stops.
I had a look on the __iter__ function of SpriteList:

## Details
Representative example code of SpriteList iter implementation

```
class XList:
    def __init__(self, *args):
        self.elements = args

    def __iter__(self) -> 'XList':
        """ Return an iterable object of sprites. """
        self._iterator = iter(self.elements)
        return self

    def __next__(self) -> int:
        """ Get next item """

        return next(self._iterator)


x_list = XList(1, 2, 3, 4)
for x in x_list:
    print(x)
    list(x_list)
```

**Comment by einarf** [comment]
`__iter__` could just return a new `SpriteIterator` instance instead with its own local iterator.

**Comment by eruvanos** [comment]
I agree.

```
class XList:
    def __init__(self, *args):
        self.elements = args

    def __iter__(self) -> 'XList':
        """ Return an iterable object of sprites. """
        return iter(self.elements)
```

Should fix it. Could you think of some place where the old behavior is intended?

**Comment by pvcraven** [comment]
> Should fix it. Could you think of some place where the old behavior is intended?

I can't.

**Comment by eruvanos** [comment]
Shall I create a pull request or maybe fix it directly? Or are you already on it?

**Comment by pvcraven** [comment]
If you have the time. School is starting up, so it'll be a while before I get to it.
