### ISSUE TITLE
SoLoud vs Pyglet for Audio

### ISSUE THREAD

**Issue by Cleptomania** [pythonarcade/arcade#742]
SoLoud has fairly lack-luster support on Linux if you are not running a bleeding edge distro. It has a glibc dependency which at the time of writing is not in the most recent version of Debian(10) or the current LTS version of Ubuntu(18.04). Due to the version of glibc shipped with the distro being used by a number of core systems, it is ill-advised to be upgrading it, at least if you need your system to be stable.

It seems as though there are other issues with SoLoud on Linux but I don't have any personal experience with it as I've not even been able to get it to run.

After a skim through Arcade's sound module, it doesn't appear that we're doing anything that Pyglet's audio library can't do. Seeing as Pyglet is already a core dependency of Arcade, it would make sense to use the audio library from that. SoLoud seems like it would be a lot more complex to maintain as time goes on and updates happen to SoLoud, and it doesn't seem like there's a benefit over a simpler solution like Pyglet.

**Comment by einarf** [comment]
I'm also a fan of using `pyglet.media` to make things simple. Playback of 16 bit wav as `StaticSource` is pretty solid. There probably a long story as to why soloud was used. The pyglet player had a lot of problems in the past, but recent improvements in 1.5.x have made it a viable candidate again.

**Comment by Cleptomania** [comment]
It seems that Pyglet supports using FFmpeg to support better audio formats. It appears that you can bundle FFmpeg directly with your project as outlined here:

https://pyglet.readthedocs.io/en/latest/programming_guide/media.html

**Comment by pvcraven** [comment]
I'm not against a PR on this, but it has to work reliably on all platforms and include mp3 and ogg support. I've wasted so much time with ffmpeg libraries and sound I personally don't want to mess with it again for quite a while.

I'm not ok having a seperate ffmpeg install required by mac or windows. Has to be bundled.

**Comment by Cleptomania** [comment]
I've submitted a pull request for this here #746

**Comment by Cleptomania** [comment]
This has been finished and merged in with the 2.5 release of Arcade
