### ISSUE TITLE
Loading individual textures make gameplay animation slow

### ISSUE THREAD

**Issue by arafat-ar13** [pythonarcade/arcade#747]
# Error

So I am making a simple platformer adventure game using the Arcade library. I am liking the Object-Oriented design of the framework. Now, in my game, the main character has to carry out a bunch of different textures like walking, jumping, attacking with sword, etc. And each texture will also be paired with the same texture but flipped horizontally. The main error that I am facing is that the game is very slow at the beginning. After a little observation, I found that whenever the game loaded the textures real-time, gameplay becomes really slow. But as I said, this lasts for some initial amount of time. This goes for all the different textures: walking, jumping. For example, when I run my code and the game shows up, if I try to walk, the game gets really slow since it loads all the different walking textures. After I have walked a bit, the game speeds up to normal and becomes playable again. All the other textures all have this slow loading time initially. 

I wish this slowness was negligible in the way that it lasted a few milliseconds, but the slowed performance is very much noticeable. I have thought of a couple of reasons this could be occurring:
* My computer itself is quite dated and slow. But I doubt this because my game ran perfectly smoothly when there were no texture animations
* I have written code in a way that takes up a ton more resources than it actually needs.

Given my second point, it should be noted that I followed the official documentation code from [arcade.academy](https://arcade.academy) on how to animate my sprites. 

This was all the info I had to give about the error I am having. Now, since this game has several different files, I am afraid I cannot include a few lines of code to show my code. It is my utmost request that my GitHub repository [on the game be checked out](https://github.com/arafat-ar13/Forest-Knight). The source code directory contains all the code I have written. I suggest that the player's `update_animation()` method be checked out. 

So, I am requesting anyone who can to help out a buddy here. Any kind of help or suggestion or idea is highly appreciated. Thank you so much in advance.

**Comment by pvcraven** [comment]
You need to pre-load the textures at start-up. User `arcade.load_texture` to load them on start-up, and then add all your textures to `Sprite.textures`. (Specific to your instance.)

**Comment by arafat-ar13** [comment]
Hello sir, you have my greatest appreciations for taking the time to reply. But I would like to include this code snippet.

```
import arcade

def load_texture_pair(filename):
    """ Given a filename, will load a pair of texture images, one is flipped horizontally """
    return [
        arcade.load_texture(filename),
        arcade.load_texture(filename, flipped_horizontally=True)
    ]

def load_textures(filename, asset_count):
    """
    Load bunch of pairs of textures quickly using this function. 
    """
    textures = []
    for count in range(1, asset_count+1):
        new_filename = filename.replace("<asset_count>", str(count))
        texture = load_texture_pair(new_filename)
        textures.append(texture)

    return textures
```
And here is a little snippet of the main Knight class:
```
class Knight(arcade.Sprite):
    def __init__(self):
        super().__init__()

        # Knight postion and scaling
        self.center_x = 124
        self.center_y = 124
        self.scale = CHARACTER_SCALE

        # Loading all the different textures of the Knight
        self.idle_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Idle (<asset_count>).png", 10)
        self.walking_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Walk (<asset_count>).png", 10)
        self.running_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Run (<asset_count>).png", 10)
        self.jumping_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Jump (<asset_count>).png", 10)
        self.attack_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Attack (<asset_count>).png", 10)
        self.dying_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Dead (<asset_count>).png", 10)
```

As you can see from the above code, I am already loading the textures using `arcade.load_texture()` and then storing them for later use, for example, `self.walk_textures`.
So, the textures are loaded in the `init()` method and the class `Knight()` is instantiated in the `setup()` method of the main `arcade.Window` subclass .

I would also like to include just a little bit of the `update_animatiion()` code of the Knight class:
```
 def update_animation(self):
        """ Method that updates the animation of the Knight using the loaded textures """

        # First, let's figure out how the Knight moves and set it's face direction accordingly
        if self.change_x < 0 and self.face_direction == KNIGHT_FACE_RIGHT:
            self.face_direction = KNIGHT_FACE_LEFT
        elif self.change_x > 0 and self.face_direction == KNIGHT_FACE_LEFT:
            self.face_direction = KNIGHT_FACE_RIGHT

        # Walking animation
        if self.change_x > 0 or self.change_x < 0:
            self.cur_texture += 1
            if self.cur_texture >= len(self.walking_textures) * UPDATES_PER_FRAME:
                self.cur_texture = 0
            self.texture = self.walking_textures[self.cur_texture //
                                                 UPDATES_PER_FRAME][self.face_direction]
```
And the `update_animation()` is also called in the `on_update()` method of the main Game Window.

So, you can see that my code is quite similar to the official guide from Arcade's web documentation. Yet, the loading of textures is very slow whereas if I run the code from Arcade's website, the animations are flawlessly smooth. So, can you please help me out with this one? Thanks a bunch for replying and I am eager to hear from you soon.

**Comment by pvcraven** [comment]
It isn't just loading the textures.

The SpriteList class takes all the textures from the sprites in the list, and combines them into one big image. The SpriteList has to know about those textures, or it recreates the big image each time you add in a new texture as being drawn in the SpriteList.

So you can have loaded the textures already, but SpriteList doesn't know about them, and they aren't part of the internal sprite sheet that SpriteList creates. Therefore it recreates the sprite sheet with each new image.

They need to be loaded into one of the sprite's `textures` list, so the SpriteList knows to pick them up. Any other list, and it doesn't know.

**Comment by arafat-ar13** [comment]
Thank you for replying again. Can you just please let me know in what way should I add all my textures to `self.textures`. This is what I have done:
```
        self.textures = []

        # Loading all the different textures of the Knight
        self.idle_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Idle (<asset_count>).png", 10)
        self.walking_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Walk (<asset_count>).png", 10)
        self.running_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Run (<asset_count>).png", 10)
        self.jumping_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Jump (<asset_count>).png", 10)
        self.attack_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Attack (<asset_count>).png", 10)
        self.dying_textures = load_textures(
            f"{KNIGHT_IMAGES_DIR}/Dead (<asset_count>).png", 10)

        # Adding all the different textures to self.textures
        self.textures.extend(self.idle_textures)
        self.textures.extend(self.walking_textures)
        self.textures.extend(self.running_textures)
        self.textures.extend(self.jumping_textures)
        self.textures.extend(self.attack_textures)
        self.textures.extend(self.dying_textures)
```

Since the textures were lists of lists/nested lists, I thought of using the `extend()` method instead of `append()` in case the SpriteList had any trouble parsing nested lists. But even after doing so, I gained no improvement sadly. The game was just like before and again it looked like it was loading the actual textures in real-time. Further help is deeply requested and appreciated. Thanks a lot.

**Comment by arafat-ar13** [comment]
Even after tweaking my code a lot, I am unable to gain any performance. Can you please help me by pointing out why is my code running so slow although I have followed the exactly code pattern that is available from the official website?

**Comment by pvcraven** [comment]
Sorry, I've been super-busy.

Please update to the new 2.4.2 version of Arcade. Then pass all possible textures to SpriteList.preload_textures:

https://arcade.academy/arcade.html#arcade.SpriteList.preload_textures

See if that helps.

**Comment by arafat-ar13** [comment]
Thanks!! Just as you said, I updated to the latest version and then passed the entire `self.textures` to the `preload_textures` method in my game's setup method and then I run my game and the game was running every so smoothly!! It's just amazing. There is absolutely no lag present and I am just really happy for this. Thank you so much for this update and for working so hard on this library. I will try my best to make this a fairly decent game if my skills allow. Thanks, and have a very nice day Sir!
