### ISSUE TITLE
Add method to Sprite that will update its size based on scale and current texture

### ISSUE THREAD

**Issue by markjoshua12** [pythonarcade/arcade#760]
### Actual behavior:
When changing the `texture` variable of `Sprite`, the new texture is drawn with the dimension of the last texture used.

### Steps to reproduce/example code:
Here's the code to reproduce it:
https://pastebin.com/02BPLsnn

**Comment by pvcraven** [comment]
This is by design. Flipping the texture of a sprite does not change the sprite size. Dimensions for a sprite are managed by the sprite, not by the texture.

This needs to be clearly documented, but I currently don't feel that flipping the texture should also resize the sprite.

**Comment by einarf** [comment]
I think this makes sense, but maybe there could be a method in the sprite updating this? It's not somethng you'd want in all cases.

**Comment by markjoshua12** [comment]
Indeed, flipping shouldn't change the size of the sprite.
Changing the `texture` variable though does not use the new texture's dimensions when rendering.

I tested the example code in an earlier version (2.3.15) and it does render the texture correctly. Will update on which version the earliest this bug shows.

Update: The earliest version this shows is on arcade 2.4a7. 

I see the reason now why its like this (#684), so a method in the sprite for updating this would suffice.
