### ISSUE TITLE
Clarify some assumptions in the pyinstaller tutorial

### ISSUE THREAD

**Issue by SirGnip** [pythonarcade/arcade#766]
### What documentation needs to change? 

The pyinstaller tutorial initial "quickstart" could be more explicit. 
https://arcade.academy/tutorials/bundling_with_pyinstaller/index.html

### What is wrong with it? How can it be improved?

This tutorial makes some assumptions about the Python environment that is being used. I'll get a PR up shortly.

**Comment by pvcraven** [comment]
Docs at this point should already be up.
