### ISSUE TITLE
No way to draw sprite lists with alternative blending modes.

### ISSUE THREAD

**Issue by 64-bit** [pythonarcade/arcade#769]
## Enhancement request:
Add support for selecting a blending mode when drawing sprite lists. Currently calling SpriteList.draw will set a default alpha-blending mode and override any changes you have made to the OpenGL blend state.

### What should be added/changed?
I am proposing that a optional varible is added to SpriteList.draw(), named 'blend_function' that the user can use to specify a custom blending mode. If not specified the original behaviour should remain. This may not be the appropiate way to solve this problem and I am open to suggestions. I will create a pull request with my proposed change.

### What would it help with?
Drawing sprites with, for example, a additive blending mode for effects or emissive layers.

**Comment by 64-bit** [comment]
Pull request here: #770

**Comment by einarf** [comment]
Merged.
