### ISSUE TITLE
Loading TMX layer fails if a tile object has a multiline property

### ISSUE THREAD

**Issue by vdmkenny** [pythonarcade/arcade#778]
## Bug Report

I created an object layer in a TMX map, with objects that have custom properties.
When one of these properties is multiline (has \n), I experience a crash. 
Changing it to a single line property works.

### Expected behavior:

I expect the layer loading to be able to return a property that is a string with newlines.

### Stack trace:
```
  File "/home/vdmkenny/adimian/RDgame/maps.py", line 20, in __init__
    tmx_map = arcade.tilemap.read_tmx(full_map_name)
  File "/home/vdmkenny/.local/lib/python3.8/site-packages/arcade/tilemap.py", line 58, in read_tmx
    tile_map = pytiled_parser.parse_tile_map(tmx_file)
  File "/home/vdmkenny/.local/lib/python3.8/site-packages/pytiled_parser/xml_parser.py", line 891, in parse_tile_map
    layers = _get_layers(map_element)
  File "/home/vdmkenny/.local/lib/python3.8/site-packages/pytiled_parser/xml_parser.py", line 428, in _get_layers
    layers.append(layer_parser(element))
  File "/home/vdmkenny/.local/lib/python3.8/site-packages/pytiled_parser/xml_parser.py", line 352, in _parse_object_layer
    tiled_objects = _parse_tiled_objects(element.findall("./object"))
  File "/home/vdmkenny/.local/lib/python3.8/site-packages/pytiled_parser/xml_parser.py", line 320, in _parse_tiled_objects
    tiled_object.properties = _parse_properties_element(properties_element)
  File "/home/vdmkenny/.local/lib/python3.8/site-packages/pytiled_parser/xml_parser.py", line 686, in _parse_properties_element
    value = property_element.attrib["value"]
KeyError: 'value'
```

**Comment by Cleptomania** [comment]
I looked into the error and it seems the type of your property is a boolean. The boolean type wouldn't support anything other than True or False. 

You should check and verify the type of your property within the Tiled map is a string, if that's not the problem then we can check into trying to reproduce it, but if there is an actual bug it's probably with https://github.com/Beefy-Swain/pytiled_parser which is what Arcade uses to load TMX maps. The current version of that is no longer supported and we're working on implementing a complete re-write but it's not done yet.

**Comment by vdmkenny** [comment]
I can confirm, it's definitely a string. Changing the same string property from `test` to `test\ntest` reproduces this for me.

**Comment by Cleptomania** [comment]
That’s interesting it does appear that for some reason the /n is making it attempt to load it as a Boolean type and then error out because of an unexpected value.

My initial thinking is this is a deeper issue with how the XML parsing is done and wouldn’t be a quick fix.

I am completely re-writing the Tiled implementation as the current stuff is a mess and not easy to maintain. I’m starting that work in November with the plan to have an initial release candidate by the start of December.

**Comment by einarf** [comment]
Can this be closed?

**Comment by Cleptomania** [comment]
Yeah the new version of pytiled-parser fixes this.
