### ISSUE TITLE
import arcade GLU library not found

### ISSUE THREAD

**Issue by pashby** [pythonarcade/arcade#787]
Don't know whether this is a bug but I cannot import the Arcade library without getting the 

error import arcade GLU library not found

I have tried many times to install Arcade but nothing works.

I'm using Python3.8 and the Pycharm IDE.
 
Peter

**Comment by einarf** [comment]
What platform? What is your exact steps installing? What is the entire stack trace/error?

**Comment by einarf** [comment]
Closing this because of no response. Be free to re-open if you have more input.
