### ISSUE TITLE
Left shift key and right shift key emit the same key code (65505)

### ISSUE THREAD

**Issue by nejinx** [pythonarcade/arcade#789]
## Bug Report
The right shift key emits the same key code as left shift key running on Windows 10.

### Actual behavior:
The right shift key emits key code 65505.

### Expected behavior:
The right shift key when pressed should emit key code 65506.

### Steps to reproduce/example code:

```
import arcade

class ShiftGame(arcade.Window):
    def __init__(self, width, height, title):
        super().__init__(width, height, title)

    def on_key_press(self, key, modifiers):
        print(key, modifiers)

    def on_key_release(self, key, modifiers):
        print(key, modifiers)

def main():
    ShiftGame(640, 480, "Testing Shift Key")
    arcade.run()

if __name__ == '__main__':
    main()
```

I have submitted the issue on Pyglet (https://github.com/pyglet/pyglet/issues/320) as suggested.

**Comment by nejinx** [comment]
Looks to possibly be a 'TODO' in Pyglet:

https://github.com/pyglet/pyglet/blob/v1.5.11/pyglet/window/win32/__init__.py

line 776
```
        elif symbol == key.LSHIFT:
            pass  # TODO: some magic with getstate to find out if it's the
            # right or left shift key.

```

I'm unfamiliar with Pyglet but could possibly be the cause...

**Comment by einarf** [comment]
Yes. This is definitely an issue that should go in the pyglet project. Maybe create an issue there (https://github.com/pyglet/pyglet) and link to this one in case there are changes we need here as well after a fix.

**Comment by nejinx** [comment]
I have submitted the issue to Pyglet and provded a link in the original issue comment.

**Comment by nejinx** [comment]
Looks like they have a pending fix for this, just tested the commit by caffeinepills at https://github.com/pyglet/pyglet/issues/320#issuecomment-742604331 and it works.

**Comment by pvcraven** [comment]
Closing this, as it it more of a pyglet thing.

**Comment by benmoran56** [comment]
Covered in the latest pyglet release.
