### ISSUE TITLE
transform mouse event location to be in window viewport coordinates, for fixing mouse events breaking when getting the game to scale along with the window

### ISSUE THREAD

**Issue by LiorAvrahami** [pythonarcade/arcade#791]
not sure if bug or enhancement request.

## Enhancement request:
transform mouse event location to be in window viewport coordinates, for fixing mouse events breaking when getting the game to scale along with the window

### What should be added/changed?
the location of mouse events is currently in window coordinates. which is usually the same as the window viewport coordinates. I am suggesting that when these are different, the window viewport coordinates be used. this should be implemented by a simple scaling and translation transformation on the mouse coordinates.

### What would it help with?
as shown in the example named "Full Screen Example" (link below), getting the game to scale along with the window is implemented via setting window.set_viewport( 0, SomeConstentWidth, 0, SomeConstentHeight). this method works well! the only problem I could find with it is that the mouse click events' locations are in window coordinates and not in window viewport coordinates, which breaks custom made buttons and any arcade.gui.UIClickable.
link to "Full Screen Example": [https://arcade.academy/examples/full_screen_example.html](https://arcade.academy/examples/full_screen_example.html)

**Comment by LiorAvrahami** [comment]
made a pr for this #792

**Comment by einarf** [comment]
We're also worked on a camera : https://github.com/pythonarcade/arcade/blob/development/arcade/experimental/camera.py
