### ISSUE TITLE
GUI managers are not view specific

### ISSUE THREAD

**Issue by LiorAvrahami** [pythonarcade/arcade#793]
it seems to me there's no way to make different GUI configurations for different views, because every UIManager is window specific and not view specific. when changing Views, al the UIElements remain unchanged

**Comment by eruvanos** [comment]
Hi,

the following View will setup the ui_manager on show and unregister all global registered callbacks when hidden.

```
class MyView(View):
    def __init__(self, window=None):
        super().__init__(window=window)
        self.ui_manager = UILayoutManager(window=window, attach_callbacks=False)

    def on_show_view(self):
        self.ui_manager.register_handlers()
        
    def on_hide_view(self):
        self.ui_manager.unregister_handlers()
```

Would this work for you?
