### ISSUE TITLE
AStarBarrierList: 'NoneType' object has no attribute 'grid_size'

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#797]
Sometimes getting `'NoneType' object has no attribute 'grid_size'` error on this piece of code:
```
arcade.astar_calculate_path(start_point=self.position,
                                          end_point=self.t.position,
                                          astar_barrier_list=self.barrier_list,
                                          diagonal_movement=False)
```

It is reproduced when I set `grid_size` value to 100 here:
```
arcade.AStarBarrierList(moving_sprite=self,
                                   blocking_sprites=self.obstacle_sprites,
                                   grid_size=100,
                                   left=int(self.center_x-self.visibility_distance),
                                   right=int(self.center_x+self.visibility_distance),
                                   bottom=int(self.center_y-self.visibility_distance),
                                   top=int(self.center_y+self.visibility_distance))
```
It is not reproduced when `grid_size` is around 20.

**Comment by pvcraven** [comment]
Any chance of a full stack trace and/or minimal working example?

**Comment by alderven** [comment]
How to get full stack trace? I'm using:
```
        try:
             update()
        except Exception as e:
            print(e)
```
and it simply prints me `'NoneType' object has no attribute 'grid_size'`.
`traceback.print_exc()` produces same output.

**Comment by pvcraven** [comment]
Might try some of the options here. I can't do much without more info:

https://stackoverflow.com/questions/3702675/how-to-catch-and-print-the-full-exception-traceback-without-halting-exiting-the
