### ISSUE TITLE
can not load pymunkoptions module

### ISSUE THREAD

**Issue by dbach** [pythonarcade/arcade#799]
## Bug Report

The recently released pymunk package v6.0.0 no longer includes a pymunkoptions module, which is imported by arcade. 

### Actual behavior:

After 'import arcade', I get a ModuleLoadError for pymunkoptions caused by an import in drawing_support.py. 

### Expected behavior:

'import arcade' should run without errors. 

### Steps to reproduce/example code:

Install pymunk 6.0.0
Install arcade
Run 'import arcade' in a Python interpreter

**Comment by pvcraven** [comment]
Good grief, I need to pin every library version. Thanks for the report.

**Comment by Cleptomania** [comment]
Pymunk is pinned at ~=5.7 in the development branch currently. I don't think we've done a release since that was done though.

It was done with https://github.com/pythonarcade/arcade/pull/780

**Comment by viblo** [comment]
Sorry for the breakage! Seems like the timing of the release was a bit unfortunate given you already have a fix in development.
(I would not be surprised if there were other breakages as well related to the new version, so you probably want to do some proper testing once you decide to upgrade properly to Pymunk 6. Let me know if there is anything unclear or tricky with upgrading and Im happy to answer questions)

**Comment by pvcraven** [comment]
I'll call it fixed with 2.5 release pinning the version.
