### ISSUE TITLE
Remove old pages from documentation

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#803]
I've tried to run "GUI Button" example from here: https://arcade.academy/examples/gui_button.html

But it gives me error:

```
Traceback (most recent call last):
  File "C:/test/arc/gui_button.py", line 6, in <module>
    class PlayButton(TextButton):
NameError: name 'TextButton' is not defined
```

OS: Win 10 x64
Python: 3.7
Arcade: 2.4.3

**Comment by pvcraven** [comment]
Ah, that version is no longer supported.

I need to pull orphaned pages off the documentation so that doesn't pull up again.

**Comment by pvcraven** [comment]
Updated to delete old files.
