### ISSUE TITLE
Setter method for scroll_x in arcade.experimental.camera broken

### ISSUE THREAD

**Issue by mkirkines** [pythonarcade/arcade#809]
## Bug Report
The setter method for scroll_x (line147 )in https://github.com/pythonarcade/arcade/blob/development/arcade/experimental/camera.py is broken.

### Actual behavior:
Using the setter like this will do nothing (no scrolling of screen in horizontal direction), as it changes the wrong variable.

### Expected behavior:
The screen scrolls in horizontal direction, when using the scroll_x setter method.

### Steps to reproduce/example code:
Just look in the repository, it' obvious.

### What should be added/changed?

change line 147 from:
        self._scroll = value
to:
        self._scroll_x = value

**Comment by einarf** [comment]
Thanks! We only use the `scroll` property in examples. Fixed in a1ab9657d4aa984c6b6a0bb01117295c44f6f958

**Comment by einarf** [comment]
Fix already released
