### ISSUE TITLE
Feature request (docs): add sphinx-copybutton

### ISSUE THREAD

**Issue by MrGallo** [pythonarcade/arcade#811]
In the docs it might be useful to use [sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/) to add a quick copy icon to the example code blocks. It would make it slightly easier to copy lengthy code.

**Install**
```sh
pip install sphinx-copybutton
```

In sphinx `conf.py` file:

```python
extensions = [
    ...
    'sphinx_copybutton'
    ...
]
```

**Comment by pvcraven** [comment]
It is part of Arcade docs. Don't know why it stopped working. I updated the versions and pushed out, once the cloud syncs it should be visible.

**Comment by pvcraven** [comment]
Thanks for reporting.
