### ISSUE TITLE
I found collision bug in Tutorial Code 

### ISSUE THREAD

**Issue by mh1633** [pythonarcade/arcade#817]
## Bug Report

I just try to learn arcade module.

this bug occurs when i run code in Simple Platformer turorial step 8-'Use a Map Editor'

i never changed original code, just I runed

and Same bugs occurs In step 9 tutorial

When a character jump and collidies diagonally against a platformers

what is the problems?

I checked Physics.engine Class and others Class in library but i can't found what is the problems....

I recoreded a bug clip and attached. please refer to it  

English is not my first language, so I'm a little lacking. Please understand.

https://user-images.githubusercontent.com/77893313/106390915-19429800-642e-11eb-9c5a-22cf0c6fb55f.mp4

**Comment by pvcraven** [comment]
Any way you can check and post the version of Arcade you are running?

**Comment by mh1633** [comment]
yeah.
I setup arcade 2.5.3 ver.
and im using python 3.8.6 in visual studio code

**Comment by mh1633** [comment]
now i try to find error point.
i found some conditions for this situation was occured 
please. you need to check "physics_engines.py ->  def _move_sprite and line 158"
In code, To escape 'while' , an 'len(collision_check) is must be != 0 
but it keeps 0.
so infinity roop problem is occured 

anyway the couse I found may be wrong.. but i'm still trying a lot of check :)

**Comment by mh1633** [comment]
I add "exit_loop = True" in "physics_engines.py -> def _move_sprite, line 184 ~ 185
Doing it, infinite loop is not occured

**Comment by einarf** [comment]
This fix is already in 2.5.4. Closing. Thanks for the PR!
