### ISSUE TITLE
Add center_window parameter to arcade.Window()

### ISSUE THREAD

**Issue by matteoprat** [pythonarcade/arcade#829]
## Enhancement request:
It would be nice if you could add to the arcade.Window constructor the center_window parameter as a boolean.

### What should be added/changed?
Just add the argument to __init__() and check if it is true, then call the arcade.Window.center_window() method already existing.

### What would it help with?
It make sense to have the option during the initialization. The fact that is currently not available as argument makes people (including myself) unaware of the existance of center_window() method.

### What documentation needs to change? 
In the code example either add the argument to the class or show that center_window() is an available method

### Where is it located?
In every example the window is created, and it is never centered

### What is wrong with it? How can it be improved?
Add a line, or a comment, that show the presence of the center_window() method.

**Comment by einarf** [comment]
This might be more a docs/tutorial issue? I's not really sustainable to add special cases like this in the window constructor imho. Maybe some quick window guide can help and/or have a `window.center()` method?

**Comment by Cleptomania** [comment]
Released with 2.6.0
