### ISSUE TITLE
Arcade for OpenGL 2

### ISSUE THREAD

**Issue by Midhil457** [pythonarcade/arcade#831]
**Problem**
Hi, so I am trying to make a pixel editor and I was trying to use arcade, but the system I am using only supports up to OpenGL 2.1 or something. Is there a work around? As pyglet 1.5 still supports OpenGL 2, it should be possible, right? , as I won't be using all the dependencies and mostly be working with image manipulation and GUI. I might be wrong. 

I don't know if I should be posting here. I couldn't find any other place to do so. Sorry 

Thanks <3

**Comment by einarf** [comment]
Arcade is targeting pyglet 2.x being an OpenGL 3.3+ library. We have made our own opengl wrapper using OpenGL 3.3 (4.1if avaialble) so making arcade to work with 2.1 will be very difficult at this point. We even keep using more advaced OpenGL features over time. Next minor release we're probably switching to pyglet 2.x and are slowly trying to use more of the pyglet 2.0 features so both projects can benefit from improvements.

If you are aiming for OpenGL 2.1 I would suggest just using pyglet 1.5.x. It's a great library.
