### ISSUE TITLE
Animated GIF image loading

### ISSUE THREAD

**Issue by CyberHawk09** [pythonarcade/arcade#834]

**Comment by pvcraven** [comment]
Not yet. Currently listed as one of the desired enhancements:

https://arcade.academy/enhancement_list.html#sprites

It is certainly do-able, and I don't think would be that hard to program.

**Comment by einarf** [comment]
The question is what this function should return. An array of textures?

**Comment by pushfoo** [comment]
Would it work if `arcade.load_textures` made the `image_location_list` argument optional when the source file passed is a gif?

**Comment by einarf** [comment]
Here's a snippet of my loader dumping frames into a vertical strip (texture array), Should be easy enough to tweak. We also have to remember that gifs also come as single images, but I think that already works with `load_texture()`?
```py
# If the image is animated (like a gif anim) we convert it into a vertical strip
if hasattr(self.image, "is_animated") and self.image.is_animated:
    self.layers = self.image.n_frames
    anim = Image.new(
        self.image.palette.mode,
        (self.image.width, self.image.height * self.image.n_frames),
    )
    anim.putalpha(0)

    for frame_number in range(self.image.n_frames):
        self.image.seek(frame_number)
        frame = self._palette_to_raw(self.image, mode="RGBA")
        anim.paste(frame, (0, frame_number * self.image.height))

    self.image = anim
```

This can also potentially work with other animated formats.

**Comment by einarf** [comment]
We do actually have this now.
