### ISSUE TITLE
all pymunk examples error

### ISSUE THREAD

**Issue by lavirlifiliol** [pythonarcade/arcade#835]
### Actual behavior:
```sh
PS C:\Users\user\dt> pip show arcade
Name: arcade
Version: 2.5.5
Summary: Arcade Game Development Library
Home-page: https://arcade.academy
Author: Paul Vincent Craven
Author-email: paul.craven@simpson.edu
License: MIT
Location: c:\users\user\appdata\local\pypoetry\cache\virtualenvs\dt-_p0vacts-py3.9\lib\site-packages
Requires: pymunk, pillow, pytiled-parser, numpy, shapely, pyglet, pyyaml
Required-by: aaaaaaaa
PS C:\Users\user\dt> pip show pymunk
Name: pymunk
Version: 6.0.0
Summary: Pymunk is a easy-to-use pythonic 2d physics library
Home-page: http://www.pymunk.org
Author: Victor Blomqvist
Author-email: vb@viblo.se
License: MIT License
Location: c:\users\user\appdata\local\pypoetry\cache\virtualenvs\dt-_p0vacts-py3.9\lib\site-packages
Requires: cffi
Required-by: arcade
PS C:\Users\user\dt> pip -V
pip 21.0.1 from C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\dt-_p0VaCts-py3.9\lib\site-packages\pip (python 3.9)
PS C:\Users\user\dt> python -V
Python 3.9.0
PS C:\Users\user\dt> python -m arcade.examples.pymunk_box_stacks
Aborting due to Chipmunk error: The shape's body must be added to the space before the shape.
        Failed condition: shape->body->space == space
        Source:Chipmunk2D\src\cpSpace.c:423
```
### Expected behavior:
the example will run
### Steps to reproduce/example code:
Create a new python environment with arcade 2.5.5. Poetry is not related to this, it can be replicated with raw pip as well.

Did not test further minor patches. My guess would be that it is related to pymunk 6.

**Comment by einarf** [comment]
Is this a pymunk 6.x vs 5.x thing?

**Comment by lavirlifiliol** [comment]
That seems to be the case. Upon further testing, manually installing pymunk==5.7.0 fixes the error and the example runs normally. The pip operation runs with a warning about arcade demanding pymunk 6.

This workaround isn't ideal however, since it makes it impossible to use poetry or pipenv which require that dependencies are upheld.

**Comment by einarf** [comment]
So that probably means 2.5.5 is broken because the dependency was bumped?

**Comment by lavirlifiliol** [comment]
Yes

**Comment by einarf** [comment]
@pvcraven PyWeek has started and this will probably cause problems for a lot of people.

**Comment by einarf** [comment]
2.5.6 released so I guess this can be closed?

**Comment by lavirlifiliol** [comment]
Yes, updating to 2.5.6 fixes the examples
