### ISSUE TITLE
Framebuffer.clear() and scissor box

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#836]
When we set the viewport we also set a scissor box to the same values. This means any `clear()` will only affect what is inside the scissor box. This creates issues when the viewport / scissor box changes. Old content in the new borders are not cleared.

This is especially an issue when using `Camera2D`.

**Comment by einarf** [comment]
Here we see lingering pixels in the upper left and right corner after resize due to scissor box preventing the entire framebuffer to clear after resize.
![unknown](https://user-images.githubusercontent.com/5418180/113003647-37e5b680-9173-11eb-8558-7dbabdd3028c.png)

A fallback is to reset the viewport and clear the screen, then apply camera.

```py
arcade.set_viewport(0, self.width, 0, self.height)
self.clear() # or arcade.start_render()
camera.use()
```

**Comment by einarf** [comment]
The reason for the scissor box is simply that we don't want the game's background color to be part of the borders. It solves several problems but introduce this issue.

**Possible solutuion**: Check if the scissor box covers the entires screen in `Framebuffer.clear()`. If this is not the case we can do a two-stage clear. First clear the entire screen, then clear apply the original viewport and clear using the window's background color. We can also decide to only do a one-stage clear if the background color is black.


I am not sure how this will apply to framebuffers that are not the default framebuffer. We might want both to work the exact same way to make offscreen rendering simpler?

**Comment by pvcraven** [comment]
What is the status of this?

**Comment by einarf** [comment]
You can now specify the exact viewport to clear.

```py
# Clear only lower left 100 x 100 pixels
self.window.clear(viewport=(0, 0, 100, 100))
# This is the same as..
self.ctx.fbo.clear(viewport=(0, 0, 100, 100)
```

We're just exposing more of the lower level api in the higher level functions.

**Comment by einarf** [comment]
2.6.10 released
