### ISSUE TITLE
Compatibility with python 3.6

### ISSUE THREAD

**Issue by thomai-d** [pythonarcade/arcade#840]
The latest arcade (2.5.6) is no longer compatible to python 3.6 [1] as it requires numpy 1.20.1, which dropped support for python 3.6 [2].

[1] https://arcade.academy/installation.html
[2] https://github.com/numpy/numpy/releases/tag/v1.20.0

**Comment by pvcraven** [comment]
Thanks for the report.

**Comment by einarf** [comment]
Is it possible to add two numpy dependencies with different python version constraints in the requirements?

**Comment by Cleptomania** [comment]
Yeah I can put a commit in for it today. We already do a conditional dependency for installing data classes if the Python version is 3.6.

@einarf Do you know what version of Numpy would be needed for 3.6?

**Comment by einarf** [comment]
It seems you need `numpy==1.19.5 `. 1.20.x removed py3.6
