### ISSUE TITLE
The arcade repo on github no longer shows "user by" data

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#855]
We no longer see any "used by" data in the github repository. This is such a useful feature we should probably look into how it can be restored.

This was probably introduced in 780

**Comment by Cleptomania** [comment]
Well the Pipfile fix didn't work. Going to probably move dependencies back into `setup.py` from `setup.cfg`.

**Comment by Cleptomania** [comment]
Resolved by moving dependencies back to `setup.py`.
