### ISSUE TITLE
Error in "background-music" example: "TypeError: get_stream_position() takes 1 positional argument but 2 were given"

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#856]
Getting error: `TypeError: get_stream_position() takes 1 positional argument but 2 were given`

when running [background-music](https://arcade.academy/examples/background_music.html#background-music) example.

**Comment by einarf** [comment]
What arcade version?
What platform/os and can you share the entire stack trace?

**Comment by alderven** [comment]
Not worked on Arcade 4.3. Upgrading to the latest Arcade package is helped.
