### ISSUE TITLE
Remove numpy as a dependency

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#860]
We actually no longer need numpy in arcade. It was previously used in `SpriteList`, but we changed to `array.array`. We should possibly make numpy into a dev requirement since some tests do use it.

Numpy is currently used for:
* Projection matrix. We can instead use pyglet's `Mat4` class.
* A couple of places in `buffered_draw_commands`. We can replace that with `struct` or `array.array`

**Comment by einarf** [comment]
Numpy was removed as a dependency in `texture-atlas`  branch.

**Comment by Cleptomania** [comment]
Released with 2.6.0
