### ISSUE TITLE
Arcade and vsync

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#866]
### Current Situation

Currently we have the following platform based checks during window creation

https://github.com/pythonarcade/arcade/blob/07b02bfb6ad4920c7df6d7f8b95d4283d760ecb4/arcade/application.py#L107-L112

This was due to users on linux and macOS experiencing framerate caps at 30 fps either due driver limitations or heat throttling.
From Catalina (macOS) some drivers started throttling framerates to 30 possibly due to heat and power usage.

Since we are already creating the window with vsync disabled we can remove these platform specific checks entirely:

https://github.com/pythonarcade/arcade/blob/07b02bfb6ad4920c7df6d7f8b95d4283d760ecb4/arcade/application.py#L93-L94

### Arcade 2.6

* Remove the platform specific checks since vsync is always disabled by default. If vsync is forced-enabled on driver level we can't really do anything about that.
* Make a section about how to make games with vsync enabled in docs. This implies that `delta_time` is actively used when moving sprites and objects.

Most of our current examples assumes `on_update` is called 60 times a second troughly because they don't take `delta_time` into consideration. Disabling vsync gives `on_update` a few more milliseconds slack to do work. This is a good default for beginners.

An optional solution is to make vsync adaptive, but this requires a bit more research. It involves constantly measuring how long `on_draw` + `on_update` takes in total. if we drop below some threshold we disable vsync. This is a much more complicated and risky move. Simply documenting how arcade works well with vsync is probably more sustainable.

**Comment by einarf** [comment]
Fixed in 6d8616c8d642216ef47b1483f6db6c7272b5b2fc

**Comment by Cleptomania** [comment]
Released with 2.6.0
