### ISSUE TITLE
pipenv : selecting branch to install and check

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#871]
hello, i use **pipenv install arcade** command.
how can i select master or development branch ?
how can i check which environment is present just after pipenv shell command ?

**Comment by einarf** [comment]
I think `pipenv install https://github.com/pythonarcade/arcade/archive/refs/heads/development.zip` should work? Optionally you can just clone the arcade git repositor and `pip install -e` that into your virtualenv.

We also have a discord server that might be simpler to use for questions like this: https://discord.gg/ZjGDqMp

**Comment by pyweeker** [comment]
thank you einarf
