### ISSUE TITLE
Window size testing in Tiling Window Managers on Linux

### ISSUE THREAD

**Issue by Cleptomania** [pythonarcade/arcade#872]
Currently the tests get inaccurate results when trying to check the size of a window when running tests on a tiling window manager. It doesn't seem like this inaccurate size reporting breaks anything else, but it would be nice for this to not be an issue.

Specifically this has been found to be an issue with the i3 window manager, but I would imagine it is an issue with most any tiling window manager. 

Currently we have a `--twm` option when running pytest which will cause the failing checks to be ignored, but we should constrain all window sizing checks to it's own test.

Would be nice to figure out why this doesn't work in the first place, but as a worst case scenario if we can constrain the size checking to one test, then it can easily be ignored for tiling window managers.

**Comment by einarf** [comment]
I'm currently in the process of rewriting most of the tests. We're now just using the default window size and no longer rely on a hardcoded value. I think that will help a lot.

I don't think it will hard to make this work with wiling window manager. We just need to accept that we don't always control the actual window size.

**Comment by Cleptomania** [comment]
I've tested using i3 on Linux and it seems like this is resolved everywhere, anything else might be small amounts of cleanup here and there that I'll fix as I come across it.
