### ISSUE TITLE
GL_GEOMETRY_* enums not supported by older GPUs

### ISSUE THREAD

**Issue by invalidenumerant** [pythonarcade/arcade#874]
### Steps to reproduce/example code: Consistent. happy_face.py produces the same error.

C:\Users\User\Documents>python mousecoin.py
Traceback (most recent call last):
  File "C:\Users\User\Documents\mousecoin.py", line 121, in <module>
    main()
  File "C:\Users\User\Documents\mousecoin.py", line 115, in main
    window = MyGame()
  File "C:\Users\User\Documents\mousecoin.py", line 31, in __init__
    super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\arcade\application.py", line 127, in __init__
    self._ctx: ArcadeContext = ArcadeContext(self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\arcade\context.py", line 64, in __init__
    self.sprite_list_program_no_cull = self.load_program(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\arcade\context.py", line 229, in load_program
    return self.program(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\arcade\gl\context.py", line 548, in program
    return Program(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\arcade\gl\program.py", line 107, in __init__
    gl.glGetProgramiv(self._glo, gl.GL_GEOMETRY_INPUT_TYPE, geometry_in)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\gl\lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid enumerant'

C:\Users\User\Documents>pip3 list
Package        Version
-------------- -------
arcade         2.5.6
attrs          21.2.0
cffi           1.14.5
chess          1.5.0
gl             0.2.36
numpy          1.20.1
Pillow         8.2.0
pip            21.1.1
pycparser      2.20
pyglet         1.5.16
pymunk         6.0.0
PyOpenGL       3.1.5
python-chess   1.999
pytiled-parser 0.9.4a3
PyYAML         5.4.1
setuptools     49.2.1
Shapely        1.7.1
windows-curses 2.2.0

**Comment by einarf** [comment]
> GL_GEOMETRY_INPUT_TYPE
> params returns a symbolic constant indicating the primitive type accepted as input to the geometry shader contained in program.

This is an OpenGL 3.3 constant. I think this is a driver issue. I don't see any win 10 drivers listed for this card.

**Comment by Cleptomania** [comment]
> This is an OpenGL 3.3 constant. I think this is a driver issue. I don't see any win 10 drivers listed for this card.

To add some more explanation to this, Windows provides an OpenGL 1.1 interface(which is actually a Direct3D wrapper) by default if you do not have a driver installed for your GPU.

Since Arcade requires OpenGL 3.3+ you’ll get these API call errors as we try to use functions which don’t exist in OpenGL 1.1. 

According to AMD’s product page Windows 8 was the last version to receive support for this card, and there are no drivers for newer versions of Windows than that, so the only possible way to use Arcade with this card would be to downgrade Windows(which I don’t recommend) or on Linux AMD drivers might solve it, but I can’t find a definitive answer on that.

**Comment by einarf** [comment]
Thanks for the clarification, @Cleptomania 

Your card will probably work on Linux, but not on windows due to lack of driver support.

Basically any GPU older that 8-10 years (since originally manufactured) or any GPU not supporting at least DX11 / GL4.1 are no logger supported on Win 10 and often not even on Win 8. (Radeon HD 4200 was released in 2009)

There used to be unofficial drivers, but these only implemented OpenGL 3.0 completely missing geometry shader support and other key features we use in arcade to get the performance we have today.

**Comment by invalidenumerant** [comment]
Thank you very much for your assistance @einarf and @Cleptomania . Are you sure this is the issue? GPU Caps Viewer reports that I am running OpenGL 3.3
![Capture](https://user-images.githubusercontent.com/84165929/118287214-140ed380-b488-11eb-846d-65a701e232d6.PNG)

**Comment by einarf** [comment]
Looking at the enums in the OpenGL registry (https://raw.githubusercontent.com/moderngl/opengl-registry/master/gl.xml) it could be that your drivers don't support the standard enum for some reason.
```
<enum value="0x8917" name="GL_GEOMETRY_INPUT_TYPE"/>
<enum value="0x8DDB" name="GL_GEOMETRY_INPUT_TYPE_ARB"/>
<enum value="0x8DDB" name="GL_GEOMETRY_INPUT_TYPE_EXT"/>
```

It may be that it only supports the `ARB` or `EXT` values (they are the same).  You could try to modify the source:

```
gl.glGetProgramiv(self._glo, 0x8DDB, geometry_in)
```

If you bump into other enums raising the same error you can look up alternative values in the linked xml file. It's a shot in the dark, but might be works exploring.

**IF** this works we could support this as an exception in the code base

**Comment by invalidenumerant** [comment]
I think that worked, because now it's telling me the error is on the next line, geometry_out. let me try a few more...

**Comment by invalidenumerant** [comment]
IT WORKED!  I changed all three of these:

            gl.glGetProgramiv(self._glo, 0x8DDB, geometry_in)
            gl.glGetProgramiv(self._glo, 0x8DDC, geometry_out)
            gl.glGetProgramiv(self._glo, 0x8DDA, geometry_vertices)
            self._geometry_info = (
                geometry_in.value,
                geometry_out.value,
                geometry_vertices.value,
            )

Thank you for your help! The mouse game and the happy face work now. I had another issue though. With my own program, I am trying to use my own event loop, because I already wrote the program with curses in mind. I'm ditching the curses interface for a graphical interface using arcade and I wanted to just drop in some drawing commands to the existing program. This actually seemed to be working in Linux, but on Windows the game window is freezing up if I try to drag it or if it loses focus. Is there a way to go around the arcade.run() loop or do I have to go through it?

**Comment by einarf** [comment]
Great! I'll re-open this to explore if there is anything we can do in arcade to support old enums. If it's a relatively low effort thing we can add a fallback.

**Comment by einarf** [comment]
Looking closer at this: The `ARB` and `EXT` versions are the OpenGL 2 versions of the enums. 3.3 drivers **should** support it the standard ones (`GL_GEOMETRY_INPUT_TYPE` etc..). The drivers are not really "true" 3.3, but it supports most 3.3 features through extentions.

I think the best solution at the moment is to simply overwrite the enums in pyglet at runtime.

```
pyglet.gl.GL_GEOMETRY_INPUT_TYPE = 0x8DDB
pyglet.gl.GL_GEOMETRY_OUTPUT_TYPE = 0x8DDC
pyglet.gl.GL_GEOMETRY_VERTICES_OUT = 0x8DDA
```

This is more practical than modifying the source itself.

Closing this again for now. Might revisit this in the future if more people experience this issue. Feel free to add more information to this issue.

**Comment by invalidenumerant** [comment]
Thanks for your assistance! Still working fine. let me know if you need any more information.
