### ISSUE TITLE
Open multiple windows at the same time or restart game in new window

### ISSUE THREAD

**Issue by Janek9527** [pythonarcade/arcade#875]
## Bug Report
Hello i am trying to use pythonarcade as a machine learning environment.
Therefore i'm trying to close the game / window and reopen it afterwards.
Or what would be even better open multiple windows / instances of the game at the same time.

### Actual behavior:
I have a class
`class GameWindow(arcade.Window):`

and the following function in the same file:
```
def run():
    window = GameWindow(SCREEN_WIDTH, SCREEN_HEIGHT)
    arcade.set_window(window)
    window.dispatch_events()
    arcade.run()
    return window.episode
```
The window is programmatically closed using `arcade.close_window()`
In another file i run the following code
```
    print(run())
    time.sleep(3)
    print(run())
```
The first run works great, closes the window and returns the expected result.

For the second run im getting this error:

 File "... game_class.py", line 295, in run
    window = GameWindow(SCREEN_WIDTH, SCREEN_HEIGHT, screen_title)
  File "... game_class.py", line 67, in __init__
    super().__init__(width, height, screen_title)
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\arcade\application.py", line 93, in __init__
    super().__init__(width=width, height=height, caption=title,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\window\win32\__init__.py", line 134, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\window\__init__.py", line 648, in __init__
    self._create()
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\arcade\application.py", line 505, in _create
    super()._create()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\window\win32\__init__.py", line 280, in _create
    self.context.attach(self.canvas)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\gl\win32.py", line 291, in attach
    super(Win32ARBContext, self).attach(canvas)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\gl\win32.py", line 238, in attach
    raise gl.ContextException('Unable to share contexts.')
pyglet.gl.ContextException: Unable to share contexts.

### Expected behavior:
I can launch multiple windows / game instances at the same time or after each other.

I hope someone can show me a brief example on how to handle this problem.

Kind regards,
Janek

**Comment by einarf** [comment]
I think the simplest solution here is to make sure that you `close()` the window before opening a new one. Arcade is building on pyglet and it might be that your drivers don't support context sharing (or the context needs to be configured differently in pyglet). There are some changes coming for this in pyglet 2.0 (We're upgrading to that soon).

A faster option would be to just reuse the window and organize your game in a View or some custom object that is easy to create and dispose. The window could also be temporarily be hidden if needed.

A third option allowing multiple games to be displayed at the same time could be achieved by rendering multiple games in the same window. Simply maintain a list of active games and draw them in a loop modifying what section of the screen they should be rendered. I can provide an example for this if needed.

**Comment by ghost** [comment]
@Janek9527 einarf is right – that happens for everyone. It seems like your “dispatch_events” kind of replaces “setup” most arcade code is written in, so instead of calling run() the function twice, just try calling dispatch_events and see if that works. This will hopefully restart your program in the same window. And yes, like einarf said you should manually stop arcade if you want to open up a second window.
