### ISSUE TITLE
Threading problems / Segfaults in arcade/gl/buffer.py

### ISSUE THREAD

**Issue by thomai-d** [pythonarcade/arcade#876]
We are implementing a game on a Nvidia Jetson using a beamer and a camera (with motion detection) and no keyboard/mouse.
We added a small flask web-api in the python process from where we can start / stop the game (using "werkzeug" backend).

Very often, we get segmentation faults, especially when switching game-views. 

We checked that we do not call arcade functions from the webserver thread.
But it seems that some cleanup-functions for weak-refs are somehow called on the webserver thread, anyways, which leads to seg faults:

```
Fatal Python error: Segmentation fault

Current thread 0x0000007f7f7fe1f0 (most recent call first):
  File "/home/gesina/.local/lib/python3.7/site-packages/arcade/gl/buffer.py", line 102 in release
  File "/usr/lib/python3.7/weakref.py", line 572 in __call__
  File "/usr/lib/python3.7/email/feedparser.py", line 164 in __init__
  File "/usr/lib/python3.7/email/parser.py", line 49 in parse
  File "/usr/lib/python3.7/email/parser.py", line 67 in parsestr
  File "/usr/lib/python3.7/http/client.py", line 224 in parse_headers
  File "/usr/lib/python3.7/http/server.py", line 337 in parse_request
  File "/home/gesina/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 378 in handle_one_request
  File "/usr/lib/python3.7/http/server.py", line 426 in handle
  File "/home/gesina/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 345 in handle
  File "/usr/lib/python3.7/socketserver.py", line 720 in __init__
  File "/usr/lib/python3.7/socketserver.py", line 360 in finish_request
  File "/usr/lib/python3.7/socketserver.py", line 650 in process_request_thread
  File "/usr/lib/python3.7/threading.py", line 870 in run
  File "/usr/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 890 in _bootstrap
```

Is that a bug in the buffer.py implementation?
Is there anything I can do or is multithreading absolutely not supported?

I'm using arcade 2.5.6, python 3.7.5 on linux / aarch64.

**Comment by einarf** [comment]
We might neeed to provide a different gc mode for OpenGL objects for this to work smoothy. One that only garbage collect opengl objects when you call `Context.gc()`. I also know that explicitly invoking the gc in main thread can help.

You could try to monkeypatch `Buffer.release` into a lambda and see what happens.

I solved this in moderngl by doing something close to this:

* Expose a `Context.auto_gc` boolean
* Only if `True` we create a weakref to handle the cleanup
* If `False` we keep references to "dead" opengl objects in the context only releasing the underlying objects when `Context.gc()` is called.

It might actually be a very simple problem to fix.

**Comment by einarf** [comment]
I could possibly make a quick branch with this new gc feature if you are interested. It's a fairly trivial thing to add.

**Comment by thomai-d** [comment]
Thanks for your answer. Creating that branch would be very kind of you.

Is `arcade.Window.ctx` the context you're referring to?
> https://github.com/pythonarcade/arcade/blob/7dd168595420fcb01cd558d211960875246e8406/arcade/application.py#L142

Further, I guess calling the `context.gc()` after views are unloaded should be enough, right?

I'm asking since there's this special case where we display a debugging video stream, using sprite textures and PIL-images, but currently there's no leaking memory and no problems with segfaults on this screen.

**Comment by einarf** [comment]
> Further, I guess calling the `context.gc()` after views are unloaded should be enough, right?

That depends how you drawing code looks like to be honest. It might be allocating resources per frame or not. I don't really know. Calling `window.ctx.gc()` in the same thread the window/context was created every frame or periodically should at least be enough. It's not an expensive operations.

If this works we can make it part of arcade 2.6 and add a section about it in docs.

**Comment by einarf** [comment]
Created quick branch with experimental gc mode: https://github.com/pythonarcade/arcade/tree/2.5.x-context-gc

Can also be installed directly from github (or referenced in requirements): 
```
pip install -I https://github.com/pythonarcade/arcade/archive/refs/heads/2.5.x-context-gc.zip
```

The arcade window initializer now takes a `gc_mode` string parameter. This is `"auto"` by default. When setting this value to `"context_gc"` you will have to call `window.ctx.gc()` to garbage collect opengl objects. This should always be done from the same thread the window was created and can be called every frame (not expensive).

**Comment by thomai-d** [comment]
Good news is, that it looks like there are no segfaults anymore when using the "context_gc" mode.

Bad news are, that when calling `context.gc()`, there are other exceptions:

```
File "/home/gesina/augmentedfitnessgames/src/APE.AugmentedFitnessGames/views/startup_view.py", line 77, in on_draw
    arcade.draw_circle_outline(center_x, load_y, 40, arcade.color.JET, border_width=10)
  File "/home/gesina/.local/lib/python3.7/site-packages/arcade/draw_commands.py", line 244, in draw_circle_outline
    draw_ellipse_outline(center_x, center_y, radius * 2, radius * 2, color, border_width, num_segments)
  File "/home/gesina/.local/lib/python3.7/site-packages/arcade/draw_commands.py", line 351, in draw_ellipse_outline
    buffer.write(data=array.array('f', (center_x, center_y)))
  File "/home/gesina/.local/lib/python3.7/site-packages/arcade/gl/buffer.py", line 157, in write
    gl.glBindBuffer(gl.GL_ARRAY_BUFFER, self._glo)
  File "/home/gesina/.local/lib/python3.7/site-packages/pyglet/gl/lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
```

What I did in window was:
```
    arcade.schedule(self.gc, 1)

    def gc(self, *kwargs):
        print(f"GC {len(self.ctx.objects)} objects")
        self.ctx.gc()
```

The output was:
```
GC 0 objects
GC 14 objects
GC 42 objects
```

**Comment by einarf** [comment]
What is `startup_view.py` doing and what thread does it run in?
What happened with the old view? I'm not sure what a "view" is in this context.

An "invalid operation" probably means the opengl context cannot be accessed for some reason. Most likely because it's accessed from a different thread/process than the context was created.

**Comment by thomai-d** [comment]
`startup_view.py` is an `arcade.View` and just rendering a few things in the `on_draw` method:
- arcade.start_render()
- arcade.draw_text()
- arcade.draw_circle_outline()
- arcade.draw_arc_outline()

I think it's my turn now and try to extract a small repro project to further debug this issue ;)

**Comment by einarf** [comment]
That would be great. I suspect drawing is happening in the wrong thread. It needs to happen in the same thread the window/context was created.

**Comment by thomai-d** [comment]
The following non-threaded code will reproduce the exception:

```
import arcade
from arcade.color import WHITE


class StartupView(arcade.View):

    def __init__(self):
        super().__init__()
        self.player = arcade.Sprite()

    def on_draw(self):
        arcade.start_render()

        # Comment out this section, then it will not crash because no objects are GC'ed.
        # >>>>>
        self.player.set_hit_box([[100, 100], [200, 200], [100, 200]])
        self.player.draw_hit_box(WHITE, 3)
        # <<<<<

        arcade.draw_circle_outline(500, 500, 40, arcade.color.JET, border_width=10)


class Window(arcade.Window):

    current_view: arcade.View = None

    def __init__(self):
        super().__init__(800, 600, "Title", True, gc_mode='context_gc')
        arcade.schedule(self.gc, 1)

    def gc(self, *kwargs):
        print(f"GC {len(self.ctx.objects)} objects")

        # Comment out the gc() call and it will work, too
        self.ctx.gc()

    def show_default(self):
        startup_view = StartupView()
        self.show_view(startup_view)

    def on_key_press(self, symbol: int, modifiers: int):
        if symbol == arcade.key.ESCAPE:
            arcade.close_window()


window = Window()
window.show_default()
arcade.run()
```

After the first gc() call, the first `on_draw` fails:
```
File "test.py", line 47, in <module>
    arcade.run()
  File "/home/gesina/.local/lib/python3.7/site-packages/arcade/window_commands.py", line 240, in run
    pyglet.app.run()
  File "/home/gesina/.local/lib/python3.7/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/home/gesina/.local/lib/python3.7/site-packages/pyglet/app/base.py", line 167, in run
    timeout = self.idle()
  File "/home/gesina/.local/lib/python3.7/site-packages/pyglet/app/base.py", line 243, in idle
    window.dispatch_event('on_draw')
  File "/home/gesina/.local/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1333, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/home/gesina/.local/lib/python3.7/site-packages/pyglet/event.py", line 408, in dispatch_event
    if handler(*args):
  File "test.py", line 20, in on_draw
    arcade.draw_circle_outline(500, 500, 40, arcade.color.JET, border_width=10)
  File "/home/gesina/.local/lib/python3.7/site-packages/arcade/draw_commands.py", line 244, in draw_circle_outline
    draw_ellipse_outline(center_x, center_y, radius * 2, radius * 2, color, border_width, num_segments)
  File "/home/gesina/.local/lib/python3.7/site-packages/arcade/draw_commands.py", line 351, in draw_ellipse_outline
    buffer.write(data=array.array('f', (center_x, center_y)))
  File "/home/gesina/.local/lib/python3.7/site-packages/arcade/gl/buffer.py", line 152, in write
    gl.glBindBuffer(gl.GL_ARRAY_BUFFER, self._glo)
  File "/home/gesina/.local/lib/python3.7/site-packages/pyglet/gl/lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
```

**Comment by einarf** [comment]
Pushed some new changes. It was actually a really stupid mistake `VertexArray.delete` that was deleting buffers with the same ID 😄 (DERP!)

If this works I will cherrypick the commits into 2.6 / development OR we do a 2.5.7. Not sure yet.
In arcade 2.6 there will also be a lot less objects to gc since we reuse most resources.

**Comment by thomai-d** [comment]
Looks very good. No more issues in our game!

Thank you very much for your help and also the quick support for every issue I create here ;-)

I won't tell anybody, just squash the commits together :-D

**Comment by einarf** [comment]
> I won't tell anybody, just squash the commits together :-D

Deal 👍 

Keeping this issue open until the fix out.

**Comment by einarf** [comment]
This is now in maintenance branch and added to update notes for 2.5.7

**Comment by einarf** [comment]
2.5.7 is released

**Comment by einarf** [comment]
@thomai-d From 2.6.6 `context_gc` will be the default mode in arcade. Garbage collection will happen in `window.flip()` by default. 

Auto gc mode just cases too much problems because of the way python threads are working. (Objects being GCed in another thread randomly)
