### ISSUE TITLE
Explore the possibility for arcade to work on repl.it

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#878]
A quick check in repl.it : `glGetString(GL_VERSION)` returned `'3.1 Mesa 20.0.8'` so it's getting closer to support arcade.

It might be worth looking into if we can get it running in repl.it in the near future. That might be more on the pyglet side.

**Comment by einarf** [comment]
Currently there is a problem with poetry and arcade requirements. This is addressed in #877 

```
--> python3 -m poetry add arcade
Using version ^2.5.6 for arcade

Updating dependencies
Resolving dependencies...

[SolverProblemError]
The current project's Python requirement (^3.8) is not compatible with some of the required packages Python requirement:
  - arcade requires Python >=3.6,<3.10

Because no versions of arcade match >2.5.6,<3.0.0
 and arcade (2.5.6) requires Python >=3.6,<3.10, arcade is forbidden.
So, because arcade-test depends on arcade (^2.5.6), version solving failed.
exit status 1
```

**Comment by einarf** [comment]
Arcade seesm to work great on repl.it as long as you create the window with `antialiasing=False`

![unknown](https://user-images.githubusercontent.com/5418180/118891978-7b9da680-b900-11eb-82cc-73090036463a.png)

**Comment by einarf** [comment]
We can look at the following enviroment variables to determine if we are running in repl.it:

```
REPL_SLUG arcade-test
REPL_IMAGE gcr.io/marine-cycle-....
REPL_ID 8cf5fc86-12b4-4744-b492-c3086aa77451
REPL_OWNER EinarForselv
REPL_LANGUAGE python3
```

For example we can disable multisampling / antialiasing if repl.it is detected.

**Comment by Mr-Coxall** [comment]
> Arcade seesm to work great on repl.it as long as you create the window with `antialiasing=False`
> 
> ![unknown](https://user-images.githubusercontent.com/5418180/118891978-7b9da680-b900-11eb-82cc-73090036463a.png)

Can you share the Replit URL, where it was actually working, so I can try to reproduce this?

**Comment by einarf** [comment]
@Mr-Coxall https://replit.com/@EinarForselv/arcade-test#main.py

I simply downgraded to arcade 2.4.x to bypass the python requirements issue. I had to downgrade pymunk to 5.7.0 as well.

Notice that the window is created with `antialiasing=False`. We can make arcade detect repl.it enviroment to make that automatic.

**Comment by Mr-Coxall** [comment]
Thanks so much.

**Comment by einarf** [comment]
@Mr-Coxall The maintenance branch should now support replit (possible version 2.5.7). You can reference `https://github.com/pythonarcade/arcade/archive/refs/heads/maintenance.zip` as a requirement.

It detects replit env, disables antialiasing and has your pull request in it.

**Comment by einarf** [comment]
url dependencies don't seem to be allowed on replit. I guesss we'll have to wair for 2.5.7 or stick with 2.4.3 for a week.

**Comment by einarf** [comment]
2.5.7 is released
