### ISSUE TITLE
topdown tanks game

### ISSUE THREAD

**Issue by ghost** [pythonarcade/arcade#882]
when you add a physics engine, its very glitchy if the list is moving. for example if the physics engine is the player sprite and a wall list its fine but if its a player sprite and an enemy list then the player sprite glitches really badly

also does anyone know how to turn a sprite on a point?
(think of a tank turrent)

**Comment by pvcraven** [comment]
Need a bit more detail to be able to understand this issue. Reproducible code, and/or a video showing the issue.

Side note, keep in minde the default engine is very simple and works best with just a few moving sprites. If there is much interaction between multiple moving sprites you need a 'real' physics engine like PyMunk.

**Comment by ghost** [comment]
@pvcraven never mind, i got it fixed - but going back, is there anyway to turn a sprite on a point?

**Comment by pyweeker** [comment]
@24wuw visit my repo

**Comment by ghost** [comment]
@pyweeker which one? where? bruh so much random stuff
