### ISSUE TITLE
I found a way to save games with tiled maps

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#885]
Hello, it is still work in progress but it does work just now !
visit my repo Sarkadban which is a sokoban remix

```
def setup(self, level):
    self.troll_list = arcade.SpriteList()
    trolls_layer_name = 'Trolls_layer'
    map_name = f"resources/maps/level_{level}.json"
    my_map = arcade.tilemap.read_map(map_name)
    self.troll_list = arcade.tilemap.process_layer(map_object=my_map,
                                                      layer_name=trolls_layer_name,
                                                      scaling=TILE_SCALING,
                                                      use_spatial_hash=True)
        
        level = self.level
        troll_layer = 8
        map_name = f"resources/maps/level_{level}.json"
        with open(map_name, 'r') as f:
            precursor_content = json.load(f)

        data_gruyere = precursor_content['layers'][troll_layer]["data"]
        data_granit = list() #integers corresponding to textures

        for data in data_gruyere:
            if data != 0:
                data_granit.append(data)

        for troll_sprite in self.troll_list:
            troll_sprite.guid = data_granit[self.troll_list.index(troll_sprite)]



def on_key_press(self, key, modifiers):
if key == arcade.key.NUM_0: # SAVE IT
            level = self.level
            map_name = f"resources/maps/level_{level}.json"
            with open(map_name, 'r') as f:
                precursor_content = json.load(f)
            modif_trolls = [0 for i in range(grid_width * grid_height)]
            troll_layer_index = 8
            for troll in self.troll_list:
                troll_X = troll.center_x 
                troll_Y = troll.center_y

                column = (troll_X - topleftX) / (GRID_PIXEL_SIZE * TILE_SCALING)
                row = (topleftY - troll_Y) / (GRID_PIXEL_SIZE * TILE_SCALING)

                round_column = round(column)
                round_row = round(row)

                new_index = round_column + (round_row * grid_width)
                new_index = int(new_index)

                modif_trolls[new_index] = troll.guid

            precursor_content['layers'][troll_layer_index]["data"] = modif_trolls            

            with open(map_name, 'w') as modified_file:
                
                modified_file.write(json.dumps(precursor_content))
```

it's dirty but it does the job ;-)
https://github.com/pyweeker/sarkadban

**Comment by Cleptomania** [comment]
Should be noted if you’re intending to re-save the map in a way that can be re-loaded by pytiled-parser this solution won’t always work. In some instances of very simple maps it’s possible it could, but pytiled does a lot of processing on the raw data depending what’s there and converting raw data to Python types, so you would need to actually reverse that process in order to save fully compatible Tiled maps

**Comment by einarf** [comment]
It might be better to save some separate custom file with information on how to alter then loaded (original) map? This can also be combined with other game states you need to save.

**Comment by pyweeker** [comment]
become friends ! We have similar passions ! Life goes fast !
how is your life ?
may be we can meet in 10 years  or after !
Regards .

Le sam. 29 mai 2021 à 06:21, Einar Forselv ***@***.***> a
écrit :

**Comment by pyweeker** [comment]
Hi Darren, may be we should meet later as friends later, i'm not so far
from the border.
Regards.

Le sam. 29 mai 2021 à 03:14, Darren Eberly ***@***.***> a
écrit :

**Comment by pyweeker** [comment]
you are right i am thinking about that for next games

**Comment by ghost** [comment]
talking about finding new ways to do stuff... how can we submit code to be put on arcade.academy as tutorials? there isnt any fancy use interface stuff and no topdown game tutorial :(

**Comment by Cleptomania** [comment]
@24wuw All of the stuff on arcade.academy is in the `docs` of the repo here on GitHub. It’s built with Sphinx

**Comment by ghost** [comment]
@Cleptomania so all i hafta do is fork this, and make a pull request, and if approved my stuff will get on arcade.academy?

**Comment by Cleptomania** [comment]
@24wuw Yeah, it will go into development branch and be pushed to the live site during the next release. Keep in mind at this exact moment the development branch chad a lot of changes and is in a somewhat unstable state and we’re re-writing a lot of documentation/examples for 2.6. So the development branch might require some amount of tweaking your code to work with it.

**Comment by Cleptomania** [comment]
Going to close this as this really mostly pertains to pytiled-parser, and re-saving maps is something that would be on the roadmap for a 2.0 release of that probably, though I don't know when that's actually gonna happen.
