### ISSUE TITLE
Setting the number of segments in a circle doesn't work

### ISSUE THREAD

**Issue by pvcraven** [pythonarcade/arcade#886]
This code should draw a circle with 4 segments:

        arcade.draw_circle_outline(center_x=SCREEN_WIDTH / 2, 
                                   center_y=SCREEN_HEIGHT / 2, 
                                   radius=200, 
                                   color=arcade.color.BLACK, 
                                   border_width=10, 
                                   num_segments=4)

It doesn't. The `draw_ellipse_outline` passes in number of segments to the `tilt_angle` parameter instead. Even correcting that bug, setting the segment to 1-20 all makes for a circle of 40 segments, It doesn't change until you get to something like 30 segments.

**Comment by pvcraven** [comment]
Is there a need for MIN_SEGMENTS in the shader? What if someone wanted to use this function to make a quick pentagram?

**Comment by pvcraven** [comment]
...experiments show this works. Although to be practical, we'll need a parameter for tilt_angle.

**Comment by einarf** [comment]
Might be a bit risky increasing the max value unless you have concluded that 112 segments will emit maximum 256 vertices.
```glsl
#define MAX_SEGMENTS 112
```

**Comment by pvcraven** [comment]
Wouldn't it max around 224? Plus or minus for endpoints?

**Comment by einarf** [comment]
You are right about `Foroutline_unbuffered_geo.glsl`

`filled_unbuffered_geo.glsl` on the other hand emits 3 vertices per segment and should be clamped to 85.

If we need higher segment count there are tricks to work around that.

**Comment by pvcraven** [comment]
Ok, flipped back to 85.

**Comment by einarf** [comment]
Fixed in 2.6
