### ISSUE TITLE
`YELLOW_GREEN` in arcade/csscolor/__init__.py is incorrect.

### ISSUE THREAD

**Issue by amosnier** [pythonarcade/arcade#888]
`YELLOW_GREEN` in arcade/csscolor/__init__.py is incorrect. The blue component is missing.

**Comment by MisoMosiSpy** [comment]
I verified that this need to be changed from 

YELLOW_GREEN = (154, 205)

To 

YELLOW_GREEN = (154, 205, 50)

Just starting with arcade, can I take up this issue?

**Comment by pvcraven** [comment]
Yes, it is a bug. Yes, please go ahead and take up the issue! Please make changes in the development branch.

**Comment by MisoMosiSpy** [comment]
Thank you, I have created the pull request, hope I got everything right.

**Comment by Cleptomania** [comment]
Released with 2.6.0
