### ISSUE TITLE
Error: when using 'check for collision' with detailed mesh

### ISSUE THREAD

**Issue by ClasRCDM** [pythonarcade/arcade#889]
## Bug Report
- _**"A LinearRing must have at least 3 coordinate tuples"**_ with detailed mesh
### Steps to reproduce/example code:
#820 put the sprite as detailed and move it only
---
### What is wrong with it? How can it be improved?
I tried to fix it, but still can't, but it works normally with none and simple.

**Comment by pvcraven** [comment]
What version of Arcade? What sprite did you use? All sprites or just some?

**Comment by ClasRCDM** [comment]
### - I'm using a newer _**2.5.7**_ 
with _python **3.9.5,**_ it's running on all the sprites I use
---
#### I found how the error occurs, it is after changing the sprite, it only occurs in Detailed, but not in Simple
this is one of the sprites: 
![Kakito_grande4](https://user-images.githubusercontent.com/68075842/120938490-ed3b6a00-c6e0-11eb-8962-f298aaba4fa3.png)

**Comment by ghost** [comment]
it might be because there are components to the sprite that are seperated by white space. try editing them out w/ photoshop or something, and see if that works. im assuming you're using pymunk?

**Comment by ClasRCDM** [comment]
##### - Hey @24wuw, I'm not using pymunk

**Comment by pvcraven** [comment]
I tried doing a new sprite with:

    sprite = arcade.Sprite("cactus.png", hit_box_algorithm="Detailed")

...but it seemed to come out ok if I drew the hitbox with:

    self.sprite_list.draw_hit_boxes(arcade.color.RED, 2)

Do you get something different?

<img width="87" alt="cactus" src="https://user-images.githubusercontent.com/1463116/122767496-5a660800-d268-11eb-9f30-025ec2b4811f.png">

**Comment by pvcraven** [comment]
Closed for lack of new info.
