### ISSUE TITLE
AttributeError using the latest version of pytiled_parser

### ISSUE THREAD

**Issue by SeanCaulfield1** [pythonarcade/arcade#893]
### Actual behavior: Raises an attribute error:
```
Traceback (most recent call last):
  File "D:\Other\Coding\Python\Lights Out Game\LightsOut.py", line 2, in <module>
    import arcade
  File "C:\Users\jacka\AppData\Local\Programs\Python\Python39\lib\site-packages\arcade\__init__.py", line 261, in <module>
    from .tilemap import get_tilemap_layer
  File "C:\Users\jacka\AppData\Local\Programs\Python\Python39\lib\site-packages\arcade\tilemap.py", line 62, in <module>
    def get_tilemap_layer(map_object: pytiled_parser.objects.TileMap,
AttributeError: module 'pytiled_parser' has no attribute 'objects'
```
### My game script:
```
# Pip
import arcade

# Program variables
screenWidth = 1280
screenHeight = 720
screenTitle = "Lights Out"
backgroundColour = arcade.csscolor.SKY_BLUE


# Main class to manage the game
class LightsOut(arcade.Window):
    # Initialise variables
    def __init__(self):
        super().__init__(screenWidth, screenHeight, screenTitle)
        arcade.set_background_color(backgroundColour)

    # Function to initialise the game
    def setup(self):
        pass

    # Render the screen
    def on_draw(self):
        arcade.start_render()


# Start the game
game = LightsOut()
game.setup()
arcade.run()
```

I currently have pytiled-parser version 0.9.4a3 and the latest (where it occurs) is 1.5.0. Also the latest numpy version is 1.20.3 and arcade requires 1.20.1 (its probably minor tho).

**Comment by pvcraven** [comment]
If you use the latest version of pytiled, you have to download and use the
dev branch of arcade. Otherwise use the version of pytiled that is
specified for your  version of arcade.

**Comment by Cleptomania** [comment]
As of version 1.0.0 of pytiled-parser we completely re-wrote it from the ground up and pretty much 100% of the API changed as a result. 2.6 will be the first release of Arcade using the new version of pytiled-parser, and if you want like Paul said, you can install from the dev branch of Arcade to receive it now, but there are a number of other changes and unstable things in there right now.
