### ISSUE TITLE
conway's game of life

### ISSUE THREAD

**Issue by ghost** [pythonarcade/arcade#894]
https://arcade.academy/examples/conway_alpha.html#conway-alpha

in the conways game of life three alive blocks side by side should oscillate, but it stays a line in the code

it should flip between:

010
010
010

and:

000
111
000

where 1 is alive and zero is not, instead it stays in one line

**Comment by pvcraven** [comment]
I used the rules here: https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life

**Comment by pvcraven** [comment]
Not sure what to change here. Reopen with more info if you know of a change.
