### ISSUE TITLE
Need annual programing challenge event to promote Arcade

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#895]
Hello,
pyweek is an example, but where pygame is hegemonic.
 Arcade is more elegant and should have his own event to concentrate our production for learning, training, teaching.

**Comment by pvcraven** [comment]
I feel like there should be t-shirts too. But my design skills are sub-optimal.

**Comment by einarf** [comment]
We discuss this on discord, so closing for now. It's not forgotten.
