### ISSUE TITLE
How can i generate texture on the fly

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#897]
How can i generate dynamic texture inside update method and apply it on sprites ?

**Comment by einarf** [comment]
You should explain what you want to achieve doing this so we're not dealing with an xy problem here. The more details, the better.

Also remember we have a discord server that is a much better place to ask questions.

**Comment by pvcraven** [comment]
At some point we could use an example showing the use of the image library and feeding it to a texture. Today is probably not that day.

**Comment by ghost** [comment]
@pyweeker yes you could actually do that, if you're talking about what i think you're talking about.

if your player sprite has animations/extra functions, just put `self.hit_box = self.texture.hit_box_points` whenever it updates. if your player sprite just calls the parent class arcade.Sprite without adding anything, in your arcade.Window or arcade.View just do `self.player_sprite.hit_box` = self.player_sprite.hit_box_points`

if you then draw the hitbox, the hitbox moves updates along with the sprite animation!

**Comment by pyweeker** [comment]
hello !
have a look there https://github.com/benmoran56/esper
it seems interessant for coding games
pyweeker
