### ISSUE TITLE
Auto reload functionality

### ISSUE THREAD

**Issue by jacobj45** [pythonarcade/arcade#899]
### What should be added/changed?
Auto reload functionality where everything is automatically reloaded when a change occurs in the source files; similar to that provided by most web servers for development

### What would it help with?
It would very convenient and save a lot of time during development and debugging since the user doesn't have to close the window and rerun the script every time they make a change

**Comment by pvcraven** [comment]
Arcade is a development library, not a whole game development environment like Unity. This is outside the scope of what Arcade will do anytime soon.
