### ISSUE TITLE
SpriteList shuffle() not working

### ISSUE THREAD

**Issue by ErLa58** [pythonarcade/arcade#903]
arcade 2.5.7 on Win10
SpriteList shuffle() results in error message "SpriteList object has no attribute 'shuffle' "
(For what its worth : SpriteList reverse() works)

**Comment by MisoMosiSpy** [comment]
Issue is seen on 2.5.7.
However, Seems to be working on latest development version, checked on commit 43deadfcb2cffa628341bc4bf675891be543641f.

**Comment by einarf** [comment]
With 2.5 you just have to use `random.shuffle` (in python standard library)

**Comment by MisoMosiSpy** [comment]
What version the docs are based on? last released or current git ? 

Looks like the docs are for latest version https://arcade.academy/arcade.html#arcade.SpriteList.shuffle.

I think we should match it with last released version or mention that the docs are for latest development to avoid confusion.
Even better provide both and let user refer to once which they are using.

**Comment by MisoMosiSpy** [comment]
Docs page does mention that it for 2.6.0dev1. However I feel by default it should be for last stable release and optionally for the latest.

**Comment by einarf** [comment]
We're fixing the doc issue.

**Comment by einarf** [comment]
2.5.7 should be here now  : https://arcade.academy/
