### ISSUE TITLE
pymunk

### ISSUE THREAD

**Issue by ghost** [pythonarcade/arcade#904]
how do you turn a sprite in pymunk physics engine?

**Comment by Romuald78** [comment]
Pymunk does not handle sprites directly.

And the answer depends on type of physic component (dynamic or kinematic)

This post should concerns an issue but you are asking for an example of use.

I suggest to close this issue and ask for help to the arcade community on discord server

‐-----------------‐

Here is a start of answer anyway.

For dynamic pymunk body, i would suggest to set the sprite angle equals to the pymunk body angle

For kinematic pymunk body, i would suggest the opposite, rotate your sprite using Sprite.angle property, then set the pymunk body angle equals to the sprite angle

Warning, if i remember well, pymunk angles are in radians,  and arcade angles in degrees

Hope it helps
