### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dalyeerh** [pythonarcade/arcade#905]
## Bug Report
when  draw_xywh_rectangle_textured is in code
this error appears:
AttributeError: module 'arcade' has no attribute 'draw_xywh_rectangle_textured'

**Comment by ghost** [comment]
this is because arcade has no such thing
there is `arcade.draw_xywh_rectangle_filled` and `arcade.draw_xywh_rectangle_outline`
could you put your code in, and i can rewrite it for you so that it works

**Comment by dalyeerh** [comment]
hi its not my code but this is the website:
https://github.com/BramCetusAlt/Stellar-Arena
if you code fix it, it would be great.

Thanks

**Comment by einarf** [comment]
Are you using arcade 2.1.6 like the README of that project states is needed?

This also sounds like a bug you should report here : https://github.com/BramCetusAlt/Stellar-Arena/issues

**Comment by dalyeerh** [comment]
how do i change the python arcade version.

**Comment by einarf** [comment]
Look at the install command here : https://github.com/BramCetusAlt/Stellar-Arena#installation

Is that doesn't work you need to poke the person who made the game

**Comment by dalyeerh** [comment]
Thanks!

**Comment by dalyeerh** [comment]
hi, I have reinstalled python arcade following the instructions laid out previously. I am now getting this error
AttributeError: module 'pytiled_parser' has no attribute 'objects'
any idea how to fix it?

**Comment by einarf** [comment]
If you followed the instructions here ... https://github.com/BramCetusAlt/Stellar-Arena#installation

and it still dooesn't work you will have to contant the author of the project. This has very little to do with the arcade project itself. I suggest you make an issue in the Stellar-Arena project about unclear install instructions.
