### ISSUE TITLE
Typo in pymunk tutorial 

### ISSUE THREAD

**Issue by quirky-bluejay** [pythonarcade/arcade#909]
## Documentation request:
Typo in typing `self.physics_engine`

### What documentation needs to change?
`=` to `:`
ie
``` diff
- self.physics_engine = Optional[arcade.PymunkPhysicsEngine]
+ self.physics_engine: Optional[arcade.PymunkPhysicsEngine]
```

### Where is it located?
https://arcade.academy/tutorials/pymunk_platformer/index.html#id7
https://arcade.academy/tutorials/pymunk_platformer/index.html#id34https://arcade.academy/tutorials/pymunk_platformer/pymunk_demo_platformer_12.html

Not sure if I have found all instances of this typo

### What is wrong with it? How can it be improved?
`self.physics_engine` is being set to a type. 
This doesn't effeft the code running however mypy does compain. 
for example:
```shell
main.py:141: error: "object" has no attribute "is_on_ground"
main.py:143: error: "object" has no attribute "apply_impulse"
main.py:155: error: "object" has no attribute "is_on_ground"
main.py:161: error: "object" has no attribute "apply_force"
main.py:167: error: "object" has no attribute "apply_force"
main.py:168: error: "object" has no attribute "set_friction"
main.py:170: error: "object" has no attribute "set_friction"
main.py:172: error: "object" has no attribute "step"
Found 8 errors in 1 file (checked 1 source file)
```

**Comment by Cleptomania** [comment]
This is fixed with 2.6.0 however the Pymunk platformer tutorial needs fixed up for 2.6.0 still. I’ll create a new issue for that.
