### ISSUE TITLE
documentation muti windows example

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#913]
Hello team,
is it possible to get this look with an example script ?

![prorealtime example](https://chartsinside.fr/wp-content/uploads/2020/01/Tutoriel-ProRealTime-Afficher-Plusieurs-Unites-De-Temps-En-Un-Clic-02.png)

**Comment by einarf** [comment]
The UI library in 2.6 will at least have widgets you can render anything into in local widget coordinates. Stay tuned for docs/release.
