### ISSUE TITLE
pyglet.gl.lib.GLException: b'invalid enumerant'

### ISSUE THREAD

**Issue by streetartist** [pythonarcade/arcade#914]
I know it has been discussed already, but you can know that it has not fixed

![image](https://user-images.githubusercontent.com/60282562/126034881-ab1d341b-173e-4703-891c-9faa15ee3030.png)

I use `antialiasing=False`,but it does not work!!

**Comment by einarf** [comment]
What version of arcde?

**Comment by einarf** [comment]
This error seems to be different. The drivers don't know about the `GL_CONTEXT_PROFILE_MASK` for some reason.

**Comment by streetartist** [comment]
It is the newest arcade.

**Comment by streetartist** [comment]
I know my GPU only supports OpenGL3.1

**Comment by einarf** [comment]
> I know my GPU only supports OpenGL3.1

That's probably the issue. Arcade can potentiall work with some 3.1 drivers, but it requires 3.3 as a mimimum.

**Comment by streetartist** [comment]
But i think arcade must support older GPU. Even big engines like Godot 、 Unity 3D and Pygame still support old GPU too. There are many computers using old GPU. Arcade must support them in order to have more users. You can imagine that if someone uses Arcade to make a game and then shares it with his friends, but his friends' computer can not run the game. He will be very very upset And Even never use Arcade any more. I think it is terrible. So Arcade must support old GPU.

**Comment by einarf** [comment]
I would suggest you use pyglet instead if you want support for a lower opengl version. We rely too heavily on OpenGL 3.3 features that reverting from that would be a huge challenge.

You could try to alter arcade a bit removing the parts that causes the problems. It can work in some instances.

What is your current gpu? We expect anything made in the last 10 years to work if your OS has proper drivers for it. Even integrated gpus today support opengl 4.5 or higher. (last two generations of amd and intel at least)

**Comment by streetartist** [comment]
my computer is dell inspiron 1427. my GPU is nVidia GeForce 9200M GS.
Dell has stopped support my computer in 2009.But nVidia keeps supporting it. The newest driver is support on 2020-9.But I Do not know if I can install it in my Dell computer.I want to ask You for advice.

**Comment by streetartist** [comment]
It supports Opengl3.3
https://www.techpowerup.com/gpu-specs/geforce-9200m-gs.c1525

**Comment by einarf** [comment]
It's more likely to be a driver issue. I bet it aracde would work on linux with mesa drivers for you.

You can try to comment out the line that is causing the issue and see if you get any further.
```
self.CONTEXT_PROFILE_MASK = ...
```

**Comment by einarf** [comment]
It's possible that we can get arcade to work on your GPU. I could potentially make a compatibility branch, but I would need you to test it sice we don't have the hardware available. Many of the old drivers stating OpenGL 3.1 do support most 3.3 features with only a few things you need to work around.

You would need to fork arcade and alter it and/or show me the stack traces you are getting.

**Comment by streetartist** [comment]
- I want to ask if I can install the driver supported by nVidia.
- - The newest driver supported by nVidia supports OpenGL 3.3, I know.
- - But I wonder whether it can run well on my Dell inspiron 1427 with Windows 7 , so I ask you for advice.(Because Dell do not provide new driver.)
- I will test the branch for Arcade

**Comment by einarf** [comment]
I have no idea about the drivers to be honest.

To progress on this issue you will have to comment out this line in arcade and tell me if you get any further :
https://github.com/pythonarcade/arcade/issues/914#issuecomment-884116068

**Comment by streetartist** [comment]
Ok.Because I am a student,I do not have so much time(Although it is on Summer Holiday,We Chinese students should also work hard.). I may test it on weekends. I am sorry to make you wait.

**Comment by pvcraven** [comment]
Closed, reopen if new info comes.
