### ISSUE TITLE
Add support for Tiled Image Layers

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#916]
Hello, i can do work tile layers and object layers but i can not display the image layer for my background.
Does it already work ? an example ?

**Comment by pvcraven** [comment]
I'm guessing there's no support. I've never played around with it  before.

**Comment by Cleptomania** [comment]
It has not been implemented yet, it will be done by the time we release 2.6 though. The work has been done in pytiled parser for it, but still have to do the implementation in Arcade, it should be pretty easy. I will add it to my list for this weekend and finish it up.

I’m going to close this issue in favor of tracking it with #863.

**Comment by pyweeker** [comment]
hello, idea of hack while waiting for it ?
something like 
```
arcade.draw_lrwh_rectangle_textured(0, 0,
                                                SCREEN_WIDTH, SCREEN_HEIGHT,
                                                self.background)
```
?
