### ISSUE TITLE
dev branch : Scene.draw with linear filter

### ISSUE THREAD

**Issue by EnlNovius** [pythonarcade/arcade#918]
I was looking for a way to use a linear filter while drawing TileMap. In 2.5.7 I was using `SpriteList.draw(filter=gl.GL_LINEAR)` to draw every layer one by one. In 2.6.0 a new solution for drawing TileMap is available with Scene.draw(). Howether you can't pass to Scene.draw() any argument. 

Is it possible to state somewhere that the filter to be used for all future renderings is the linear filter?

Otherwise:
 
## Enhancement request:

To have the possibility to transmit arguments through Scene.draw to SpriteLists.draw, for example `filter = gl.GL_LINEAR`.

An easy solution is the use of a `**kwargs` in Scene.draw : 

```
    def draw(self, names: Optional[List[str]] = None, **kwargs) -> None:
        """
        Draw the Scene.

        If `names` parameter is provided then only the specified SpriteLists
        will be drawn. They will be drawn in the order that the names in the
        list were arranged. If `names` is not provided, then every SpriteList
        in the scene will be drawn according the order of the main sprite_lists
        attribute of the Scene.

        :param Optional[List[str]] names: A list of names of SpriteLists to draw.
        """
        if names:
            for name in names:
                self.name_mapping[name].draw(**kwargs)
            return

        for sprite_list in self.sprite_lists:
            sprite_list.draw(**kwargs) 
```

**Comment by Cleptomania** [comment]
I think what would be better would be to set this as an option to each SpriteList. The problem with passing the value to `Scene.draw` is that it would be applied to every SpriteList in the scene. Having a way to set options using a dictionary on the SpriteList would allow setting it for each one individually.

It could work much like the layer_options dict in Tilemap. I’ll work up something for this tomorrow.

**Comment by einarf** [comment]
You could have both?

**Comment by EnlNovius** [comment]
While on the subject, making a first draw with gl.GL_LINEAR makes subsequent draws use gl.GL_LINEAR, even if the option is not specified for these draws.

**Comment by Cleptomania** [comment]
I implemented the proposed solution in the dev branch. I'll look into potential per layer settings down the road a bit. For now if you really need it set per sprite list you can do a couple things:

- Use multiple scenes(though this would require some manual doing if you're also using Tiled maps)
- Grab the spritelists from the scene and draw them directly instead of using `Scene.draw`
- Don't use a scene and render the spritelists directly

**Comment by pvcraven** [comment]
Looks like it was implemented, I'm going to go ahead and close. Yell if that's not right.
