### ISSUE TITLE
FIX: test_placed_widget.py

### ISSUE THREAD

**Issue by niklasfriberg** [pythonarcade/arcade#920]
I'm attempting to fix the tests in test_placed_widget.py which display the following error when executing:
TypeError: Can't instantiate abstract class Widget with abstract method render

I tried using the Dummy class instead of Widget as parent and child but the x and y coordinates are always 0.
Is there a better class to use as parent and child to the widget for this test?

**Comment by eruvanos** [comment]
Thanks for looking into this, always appreciate  help. I fixed the problem, which contained also some renaming (PlacedWidget -> AnchorWidget)

The Dummy widget was the right one to use, not sure why it was giving always 0.
