### ISSUE TITLE
Bug with camera.viewport_width ?

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#923]
Hello,
i am trying to make a top down shoot 'em up 
i am using Tiled for the map.
i copy paste arcade dev branch folder in my project.
i get this:

in on_draw
    self.camera.use()
  File "/home/me/Bureau/xenon2/arcade/camera.py", line 169, in use
    self.update()
  File "/home/me/Bureau/xenon2/arcade/camera.py", line 106, in update
    self.viewport_width + math.floor(result_position[0]),
TypeError: unsupported operand type(s) for +: 'Window' and 'int'

the error does not seem to appear with the height.

**Comment by pyweeker** [comment]
```
def on_draw(self):

        self.camera.use()
        #self.clear()
        self.window.clear()


        arcade.start_render()
        self.background_list.draw()


        self.scene.draw()


        self.center_on_player()

        self.gui_camera.use()
```

**Comment by pvcraven** [comment]
Creating the camera expects width, height, then an optional window parameter. This error occurs when the window is passed in as a size.

Originally in the dev cycle camera had the ordering of the constructor with window first, so older code no longer works.
