### ISSUE TITLE
Add layer function?

### ISSUE THREAD

**Issue by streetartist** [pythonarcade/arcade#924]
Can Arcade add layer function to draw sprite on different layers?

**Comment by Cleptomania** [comment]
There is SpriteList, it’s covered in this tutorial https://api.arcade.academy/en/latest/examples/platform_tutorial/step_02.html

**Comment by streetartist** [comment]
What I mean is that the Sprite object should have a layer property. When two Sprites overlap each other, the one with the larger layer value is displayed on top of the other.

**Comment by Cleptomania** [comment]
Draw order is determined exclusively by the order in which you draw things. Ordering the drawing of a Sprites within a list would be a rather expensive operation to add for draw time I believe.

What’s better is to maintain SpriteLists for different types of Sprites, and draw them in the order you want to display them.

so for example let’s say you have an Enemies SpriteList and a Player SpriteList, and you want the player to always appear above the enemies, then simply ensure that you draw the enemy SpriteList first, and then the player one.

The new Scene class in 2.6 has some concept of Layers, you assign names to SpriteLists within the Scene and can insert new SpriteLists before/after a given spritelist within the scene. Then you call `scene.draw()` it will always follow the pre-determined draw order.

**Comment by streetartist** [comment]
Yes.I know.

**Comment by streetartist** [comment]
Yes. I know.

**Comment by streetartist** [comment]
Yes.I know

**Comment by streetartist** [comment]
You can close the Issue
