### ISSUE TITLE
pyglet.gl make it hard to edit the code of Arcade.

### ISSUE THREAD

**Issue by streetartist** [pythonarcade/arcade#925]
In the code of Arcade, you use `from pyglet import gl` to use OpenGL.
But it makes it hard to edit the code of Arcade.
I think use ModernGL library like Wasabi2d or Heat2d is better.

**Comment by streetartist** [comment]
Maybe you can write some tutorials to help developer edit the Arcade code as well.

**Comment by pvcraven** [comment]
Thanks for the suggestion, although I don't see us changing that any time soon. We'd need a pretty strong feature-need to recode everything.
