### ISSUE TITLE
Custom hitboxes don't follow Tiled Map Rotation

### ISSUE THREAD

**Issue by pvcraven** [pythonarcade/arcade#929]
The tiles will rotate, but not the hitboxes for tiled maps:

<img width="324" alt="hitboxes" src="https://user-images.githubusercontent.com/1463116/130366274-c3584254-6729-431f-b483-2f016b123b9f.png">

**Comment by Cleptomania** [comment]
Is this for Tiles with a custom object used for the hit box I assume? I would imagine this effects 2.5 and 2.6, as I think the base code for loading object positioning was largely untouched

**Comment by pvcraven** [comment]
It is current 2.6 using the 'flip' buttons in a regular tile layer. I do not get why it isn't working. It looks like the hitbox calculation happens after the image rotation, so I just don't understand.

**Comment by pvcraven** [comment]
This is if there is a CUSTOM hit box.

**Comment by Cleptomania** [comment]
Released with 2.6.0
