### ISSUE TITLE
The website is broken

### ISSUE THREAD

**Issue by Python-Is-Long** [pythonarcade/arcade#930]
All resource pictures are missing on the website. 
https://api.arcade.academy/en/latest/resources.html
![image](https://user-images.githubusercontent.com/72286000/130626830-34c86438-d811-47bb-8ce1-3fdb56408e51.png)

**Comment by pvcraven** [comment]
That's not going to get fixed for the 2.5.7. You can grab the current development stream where it is fixed:

https://api.arcade.academy/en/development/resources.html
