### ISSUE TITLE
Opening Tiled ImageLayer crashes without offset

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#931]
### Actual behavior:
Loading an image layer with horizontal and vertical offset = 0,00 raises an exception:

`Traceback (most recent call last):
  File "[...]\arcade\tilemap\tilemap.py", line 826, in load_tilemap
    return TileMap(
  File "[...]\arcade\tilemap\tilemap.py", line 190, in __init__
    self._process_layer(layer, global_options, layer_options)
  File "[...]\arcade\tilemap\tilemap.py", line 227, in _process_layer
    processed = self._process_image_layer(layer, **options)
  File "[...]\tilemap\tilemap.py", line 570, in _process_image_layer
    my_sprite.center_x = (layer.offset[0] * scaling) + my_sprite.width / 2
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1`

Setting either horizontal or vertical offset (or both) to any nonzero value makes the exception go away.

### Expected behavior:
ImageLayer with zero offsets gets successfully loaded with zero offsets.

### Steps to reproduce/example code:
Create an image layer in Tiled with horizontal and vertical offset == 0,00 and load into TileMap.

**Comment by bunny-therapist** [comment]
Arcade version:
arcade @ git+https://github.com/pythonarcade/arcade.git@2ee473e4217618651cef5dccbdca33d0c1871371

**Comment by Cleptomania** [comment]
Hmmm this is likely a problem with pytiled parser. My guess is other layer types fill in 0 values in the JSON whereas ImageLayers must be leaving the field out completely, and putting one of them in causes it to add both into the json.

I’ll probably just need to default those values to 0 if they’re not present. I’ll look into it and get a fix in sometime today.

**Comment by Cleptomania** [comment]
Pushed out v1.5.3 of pytiled-parser and updated Arcade's requirement for it in 8a9726d619666caeafc321ec3c4df90e10590f90

Make sure it installs the new version(1.5.3) of pytiled-parser as the fix is solely in that.

I've done some testing and it seems to be fixed and functioning as expected so I'm gonna close this, feel free to re-open if there's any remaining problem.
