### ISSUE TITLE
Update Pymunk platformer tutorial for 2.6

### ISSUE THREAD

**Issue by Cleptomania** [pythonarcade/arcade#932]
The Pymunk platformer tutorial still needs updated for 2.6. I believe some pieces of the code have been updated, but I don’t think the whole thing has. I know at the least the line highlighting in the tutorial is broke. Because of re-writing some pieces of the code.

**Comment by pushfoo** [comment]
#976 is a duplicate of this ticket, and #979 is a prerequisite for this to be closed,

**Comment by einarf** [comment]
I would think this one should be closed?
