### ISSUE TITLE
Multiple documentation links broken

### ISSUE THREAD

**Issue by caffeinepills** [pythonarcade/arcade#936]
## Bug Report
On the readme.rst, the following bolded links are broken:

Documentation
For full documentation see http://arcade.academy
**For installation: http://arcade.academy/installation.html
For example code that uses the Arcade library see: http://arcade.academy/examples/index.html
For API documentation see: http://arcade.academy/quick_index.html**
Learn Arcade AND how to program: https://learn.arcade.academy
**Release notes: http://arcade.academy/release_notes.html**

Games Using Arcade
**See: http://arcade.academy/sample_games.html**

**Comment by pvcraven** [comment]
Fixed, thanks.
