### ISSUE TITLE
Unable to bind multiple sampler2D's to a fragment shader

### ISSUE THREAD

**Issue by DragonMoffon** [pythonarcade/arcade#939]
I was developing a shader that takes in a Mercator map and projects it to a sphere, and I found 2 Issues with uniforms within my gl fragment shader. One is an enhancement that would make life a lot easier, and the other is a bug. 

I realized that these are two separate issues and I've split them into to separate issues.

## Bug Report
The other issue is with binding textures to uniforms. 

It seems that when I call texture.use(0) it binds all active sampler2Ds to that texture and it completely ignores the rest, and If texture.use() is never called it binds all active sampler2Ds to the last texture created.

For example:
Vertex Script: [basic_vertex.glsl]
```
#version 430

in vec2 vert_pos;

void main() {
	gl_Position = vec4(vert_pos, 0, 1);
}
```
Fragment Script: [example_frag.glsl]
```
#version 430

layout(location = 0) uniform sampler2D fist_half;
layout(location = 1) uniform sampler2D second_half;

uniform vec2 screenRes;

in vec4 gl_FragCoord;

out vec4 fragColor;


void main() {
    if (gl_FragCoord.x/screenRes.x > 0.5)
	{
		fragColor = texture(second_half, gl_FragCoord.xy/screenRes);
	}
	else
	{
		fragColor = texture(fist_half, gl_FragCoord.xy/screenRes);
	}
}
```
Python code:
```
from array import array
from PIL import Image

import arcade
import arcade.gl as gl

first_image = Image.open("equirectangular.png")
second_image = Image.open("earth_dark.png")

SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600


class Window(arcade.Window):

    def __init__(self):
        super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, "sampler2D example")
        self.program = self.ctx.load_program(vertex_shader="basic_vertex.glsl",
                                             fragment_shader="example_frag.glsl")

        self.buffer = self.ctx.buffer(data=array('f', (-1, -1, -1, 3, 3, -1)))
        self.geometry = self.ctx.geometry([gl.BufferDescription(self.buffer, '2f', ['vert_pos'])])
        self.program['screenRes'] = SCREEN_WIDTH, SCREEN_HEIGHT

        self.first_half = self.ctx.texture((720, 360), data=first_image.tobytes(), components=3)
        self.second_half = self.ctx.texture((720, 360), data=second_image.tobytes(), components=3)

    def on_draw(self):
        arcade.start_render()
        self.first_half.use(0)
        self.second_half.use(1)

        self.geometry.render(self.program, mode=self.ctx.TRIANGLES)


if __name__ == '__main__':
    window = Window()
    arcade.run()
```
The two images I'm using in the example: (they're upside down because gl_FragCoord has y = 0 at the top, so they get flipped)
![equirectangular](https://user-images.githubusercontent.com/86714785/131942134-94e8debe-f10d-47db-9495-76570398b64c.png)
![earth_dark](https://user-images.githubusercontent.com/86714785/131942131-737c18c3-a67a-40ce-b369-913213f14469.png)

### Actual behavior:
When I run the above code I get:
![image](https://user-images.githubusercontent.com/86714785/131942297-e9ed0504-23a0-4e98-ad77-84dc88a01217.png)

And if I flip

```
self.first_half.use(0)
self.second_half.use(1)
```

to

```
self.first_half.use(1)
self.second_half.use(0)
```

I get

![image](https://user-images.githubusercontent.com/86714785/131942385-bf5e9e13-de52-45aa-95fb-af81c0c7cb9c.png)

### Expected behavior:
I'd expect to see half the screen be the day map of earth, and the other half be the night map of earth. like this:

![image](https://user-images.githubusercontent.com/86714785/131943604-0b37ca88-5b9f-4cf8-a691-33c3275c0f19.png)

**Comment by einarf** [comment]
Weird. What happens if you assign channels to the sampler uniforms manually?

**Comment by DragonMoffon** [comment]
I've tried importing pyglet.gl and manually calling the binding to no avail. 

Everything lines up with the Opengl documentation so I went looking through the Texture class and I found something strange in the __init__ [line 135 to 145 of arcade/gl/texture.py].

```
gl.glActiveTexture(gl.GL_TEXTURE0)  # Create textures in the default channel (0)

        self._glo = glo = gl.GLuint()
        gl.glGenTextures(1, byref(self._glo))

        if self._glo.value == 0:
            raise RuntimeError(
                "Cannot create Texture. OpenGL failed to generate a texture id"
            )

        gl.glBindTexture(self._target, self._glo)
```

That may be correct I don't have much experience with Opengl to be honest, but it seems strange to bind the texture when we first create it.

**Comment by einarf** [comment]
I assumed you were using arcade 2.6 as version was not stated. We now create textures in the last texture channel to not interfere with binding : https://github.com/pythonarcade/arcade/blob/357d6222abd9ff55bf031a9bd76610907fc2ae90/arcade/gl/texture.py#L136-L144

The binding is also pretty straight forward
https://github.com/pythonarcade/arcade/blob/357d6222abd9ff55bf031a9bd76610907fc2ae90/arcade/gl/texture.py#L583-L589

I will still have to test your example locally. Will be in the weekend. It's probably something trivial.

**Comment by DragonMoffon** [comment]
Yeah I realized I had not updated arcade properly (I thought I was in 2.6 but I wasn't). I've updated arcade and tried manually binding the textures. It still doesn't work.

**Comment by einarf** [comment]
Thanks. I will look at this asap 😄

**Comment by einarf** [comment]
I just realized the problem. You are using the `location` qualifier. This only controls the index of the uniform in the program. It has nothing to do with the texture channel mapping.

If we print the texture channels in the render loop like this 
```py
print(self.program["fist_half"], self.program["second_half"])
```
We'll see the following output
```
0 0
0 0
0 0
...
```
meaning both samplers read from texture channel 0. Clearly something is wrong.

Since both are 0 we can configure them during initialization 
```py
self.program["fist_half"] = 0
self.program["second_half"] = 1
```

OR what you were probably trying to do initially.. set the channel in the shader itself. This is done with the `binding` qualifier.
```glsl
layout(binding = 0) uniform sampler2D fist_half;
layout(binding = 1) uniform sampler2D second_half;
```
Printing the uniform values will now show the right channels
```
0 1
0 1
0 1
...
```

**Comment by einarf** [comment]
FYI: We also have a `ctx.load_texture` method : https://github.com/pythonarcade/arcade/blob/ad01f00a9cb2463305ebaba3d3d3666281cf2b3e/arcade/context.py#L346-L381

**Comment by DragonMoffon** [comment]
Oh awesome. Thank you!

**Comment by einarf** [comment]
One thing to also remember is that you can probably downgrade your glsl version to 3.3 by not using the binding qualifiers in the glsl source and instead assign channels in python, Then your code will run on way more computers and platforms. For example: MaxOS only supports 4.1 and many slightly older integrated only support 3.3 -> 4.2
