### ISSUE TITLE
Bloom example does not appear correctly

### ISSUE THREAD

**Issue by caffeinepills** [pythonarcade/arcade#946]
## Bug Report

The bloom example doesn't seem to be applying a bloom effect.

### Actual behavior: 
![image](https://user-images.githubusercontent.com/17804711/132413697-212a4fd4-200d-4604-b930-721973e044b5.png)

### Expected behavior:  In the Arcade images it shows it should look like this.
![Image](https://api.arcade.academy/en/stable/_images/bloom_defender.png)

### Steps to reproduce/example code:

I am just running Arcade 2.6.1 from PIP and using the example `examples/bloom_defender.py` included with the installation.

```
OS: Windows 10
Python: Python 3.7.7

Graphics Info:
gl_info.get_version(): 3.3.0 - Build 27.20.100.9320
gl_info.get_vendor(): Intel
gl_info.get_renderer(): Intel(R) UHD Graphics 620
```

**Comment by pvcraven** [comment]
I thought I'd deleted this. I have different bloom code that needs to work its way into an example soon.

**Comment by einarf** [comment]
Deleting this example. It's not an ideal scenario for glow/bloom since the objects needing glow is too small. It has also been broken for a long time. A better example is https://github.com/pythonarcade/arcade/blob/development/arcade/experimental/shapes_buffered_2_glow.py
