### ISSUE TITLE
Fallback for antialiasing when drivers don't support it (Software, WSL etc)

### ISSUE THREAD

**Issue by Scowley4** [pythonarcade/arcade#948]
### Actual behavior:

Running the [template.py](https://api.arcade.academy/en/latest/examples/starting_template.html#starting-template) from the examples produces an error "Unable to create an OpenGL 3.3+ context". 

<details><summary>Full Error Output</summary>

```
Traceback (most recent call last):
  File "/home/scowley4/game-making/arcade-testing/env/lib/python3.8/site-packages/arcade/application.py", line 110, in __init__
    super().__init__(width=width, height=height, caption=title,
  File "/home/scowley4/game-making/arcade-testing/env/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/scowley4/game-making/arcade-testing/env/lib/python3.8/site-packages/pyglet/window/__init__.py", line 547, in __init__
    config = screen.get_best_config(config)
  File "/home/scowley4/game-making/arcade-testing/env/lib/python3.8/site-packages/pyglet/canvas/base.py", line 198, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "template.py", line 101, in <module>
    main()
  File "template.py", line 94, in main
    game = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
  File "template.py", line 27, in __init__
    super().__init__(width, height, title)
  File "/home/scowley4/game-making/arcade-testing/env/lib/python3.8/site-packages/arcade/application.py", line 115, in __init__
    raise NoOpenGLException("Unable to create an OpenGL 3.3+ context. "
arcade.application.NoOpenGLException: Unable to create an OpenGL 3.3+ context. Check to make sure your system supports OpenGL 3.3 or higher.
```
</details>

<details><summary>OpenGL Versioning</summary>

```
$ glxinfo | grep -i "opengl.*version"
libGL: MESA-LOADER: dlopen(/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/scowley4/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/scowley4/.drirc: No such file or directory.
OpenGL core profile version string: 3.3 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.3 (Compatibility Profile) Mesa 21.0.3
OpenGL shading language version string: 4.50
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
</details>

I am running on Windows 10 WSL2. After attempting many different with the OpenGL side of things, I finally came across #635 where it's mentioned a few times this may be related to antialiasing. In the case of that issue, it didn't appear to be antialiasing.

However, for me, this _did_ solve the problem.
```python

    def __init__(self, width, height, title, antialiasing=True):
        super().__init__(width, height, title, antialiasing=antialiasing)
...
game = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE, antialiasing=False)
```
### Expected behavior:

As @einarf mentions [here]( https://github.com/pythonarcade/arcade/issues/635#issuecomment-612652742), "maybe arcade should have a fallback for this case?". I think the fallback with a warning would be a good way to go. Or just a much more helpful error message.

----

I'm super new to arcade (just got the template code working 15 minutes ago). Anything I should consider doing to enable antialiasing? Will not using it lead to any problems moving forward?

**Comment by einarf** [comment]
I have never tried arcade in WSL2 and frankly not sure how it could run there. Are you expecting a window to pop up or using arcade in headless mode?

**Comment by Scowley4** [comment]
I might not be using the right terminology, but I'm running a VcXsrv server to display GUI applications through WSL2. Turning off antialiasing (as shown in original post) allowed the arcade window to show up on the VcXsvr screen.

**Comment by einarf** [comment]
My bad. I misread thinking it still did not work.

What probably happens is that the OpenGL drivers are emulated in software. This usually don't support MSAA framebuffers. A trick to get antialiasing with software rendering is rendering to an offscreen framebuffer twice as large as the window and render that back into the window. It will be a bit more costly to render your content. This can be done with the low level rendering api in arcade.

Not having antialiasing enabled is a minor problem for most people.

**Comment by einarf** [comment]
We should also look into into a better fallback when MSAA is not supported.

**Comment by einarf** [comment]
From Benjamin:

This is the recommended fallback from the pyglet docs:
```py
template = gl.Config(sample_buffers=1, samples=4)
try:
    config = screen.get_best_config(template)
except pyglet.window.NoSuchConfigException:
    template = gl.Config()
    config = screen.get_best_config(template)
window = pyglet.window.Window(config=config)
```
I would say the only way to be sure is to just pass in major/minor and nothing else.

**Comment by einarf** [comment]
Fixed. We now do a fallback to non-MSAA config.

**Comment by einarf** [comment]
2.6.6 is out
