### ISSUE TITLE
Typos in GUI Widgets doc

### ISSUE THREAD

**Issue by ghost** [pythonarcade/arcade#949]
### What documentation needs to change? 
* `align_x – offset for y value (- = down, + = up)` -> `align_y – offset for y value (- = down, + = up)`
* `y – x coordinate of bottom left` -> `y – y coordinate of bottom left`

### Where is it located?
[arcade-gui-uiwidget](https://api.arcade.academy/en/latest/api/gui_widgets.html#arcade-gui-uianchorwidget)

### What is wrong with it? How can it be improved?

* In the `parameters` of `arcade.gui.UIAnchorWidget`,  `align_x – offset for y value (- = down, + = up)` should be `align_y – offset for y value (- = down, + = up)`
* In the `parameters` of `arcade.gui.UIBoxLayout`, `y – x coordinate of bottom left` should be `y – y coordinate of bottom left`
* the format of the `parameters` of `arcade.gui.UIInputText` is incorrect

**Comment by eruvanos** [comment]
Thanks, fixed it.

**Comment by einarf** [comment]
Fixed in 2.6.3. Be free to reopen
