### ISSUE TITLE
Small circles aren't circles

### ISSUE THREAD

**Issue by pvcraven** [pythonarcade/arcade#950]
Small circles don't have enough points and render as polygons. This code:
```py
import arcade

arcade.open_window(800, 300, "Test")
arcade.set_background_color(arcade.color.WHITE)
arcade.start_render()

x = 10
for radius in range(1, 30):
    arcade.draw_circle_filled(x, 150, radius, arcade.color.BLACK)
    x += 40

arcade.finish_render()
arcade.run()
```

Renders as:

<img width="601" alt="2021-09-09_16-15-30" src="https://user-images.githubusercontent.com/1463116/132763808-04cef34e-ca50-4f21-9e65-ea5a369b9b38.png">

Lots of complaining in my intro class.

**Comment by einarf** [comment]
Probably just need to change the segment formula using a higher min value. You can manually specify the number of segments to make it look nicer of course, but the default needs to be more sane

**Comment by pvcraven** [comment]
I worry this change might have too many segments, but it does look better.
<img width="600" alt="2021-09-10_9-32-19" src="https://user-images.githubusercontent.com/1463116/132870288-f34d21b7-ba0f-4285-abfd-1d267d713736.png">

**Comment by einarf** [comment]
I don't think it's a huge problem. It's created by the geo shader anyway. The only concern I have is that it changes behavior from previous versions... but .. circles should be circles?
