### ISSUE TITLE
[idea] libretro port

### ISSUE THREAD

**Issue by eadmaster** [pythonarcade/arcade#956]
As alternative to  [pyinstaller deployment](https://api.arcade.academy/en/latest/tutorials/bundling_with_pyinstaller/index.html), i think it would be easier to use a libretro core with a full python interpreter inside, similar to
https://github.com/libretro/libretro-lutro
https://github.com/libretro/libretro-chailove

It will also have the added benefit of increasing the library supported platforms.

To consider: an alternative CPython interpreter could be used for this.

**Comment by einarf** [comment]
I'm not sure what the scope of this change would be. If it's something huge I things we would probably rely on someone maintaining a fork?
