### ISSUE TITLE
Sprite getting blurred after scaling

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#958]
Run this code:
```
import arcade
arcade.open_window(600, 400, 'Image Scale')
arcade.start_render()
sprite = arcade.Sprite('image.png', 10, center_x=300, center_y=200)
sprite.draw()
arcade.finish_render()
arcade.run()
```

Getting blurred sprite:

![изображение](https://user-images.githubusercontent.com/21060932/133917452-fbf575af-3482-448b-92b0-d8aea0b2f58f.png)

Is it possible to apply "Nearest Neighbor" algorithm for scaling? Like in Photoshop:

![изображение](https://user-images.githubusercontent.com/21060932/133917682-6056eca3-6cce-4db7-91d2-46e35e0bb0c1.png)

`image.png`:
![изображение](https://user-images.githubusercontent.com/21060932/133917655-4c3dab78-64f4-4c23-91d0-e2838df88142.png)

**Comment by einarf** [comment]
```py
spritelist.draw(filter=self.ctx.NEAREST)
```
(were self is the window)

**Comment by alderven** [comment]
> ```python
> spritelist.draw(filter=self.ctx.NEAREST)
> ```
> 
> (were self is the window)

Is it possible to do with single sprite?

**Comment by einarf** [comment]
> Is it possible to do with single sprite?

No. The filter applies to the entire sprite list. We can't change that state between every sprite because we batch draw them. A workaround could be scaling up that sprite either in the image itself or with Pillow. Optonally have a different spritelist for these.

**Comment by alderven** [comment]
OK. Thank you
