### ISSUE TITLE
Dead link in the docs

### ISSUE THREAD

**Issue by Jayman2000** [pythonarcade/arcade#960]
### What documentation needs to change? 
[Get Started Here](https://api.arcade.academy/en/latest/get_started.html?highlight=Learn%20arcade%20book%20on%20collisions#arcade-skill-tree)

### Where is it located?
`arcade/doc/get_started.rst` 

### What is wrong with it? How can it be improved?
The [Learn arcade book on collisions](https://learn.arcade.academy/en/latest/chapters/18_sprites_and_collisions/sprites.html#the-update-method) link 404s.

**Comment by einarf** [comment]
Fixed in 2.6.3. Be free to reopen
