### ISSUE TITLE
unable to resume stopped music

### ISSUE THREAD

**Issue by StrangeGirlMurph** [pythonarcade/arcade#961]
### What should be added/changed?
Both `arcade.Sound.stop()` and `arcade.stop_sound()` don't just stop the sound of the player but also delete the player completely.

```
    def stop(self, player: media.Player) -> None:
        """
        Stop a currently playing sound.
        """
        player.pause()
        player.delete() <---
        if player in media.Source._players:
            media.Source._players.remove(player)
```
- https://github.com/pythonarcade/arcade/blob/development/arcade/sound.py#L64
- https://github.com/pythonarcade/arcade/blob/development/arcade/sound.py#L171

Removing this part and some minor other changes would make it possible to play, pause and resume audio in arcade.

### What would it help with?
It would especially help with bringing music to games. Always starting music from the beginning can destroy the atmosphere of a game. Many songs just start slowly.

**Comment by Cleptomania** [comment]
Playing a sound returns a player object that can be used to pause it.

```python
# Start playing a sound for the first time
player = arcade.play_sound(my_sound)

# Whenever you want to pause it
player.pause()

# Whenever you want to restart it
player.play()
```

The `Sound` object in Arcade is not intended to represent an actively playing sound, but rather an audio source that can be played many times on top of itself. The player object returned from playing it is meant to be what is used to control a sound that is actively being played.

**Comment by StrangeGirlMurph** [comment]
Oh thanks! 
I didn't know the player has this functionality.

**Comment by Cleptomania** [comment]
The player returned from this is actually a Player object from Pyglet. The sound API in arcade is really just a small wrapper overtop of Pyglet’s media system. You can read more about that [here](https://pyglet.readthedocs.io/en/latest/programming_guide/media.html#controlling-playback)

I’ll admit the API a bit clunky as we converted to Pyglet from Soloud for the entire audio backend and maintained full backwards compatibility, so there were some instances of different concepts that had to be morphed to mesh together well enough. I’d expect it to become a bit more clear in future versions down the road.
