### ISSUE TITLE
AttributeError: module 'arcade' has no attribute 'exit'

### ISSUE THREAD

**Issue by StrangeGirlMurph** [pythonarcade/arcade#962]
### Actual behavior:
`arcade.exit()` (https://github.com/pythonarcade/arcade/blob/development/arcade/window_commands.py#L286) doesn't work.
Error: `AttributeError: module 'arcade' has no attribute 'exit'`

### Expected behavior:
Close the window and stop the program.
Instead `arcade.close_window()` (https://github.com/pythonarcade/arcade/blob/development/arcade/window_commands.py#L188) does what I want.

### Steps to reproduce/example code:
Just run `arcade.exit()` I think.

**Comment by einarf** [comment]
What version are you using? `arcade.exit()` definitely works for me in the latest version.

**Comment by pvcraven** [comment]
This problem does exist on 2.5.7. So I think if you upgrade it should work. But 2.6.x is a pretty major update and might break other stuff.

**Comment by StrangeGirlMurph** [comment]
Yes I was using arcade 2.5.7 upgrading fixed it. Thank you!
The experience is just like with `arcade.close_window()`.
