### ISSUE TITLE
Invalid comparison of signed integer with unsigned integer

### ISSUE THREAD

**Issue by Destranix** [pythonarcade/arcade#965]
## Bug Report
In sprite_list_geometry_cull_geo.glsl and sprite_list_geometry_no_cull_geo.glsl.
Some GLSL compilers report an signed integer overflow for the following line:
`if (vertex_id[0] == 4294967294) return;`
This is a designerror. You are using a unsigned magic number for check of a signed value.

This can be fixed by either making the variable unsigned or by using a signed magic number like -1.

P.S.: I haven't reproduced that issue myself, just got messaged by someone on a different platform and wanted to make sure that you know about the issue.

**Comment by einarf** [comment]
ah right. Thanks for noticing this. It was a silly oversight on my part.

**Comment by einarf** [comment]
Fixed in development brach. You can reference this as a depedency until 2.6.3 is  out : https://github.com/pythonarcade/arcade/archive/refs/heads/development.zip

**Comment by einarf** [comment]
Fixed in 2.6.3. Be free to reopen
