### ISSUE TITLE
Update all docs and change 'arcade.math' to 'pyglet.math'

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#966]
Running code from this example: https://api.arcade.academy/en/latest/tutorials/crt_filter/index.html
Getting error:
```
Traceback (most recent call last):
  File "C:/arcade_lib/crt_filter.py", line 4, in <module>
    from arcade.math import Vec2
ModuleNotFoundError: No module named 'arcade.math'
```

**Comment by Cleptomania** [comment]
We moved all of what was in `arcade.math` into `pyglet.math`. The API is identical so you can just replace 

```python
from arcade.math import Vec2
```

with 

```python
from pyglet.math import Vec2
```

The example just needs updated to reflect that change.

**Comment by MisoMosiSpy** [comment]
I would like to work on this if no one has singed up yet.

**Comment by einarf** [comment]
There was a question if we should alias this or not.

**Comment by MisoMosiSpy** [comment]
OK, will wait, thanks!

**Comment by pvcraven** [comment]
All arcade.math references are gone now, so closing.
