### ISSUE TITLE
crt_filter_example.py ===> ModuleNotFoundError: No module named 'arcade.math'

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#968]
Hello, i get this with stable and dev branch on pipenv with crt_filter_example.py :

**Traceback (most recent call last):
  File "crt_filter_example.py", line 4, in <module>
    from arcade.math import Vec2
ModuleNotFoundError: No module named 'arcade.math'**

**Comment by einarf** [comment]
See #966

**Comment by einarf** [comment]
2.6.4 released
