### ISSUE TITLE
Outdated travis-ci.org link

### ISSUE THREAD

**Issue by Jayman2000** [pythonarcade/arcade#969]
### What documentation needs to change?
[How to Submit Changes](https://api.arcade.academy/en/latest/development/how_to_submit_changes.html)

### Where is it located?
`arcade/doc/development/how_to_submit_changes.rst`

### What is wrong with it? How can it be improved?
The page says:

> Linux build testing is done on [TravisCI](https://travis-ci.org/pvcraven/arcade).

When you click on the TravisCI link, it takes you to a page that says

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Comment by pvcraven** [comment]
If memory serves, lack of OpenGL support is keeping us from CI builds on most platforms anyway. I'll remove.

**Comment by einarf** [comment]
I can set up github actions soon

**Comment by einarf** [comment]
2.6.4 released
