### ISSUE TITLE
Custom class name gets printed when loading Tiled map

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#970]
## Bug Report

When loading a Tiled map, custom class name is printed. This includes using animation editor in Tiled to create AnimatedTimeBasedSprite.

### Actual behavior:
Custom class name is printed.

### Expected behavior:
Nothing should be printed.

### Steps to reproduce/example code:
Create a Tiled map and use the animation editor to create an animated tile. Then load the map into arcade. "AnimatedTimeBasedSprite" gets printed to console.

**Comment by bunny-therapist** [comment]
arcade==2.6.3

**Comment by einarf** [comment]
Fixed in development branch

**Comment by einarf** [comment]
2.6.4 released
