### ISSUE TITLE
"Copy" button absent on some code examples

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#978]
Some code examples have "Copy" button:
https://api.arcade.academy/en/latest/examples/starting_template.html#starting-template
https://api.arcade.academy/en/latest/examples/happy_face.html#happy-face
etc.

![изображение](https://user-images.githubusercontent.com/21060932/135401963-e1225a9c-633c-4f75-b982-80e472af0907.png)

Some are not:
https://api.arcade.academy/en/latest/examples/drawing_text.html#drawing-text
https://api.arcade.academy/en/latest/examples/bouncing_rectangle.html#bouncing-rectangle
etc.

![изображение](https://user-images.githubusercontent.com/21060932/135402359-3f5fa4ea-0d09-440b-8285-bf442eac493f.png)

**Comment by pvcraven** [comment]
This happens when the example is too wide. The copy button is there, you just have to scroll to the right.

The mentioned examples need to be updated with shorter line lengths.

**Comment by pushfoo** [comment]
I think this may be more permanently addressable by altering our theme's CSS. We currently position the button against the right side of the parent div, which will have a scrollbar in some cases. 

If we position against the left side instead, it should let us consistently place the copy button at the top. There will probably be additional steps needed to make it look great consistently, maybe media queries and/or calc directives.

**Comment by pvcraven** [comment]
Checked into dev. Closing.
