### ISSUE TITLE
check_for_collision_with_lists requires Lists

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#980]
We limit `check_for_collision_with_lists` to lists only. There are good reasons to support things like tuples, sets and deques.

This also includes platforms in `PhysicsEnginePlatformer`.

I'm helping out on a voxel game and it's not ideal to maintain lists of spritelists for the chunks.

**Comment by Cleptomania** [comment]
I believe the existing code should work out of the box with any type of iterable assuming we remove the `isinstance` check for list. This means any type could be accepted and throw an error that maybe doesn't make sense.

Are we thinking just remove the `isinstance` check in `check_for_collision_with_lists` and update the type annotation to a Union containing all the possible iterable types? I'd be in favor of doing that.

**Comment by einarf** [comment]
`Sequence[SpriteList]` or `Iterable[SpriteList]`?

**Comment by Cleptomania** [comment]
I used `Iterable[SpriteList]` for now, we can change to Sequence or something more specific later if we find we need to, but this should work out of the box as it is for anything that is iterable.

**Comment by einarf** [comment]
2.6.4 released
