### ISSUE TITLE
why scene has no __getitem__ ?

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#981]
Hello,
i have a spritelist in my scene, i need to iterate over it because i have text to draw close to my sprites.
I use a tiled map and scrolling camera, the sprites have good behaviour, but the text follows the camera movement.
I'd like my text to stay close to my sprites.
When i want to acces to the sprite in the spritelist to return their position, i do this:

```
for obj in self.scene["name_mapping"]["Memobjs_spritelist"):  
            try:
                arcade.draw_text(f" {obj}  size {sys.getsizeof(obj)}  ", obj.pos_XY[0] + DECTEXT, obj.pos_XY[1], arcade.color.GREEN, 20)
```
**TypeError: 'Scene' object is not subscriptable**

**Comment by pyweeker** [comment]
i did this to solve my problem, may be usefull for other ones:

```
for obj in self.memobjs_data:  
            try:
                arcade.draw_text(f" {obj}  size {sys.getsizeof(obj)}  ", obj.pos_XY[0] + DECTEXT -self.camera.position[0], obj.pos_XY[1]-self.camera.position[1], arcade.color.GREEN, 20)
        except:
            pass
```

**Comment by Cleptomania** [comment]
Scene has two possible ways to get a specific SpriteList.

You can do either:
```python
my_spritelist = my_scene.name_mapping["My Layer Name"]
```

or 

```python
my_spritelist = my_scene.get_sprite_list("My Layer Name")
```

**Comment by Cleptomania** [comment]
I've added support now for __getitem__ as well so you can sub-script a Scene object to retrieve a SpriteList like so:

```python
my_spritelist = my_scene["My Layer Name"]
```

If you try to access a layer which doesn't exist, it will raise a KeyError informing you a layer by that name doesn't exist, like you would expect a regular python dictionary to function.

**Comment by pyweeker** [comment]
Thank you Darren !

Le dim. 3 oct. 2021 à 22:04, Darren Eberly ***@***.***> a
écrit :

**Comment by einarf** [comment]
2.6.4 released
