### ISSUE TITLE
Redundant if statement in `setup.py`

### ISSUE THREAD

**Issue by Jayman2000** [pythonarcade/arcade#983]
### What should be added/changed?
`setup.py` says
```python
if sys.platform == "darwin":
    required_python_version = ">=3.6"
else:
    required_python_version = ">=3.6"
```
This if statement is redundant. If the code just said `required_python_version = ">=3.6"`, it would still do the same thing.

### What would it help with?
This change would make `setup.py` easier to understand. It would also make `setup.py` shorter.

**Comment by einarf** [comment]
Thanks! It was a lingering old hack
