### ISSUE TITLE
UIInputText does not work with 3 byte color

### ISSUE THREAD

**Issue by pvcraven** [pythonarcade/arcade#988]
Setting text_color to arcade.color.WHITE causes an error in UIInputText. Setting it to (255, 255, 255, 255) so you include the alpha works though.

**Comment by einarf** [comment]
https://github.com/pythonarcade/arcade/blob/c928408a9bcf98d20f4f93f267d32f6624962906/arcade/gui/widgets.py#L956-L975

**Comment by einarf** [comment]
2.6.4 released
