### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#994]
This issue tracks what we need for python 3.10 support. It's mainly about dependencies.

Dependencies having 3.10 wheels

- [x] [Pillow](https://pypi.org/project/Pillow/)
- [x] [Shapely](https://pypi.org/project/Shapely/)
- [x] [pymunk](https://pypi.org/project/pymunk/)

Other dependencies don't need binary distributions and should ideally work out of the box.

**Comment by Cleptomania** [comment]
I haven't tested pytiled-parser with 3.10 yet but my initial guess is that it works out of the box. I don't think there's anything going on in it that should break with 3.10. I will try and test later tonight

**Comment by sallywag** [comment]
Is arcade currently expected to work on 3.10? I'm seeing an issue when importing arcade that seems to have been brought up before. ModuleNotFoundError: No module named 'pymunkoptions'

**Comment by Cleptomania** [comment]
We currently don't have 3.10 support due to underlying dependencies not having 3.10 wheels yet. We expect that as soon as Shapely and Pymunk get wheels for 3.10 it should work. At most very minimal changes would be needed to make it compatible. 

It may be possible to build everything from source but you need extra dependencies and stuff for that, unsure what the results would be of that.

**Comment by einarf** [comment]
You should have seen errors when installing arcade. I hope you are using latest 2.6.x because there's no hope getting 2.5 or earlier working on python 3.10.

There might be pre-release wheels for python 3.10 popping up for shapely and pymunk (or soon).

**Comment by sallywag** [comment]
Thanks, in the mean time I can roll back my Python version. Was not able to get older versions of pymunk working with 3.10.

**Comment by einarf** [comment]
Bumped shapely to 1.8. Only need pymunk now.

**Comment by einarf** [comment]
https://github.com/viblo/pymunk/issues/203

**Comment by einarf** [comment]
pymunk works great, but it looks like shapely still have some issues.
https://github.com/Toblerity/Shapely/issues/1215

**Comment by einarf** [comment]
Support for M1 macs is also related to this issue as new wheels are needed. 1.8.0 should have wheels for M1 #990

**Comment by pvcraven** [comment]
Going to close as shapely is now optional. We'll need to revisit the topic later though.
