### ISSUE TITLE
TopLeft coordinates when  drawing rectangles

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#996]
Hello,
it is not always handy to draw from x,y centers .
Is it possible to get 4 angles or only topleft from calling arcade.draw_rectangle_filled for example ?

**Comment by einarf** [comment]
There are version using xywh : https://api.arcade.academy/en/latest/api/drawing_primitives.html

**Comment by pyweeker** [comment]
thank you Einar

Le jeu. 7 oct. 2021 à 10:18, Einar Forselv ***@***.***> a
écrit :

**Comment by einarf** [comment]
Closing this. Be free to reopen if the issue is not resolved.
