### ISSUE TITLE
Fix small spelling error in Ray Casting Shadows tutorial

### ISSUE THREAD

**Issue by rckwzrd** [pythonarcade/arcade#999]
### What documentation needs to change? 
Small spelling error in section 6 of the Ray Casting Shadows tutorial.

### Where is it located?
`/arcade/doc/tutorials/raycasting/index.rst`
line 364

### What is wrong with it? How can it be improved?
change `tje` to `the`

**Comment by einarf** [comment]
2.6.4 released
